### ISSUE TITLE
Date - could be a span of dates

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#101]
The CoDe Academies runs over 5 days - but it's not possible to signal that in the current date/location layout:

![image](https://cloud.githubusercontent.com/assets/155492/14582099/ecdecff0-03fb-11e6-88d1-715b6692846e.png)

Currently we do dates like this:

```
date_: 2016-08-15
time: 09—17:00
city: Copenhagen
```
 We need to be able to do something more like:

```
date_: 2016-08-15
enddate: 2016-08-19
time: 09—17:00
city: Copenhagen
```

And then make it look good.

The layout shouldbe data-driven: as in `enddate: 2016-08-19` is _optional_

**Comment by illus0r** [comment]
@lakruzz we can get rid of `time` till it's not relevant here. So we'll have a room for `date_end`.
I'll reuse existing `_includes/date-location.html`. If you'll set `date_end` in frontmatter it will show `date_end` instead of `time`

**Comment by jonnycoull** [comment]
@lakruzz is it possible to have the time on one line instead of 2?

**Comment by illus0r** [comment]
@jonnycoull yep! @lakruzz has made #102 for that.
