### ISSUE TITLE
No HTML in MarkDown files

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#103]
Related to the solution implemented in #94 
```
academy2016.md
academy2016
   trd.md
   aar.md
   cph.md
   osl.md
```

All five pages for the code academy now break with an important principle:

>MarkDown files (`.md`)  only contains
> * MarkDown
> * yaml (frontmatter)
> * Liquid includes

At this point we have a lot of hacked HTML (divs, styles etc.) 

...It has to go!!!!

**Comment by illus0r** [comment]
- [ ] academy
- [ ] aar.md 
- [ ] cph.md 
- [ ] osl.md 
- [ ] trd.md
