### ISSUE TITLE
Improve navigation to sub sites

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#104]
In the [Code academy page](http://www.code-conf.com/academy2016/) I have implemented the navigation to the four sub pages, by listing the date/time includes:

![image](https://cloud.githubusercontent.com/assets/155492/14585526/93f6ff4c-0479-11e6-8700-c7a1c427cee3.png)

This must be regarded as a temporary solution, we need to come up with a better solution

**Comment by jonnycoull** [comment]
Maybe a go sign at the end of each?

**Comment by lakruzz** [comment]
I think it should be more obvious that ti's something that can be clicked, and which will take you to a sub-page

**Comment by illus0r** [comment]
@lakruzz Mmm, a kind of..?

![image](https://cloud.githubusercontent.com/assets/797993/14709051/3ee174d6-07d7-11e6-8fd9-54b1d334039b.png)

**Comment by jonnycoull** [comment]
@lakruzz @illus0r 
So I've had a play with this file as a whole, and as per the SPONSOR documents, the pages for CODE ACADEMY all follow the grey colour scheme. 

@illus0r the top image needs cropping its to deep currently is that something I need to do? 

note new FULL PROGRAMME BUTTON with a arrow icon, which feels more clickable. or maybe it has a different name? find out more etc.

Also may need a separate issue but we need a writer or someone good at cutting copy to asess copy boxes that don't line up it looks messy. they need to line up. 

ill address the page its self next. 

[CODECONF_ACADEMEY_v3.pdf](https://github.com/Praqma/code-conf.com/files/230310/CODECONF_ACADEMEY_v3.pdf)

**Comment by jonnycoull** [comment]
PDF on last comment. or this grab.
![screen shot 2016-04-21 at 17 10 27](https://cloud.githubusercontent.com/assets/17589853/14716255/0e66493c-07e4-11e6-87eb-24e084ba22e3.png)

**Comment by jonnycoull** [comment]
in addition, sub pages could look like this.... @lakruzz @illus0r 
[CODECONF_ACADEMEY_vTRD.pdf](https://github.com/Praqma/code-conf.com/files/230354/CODECONF_ACADEMEY_vTRD.pdf)
![codeconf_academey_vtrd](https://cloud.githubusercontent.com/assets/17589853/14717022/7327341e-07e7-11e6-857b-20bebdb48522.jpg)

**Comment by jonnycoull** [comment]
also @lakruzz I've noticed on the site that the bottom sell has been re written to THE CONTINUIOUS DELIVERY AND DEVOPS COMPANY. this makes the bottom lop sided. so we need a word smith to conjure up an equal length bit for the other side.

**Comment by illus0r** [comment]
@jonnycoull 
> the top image needs cropping its to deep currently is that something I need to do?

yep, you have everything you need to crop the image so it suit the best. Let me know if you need some additional info

**Comment by jonnycoull** [comment]
@illus0r can you send me ideal pixel size so I can chop to exact size please. so there all the same depth, or shall I work backwards from the site?

**Comment by lakruzz** [comment]
I've taken the issue @jonnycoull mentioned regarding the text in the footer to a separate issue #121

**Comment by illus0r** [comment]
@jonnycoull the width of the img is 990px
Height can be any, but we can make this a standard. I.e. 560px.

**Comment by jonnycoull** [comment]
@illus0r thanks. ill re-supply the main code conf graphic. and the hats. (for the midway down bar)

**Comment by jonnycoull** [comment]
@illus0r all pics uploaded (hopefully)

**Comment by jonnycoull** [comment]
all ok to leave this with you @illus0r the images should be in GITHUB for the new icons and the mock ups are on here.

**Comment by illus0r** [comment]
@jonnycoull Yep, I've integrated them without a pull request (PR). I've closed PR it just now.

**Comment by illus0r** [comment]
@jonnycoull I'd improve this block somehow
![image](https://cloud.githubusercontent.com/assets/797993/15016098/251df808-1218-11e6-842b-eef1f54eba82.png)

We could make it more informative, cutting out repeating elements
![image](https://cloud.githubusercontent.com/assets/797993/15016150/64ee363c-1218-11e6-9d37-548c43887b97.png)

Then we can factor out `Full programme`
![image](https://cloud.githubusercontent.com/assets/797993/15016189/9e663658-1218-11e6-8637-44e303b9eeb1.png)

So we've got free space to fill it with something city related. We can add an image for each city for example and make an accent on city names.
![image](https://cloud.githubusercontent.com/assets/797993/15016339/3792f096-1219-11e6-8aa3-22178eadcb67.png)

**Comment by jonnycoull** [comment]
I'm going to be a huge pain in the bum, but we had to shift CODE ACADEMY back to orange, sorry @illus0r I thought i left a note on that page. 

hmmm. I think the last one looks best if were going that way BUT i don't think we need that BIG white copy. maybe something integrated into the boxes. leave it with me.

**Comment by jonnycoull** [comment]
So @illus0r a solution that uses both. and keep with the design.

![codeconf_academey_v4](https://cloud.githubusercontent.com/assets/17589853/15020429/ebe4bda4-1219-11e6-9e9d-6062a47d02e3.jpg)

**Comment by lakruzz** [comment]
I'm fine with this! Great job!

**Comment by lakruzz** [comment]
@illus0r This case is a briefing case, but I believe at this point we've come to an end, the design is ready, and we need to spawn out into actual workable tasks, please create the tasks and estimate them, give them the same priority as this one and put them in the same milestone ("Press ready").

**Comment by illus0r** [comment]
@lakruzz I'll implement within this task
