### ISSUE TITLE
CoDe Academy - Trondheim Date

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#105]
CoDe Academy Trondheim is sheduled for June 15th - whic is a Wednsday. Should it have been Man 13th?

http://www.code-conf.com/
![screen shot 2016-04-19 at 14 05 37](https://cloud.githubusercontent.com/assets/8004259/14638461/dca16178-0637-11e6-8889-5d6c66e5e36d.png)

http://www.code-conf.com/academy2016/

![screen shot 2016-04-19 at 14 06 15](https://cloud.githubusercontent.com/assets/8004259/14638511/f12820a0-0637-11e6-991e-ddd1c76c6ca2.png)

**Comment by meekrosoft** [comment]
Yes, it should be from Monday.

**Comment by adamhenriques** [comment]
Ivan, will you update throughout so dates  for trondheim is 13. Jun 2016

**Comment by adamhenriques** [comment]
Done
