### ISSUE TITLE
Improve design for programm

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#107]
![image](https://cloud.githubusercontent.com/assets/797993/14674552/4d746b68-070d-11e6-8b20-42685a999b75.png)

can be found on academy2016/trd/

**Comment by lakruzz** [comment]
Aaauch - my eyes literally hurt!

What can we do???

**Comment by jonnycoull** [comment]
Can someone send me the link to investigate this? Come up with a easy on
the eye design? Thanks

**Comment by illus0r** [comment]
@jonnycoull http://www.code-conf.com/academy2016/aar/, but not now. I've did it fixing #103, but my commit is hanging somewhere in Jenkins and I have no idea what did go wrong. Old jenkins link doesn't work http://code.praqma.net/ci/view/Websites/job/Web_new.code-conf.com-verify/ may be @lakruzz can help me, nobody on slack did.

**Comment by jonnycoull** [comment]
@illus0r did you see my comments from yesterday, or do you want them on
slack. let me know what elements you need to implement it. working on home
page ideas today.

**Comment by jonnycoull** [comment]
![codeconf_academey_vtrd](https://cloud.githubusercontent.com/assets/17589853/14739617/a5397b1c-0880-11e6-873f-a58d20182d87.jpg)
have a look....sorry the form is incorrect, I hadn't seen the full live page. but easily changed.
