### ISSUE TITLE
Repair broken styles on ticket form

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#108]
Background of the bottom should be white. It was before

![image](https://cloud.githubusercontent.com/assets/797993/14674652/c026f798-070d-11e6-81e0-51f9156797d2.png)

**Comment by illus0r** [comment]
@lakruzz can I fix it?

**Comment by lakruzz** [comment]
@illus0r 

We don't have any means of controlling the background color.

And actually it's not the background color that's the problem, but the fact that we crop off then bottom of the form.

We have a fixed height of 300px

This is what the same form looks like with height = 310 px

![image](https://cloud.githubusercontent.com/assets/155492/15604688/fc9da602-2401-11e6-9230-39a31f42f50b.png)

We should pay attention to #25 - that will solve the problem
