### ISSUE TITLE
Browse press material

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#116]
GitHub pages doesn't allow directory browsing

But I have dumped some files in http://www.code-conf.com/press/academy2016/ which I'd actually like users to browse:

Idea:

Can you create an index.md file in http://www.code-conf.com/press/academy2016/ that contains some liquid, which just lists (and links) the files in the folder - so that if I add more files they automatically show up as well.

**Comment by illus0r** [comment]
@lakruzz I've looked around but nothing suggests itself. This `directory` feature [was proposed](https://github.com/jekyll/jekyll/pull/585), but GHP doesn't allow it for sake of security. Jekylls decided to leave this functionality out of core. 
```
<ul>
  {% directory path: media %}
    <li> <img src="{{ file.url }}" /> </li>
  {% enddirectory %}
</ul>
```

I've bumped into this trouble making a gallery page for Praqma couple of months ago.
I can't estimate this for now. I can take a timebox to investigate.

**Comment by illus0r** [comment]
@lakruzz I wonder if we could use API to fetch dir list https://developer.github.com/v3/repos/contents/

**Comment by lakruzz** [comment]
The I think the best solution is simply to add an `index.md` file. 

In the front matter we specify an array of 

* Link text
* Description
* Small icon/image to use for the link
* A description of the content

And then add a `directory` layout.

This can also prove useful when we want to publish videos, presentations etc.

It's a little bit more hand-held but gives us more options and is easier to implement.

**Comment by illus0r** [comment]
Good! That's doable with ease. What's purpose of this file listing? Who will use it?

**Comment by lakruzz** [comment]
@illus0r 
It's for shipping press and promotion materials

**Comment by illus0r** [comment]
So we'll reuse existing `academy2016` layout, we'll list JPG and PDF files there. No dates, no filenames. Just titles. I'd make icons autogenerated by files' extentions.

The tiitle of the page will be `CoDe Academy: press materials`.

@lakruzz How people will get onto this page?

**Comment by lakruzz** [comment]
The page should exist, but it shouldn't be indexed or discoverable.

They only have access to the page if they know (or guess) the link - Typically I would send the link to them in a mail

**Comment by lakruzz** [comment]
Reopening, my solution in  c0d303b is just a quick and dirty hack - but it's not urgent anymore
