### ISSUE TITLE
Get CoDe STHLM on http://www.code-conf.com/

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#127]
We need code stockholm (continuous delivery & DevOps conference, stockholm, Nov 29th) in MVP on on http://www.code-conf.com/. 

We need the graphics similar to attached example made so Ivan can implement ir and we can get it online.

<img width="492" alt="screen shot 2016-04-25 at 17 35 43" src="https://cloud.githubusercontent.com/assets/8004259/14789320/403ac4da-0b0c-11e6-9ba7-a8b8ce4b9eb5.png">

**Comment by jonnycoull** [comment]
@adamhenriques the STHLM has been done for a while, all the bars currently on site are made from code i believe, @illus0r can facilitate the creation of this online but for reference here it is again. Also to not @illus0r the hyphen is 50% size and orange on all code cof items. not white as above. and should have the "on" icon at the end. are these are the logos. 
![codesthlm](https://cloud.githubusercontent.com/assets/17589853/14809846/aa5ed812-0b87-11e6-8c49-502f7754ef3d.jpg)

**Comment by adamhenriques** [comment]
Ok. @illus0r can we make code-sthlm visable on code-conf.com?

**Comment by illus0r** [comment]
@adamhenriques so we need a new page for CODE-STHLM, which will have a logo similar to Bok's image. Right?

**Comment by adamhenriques** [comment]
Yes, just like code Cph. Thx

Regards

Adam Henriques

**Comment by illus0r** [comment]
@adamhenriques we've already had this page: `code-sthlm-2016.md`. It's unpublished now. To publish remove line 
```
published: false
```
I've just colored hyphens.

**Comment by adamhenriques** [comment]
Great, thx

Regards

Adam Henriques

**Comment by illus0r** [comment]
@adamhenriques when you write address like `http://www.code-conf.com/` in the task titles it breaks my git alias and I can't start working on task easily.

BTW, every issue in this repo relates to `http://www.code-conf.com/` ;)
