### ISSUE TITLE
Create teaser copy for all events

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#129]

**Comment by adamhenriques** [comment]
@jonnycoull please find included teaser-copy. Let me know how it fits wordcount wise.

CoDe Copenhagen, Sep 13th
The CoDe conference brings together technologists and industry leaders and focuses on innovation through Continuous Delivery and DevOps.

CoDe Academy, 
Date 13 Jun 2016 Trondheim 
Date 15 Aug 2016 Where Copenhagen 
Date 22 Aug 2016 Where Aarhus
Date 29 Aug 2016 Where Oslo

A free 5 days intense hands-on course in Continuous Delivery, agile planning, Git, Jenkins, Test-driven development and Docker.

CoDe Stockholm, Now 29th
The CoDe conference brings together technologists and industry leaders and focuses on innovation through Continuous Delivery and DevOps.

Day Of Containers Stockholm, Aug 25th
A full day festival focused on hands-on workshops and demos of the Docker ecosystem and the newest trends of containerization for developers of all experience levels.

Day Of Containers Copenhagen, 29 Aug
A full day festival focused on hands-on workshops and demos of the Docker ecosystem and the newest trends of containerization for developers of all experience levels.

**Comment by jonnycoull** [comment]
That looks about right @adamhenriques if you see the one, "a free 5 days..." thats bang on.

**Comment by adamhenriques** [comment]
@jonnycoull updated

**Comment by jonnycoull** [comment]
awesome thanks, is that all the events/conferances we have written @adamhenriques ?

**Comment by adamhenriques** [comment]
@jonnycoull, yes that should be it; code Cph & Stockholm, day of containers Cph & Stockholm, and code academy

**Comment by lakruzz** [comment]
hey guys @adamhenriques @jonnycoull is this case still open Looks to me like we could close it.

It's assigned to Jonathan - is that right? It seems like it's @adamhenriques who's working it.

**Comment by adamhenriques** [comment]
It should be closed

Regards

Adam Henriques

**Comment by lakruzz** [comment]
All right @adamhenriques ...then close it :-)

**Comment by jonnycoull** [comment]
@illus0r your copy for the small pieces of copy on the home page.
