### ISSUE TITLE
Change default email adress in sponsor button

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#130]
Great with sponor inquireries! Will you change default email in sponsor button to ah@praqma.net

**Comment by illus0r** [comment]
Should it be main email of the code-conf.com?

**Comment by adamhenriques** [comment]
@illus0r in reality only for sponsor inquiries. However, if we can only use one mail - lets just keep info@praqma.

**Comment by illus0r** [comment]
Ok, I'll make a new variable for your mail.
