### ISSUE TITLE
Get info from Daniel Ståhl and Fatih Degirmenci for Codesthlm

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#136]
We need;

- Titles
- Abstracts
- Bios
- Pictures
- Twitterhandles (got Fatihs already)

**Comment by Andrey9kin** [comment]
Daniel's photo https://github.com/d-stahl-ericsson

**Comment by lakruzz** [comment]
@adamhenriques @Andrey9kin 

What is happening with the Stockholm event?
![image](https://cloud.githubusercontent.com/assets/155492/15285064/6daebe54-1b55-11e6-83ca-fd8170acbb21.png)

Don't we have _any_ speakers to present?

**Comment by adamhenriques** [comment]
They getting on today

Regards

Adam Henriques

**Comment by Andrey9kin** [comment]
@adamhenriques @lakruzz I'm just about to push an update
