### ISSUE TITLE
How to get speaker bio

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#137]
I Find myself clicking on the speaker pics - trying to learn more about them.

![image](https://cloud.githubusercontent.com/assets/155492/14877762/748e0c14-0d1f-11e6-813e-da85a069a291.png)

Any ideas on how we could incorporate access to the speaker bio, and what it should look like/behave?

@illus0r @jonnycoull

**Comment by illus0r** [comment]
Great, we've got some speaker info already

1. name
2. bio
3. position
4. img
5. social

@lakruzz what you'd like to add?
@jonnycoull how'd you present it?

**Comment by illus0r** [comment]
```
name: Diptanu Choudhury
bio:  >
  Diptanu is a Senior Engineer at HashiCorp, and works on large-scale distributed systems, cluster schedulers, service discovery and highly available and high throughput systems on the public cloud. He is a core committer to the Nomad cluster scheduler which has a parallel and distributed scheduler and support heterogeneous virtualized workloads. Prior to HashiCorp, Diptanu worked in the Cloud Platform group at Netflix, where he worked on the core platform infrastructure that powered the Microservices infrastructure of Netflix. He worked on Apache Mesos and wrote a cluster scheduler for running Docker on AWS, and also contributed to various reactive IPC and service discovery infrastructure projects.
position: Senior Engineer, HashiCorp
img: /images/speakers/diptanu.jpeg
social: >
  Twitter: [diptanu](https://twitter.com/diptanu)
```

**Comment by illus0r** [comment]
```
name: Jan U. Hagen
bio:  >
  Jan Hagen is an associate professor and a member of the faculty at European School of Management and Technology. Jan is particularly interested to understand how teams and organizations deal with errors. He is currently studying the interaction of flight crews in the cockpits of airline and military aircrafts. His research received media coverage in outlets like the Financial Times, Frankfurter Allgemeine Zeitung, The Guardian, Forbes, Harvard Business Manager. Jan is the author of [Confronting Mistakes: Lessons from the Aviation Industry when Dealing with Errors](https://www.esmt.org/confronting-mistakes-lessons-aviation-industry-when-dealing-errors)
position: Associate professor ESMT
img: /images/speakers/januhagen.png
social: >
  Publications: [ESMT](https://www.esmt.org/jan-u-hagen)
```

**Comment by illus0r** [comment]
some txt for example. You can find more [on repo](https://github.com/Praqma/code-conf.com/tree/gh-pages/_speakers)

**Comment by lakruzz** [comment]
I'm fine with the properties we currently use

**Comment by jonnycoull** [comment]
@illus0r @lakruzz is there a link to an old bio page?

**Comment by lakruzz** [comment]
http://archive.code-conf.com/cph15/program/

http://archive.code-conf.com/jues15/program/

**Comment by jonnycoull** [comment]
Thanks @lakruzz

**Comment by jonnycoull** [comment]
also in #139 see how hover state works in speakers.
![codeconf_speakers 3](https://cloud.githubusercontent.com/assets/17589853/14987598/1a796552-1148-11e6-89c1-e93fb6359caf.jpg)

**Comment by illus0r** [comment]
I'll start with @jonnycoull mockup. Links should be recolored, but I'll do it on the fly

![](https://cloud.githubusercontent.com/assets/17589853/14987679/69d2f014-1148-11e6-8130-05760d71b0ce.jpg)

**Comment by illus0r** [comment]
- [ ] output code
- [ ] put css on
- [ ] make *speaker's links* jump to exact person in the list

**Comment by illus0r** [comment]
Hi, @jonnycoull! Where to get this photo? 
![image](https://cloud.githubusercontent.com/assets/797993/15075782/d9ca3ad6-13ae-11e6-9623-042febdbd09f.png)

**Comment by jonnycoull** [comment]
Hi guys sorry I'm away at the mo it's from Lars archive, I'm back ties so
maybe Lars can give u accsess?

**Comment by illus0r** [comment]
@lakruzz in [the checklist](https://github.com/Praqma/code-conf.com/issues/137#issuecomment-217435253) I've showed, what part was implemented by now. I'll set size to `0` and branch out unfinished items into separate tasks.

**Comment by lakruzz** [comment]
@illus0r regarding  4aa0992 - pleade deliver _one_ commit at time: 

one commit to one issues

I you don't we will squash it (as in  4aa0992) and we loose some traceability this way.

I thing this is a matter of you using `pull` - without `--rebase`

Dont do: 👎 
```
git pull
```
If there are updates, you'll get an extra commit with nothing in it except the merged files.

Instead make it a habit to use : 👍 

```
git pull  --rebase
```

...and you'll be fine

**Comment by lakruzz** [comment]
I am closing this briefing, we have created work items for all things mentioned in this briefing.
