### ISSUE TITLE
Design for Speaker's page

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#139]
Subtask of #137

we've got some speaker info already

1. name
2. bio
3. position
4. img
5. social

some txt for example. You can find more [on repo](https://github.com/Praqma/code-conf.com/tree/gh-pages/_speakers)

```
name: Diptanu Choudhury
bio:  >
  Diptanu is a Senior Engineer at HashiCorp, and works on large-scale xdistributed systems, cluster schedulers, service discovery and highly available and high throughput systems on the public cloud. He is a core committer to the Nomad cluster scheduler which has a parallel and distributed scheduler and support heterogeneous virtualized workloads. Prior to HashiCorp, Diptanu worked in the Cloud Platform group at Netflix, where he worked on the core platform infrastructure that powered the Microservices infrastructure of Netflix. He worked on Apache Mesos and wrote a cluster scheduler for running Docker on AWS, and also contributed to various reactive IPC and service discovery infrastructure projects.
position: Senior Engineer, HashiCorp
img: /images/speakers/diptanu.jpeg
social: >
  Twitter: [diptanu](https://twitter.com/diptanu)
```

```
name: Jan U. Hagen
bio:  >
  Jan Hagen is an associate professor and a member of the faculty at European School of Management and Technology. Jan is particularly interested to understand how teams and organizations deal with errors. He is currently studying the interaction of flight crews in the cockpits of airline and military aircrafts. His research received media coverage in outlets like the Financial Times, Frankfurter Allgemeine Zeitung, The Guardian, Forbes, Harvard Business Manager. Jan is the author of [Confronting Mistakes: Lessons from the Aviation Industry when Dealing with Errors](https://www.esmt.org/confronting-mistakes-lessons-aviation-industry-when-dealing-errors)
position: Associate professor ESMT
img: /images/speakers/januhagen.png
social: >
  Publications: [ESMT](https://www.esmt.org/jan-u-hagen)
```

**Comment by jonnycoull** [comment]
@illus0r @lakruzz still looking at colour but how about the attached? 

• same collapsable style as the speakers on the conference pages. 
• Now has a READ MORE and READ LESS, as a bit annoying I can't collapse the stack back after reading. 

![codeconf_speakers 2](https://cloud.githubusercontent.com/assets/17589853/14987538/ec2a39d8-1147-11e6-8f61-30e6433c8b96.jpg)
![codeconf_speakers 3](https://cloud.githubusercontent.com/assets/17589853/14987540/ec43ade6-1147-11e6-8b8a-368d0e987a9a.jpg)

**Comment by jonnycoull** [comment]
@illus0r @lakruzz Whoops was supposed to be orange colours. also @illus0r we need to switch body copy to a "code esc" font. I've used courier. any suggestions?
![codeconf_speakers v2](https://cloud.githubusercontent.com/assets/17589853/14987679/69d2f014-1148-11e6-8130-05760d71b0ce.jpg)

**Comment by illus0r** [comment]
@jonnycoull looks encouraging, I can implement it!
But links should be same colored, that's rule.
What is link on this image? Hard to guess now.
![image](https://cloud.githubusercontent.com/assets/797993/15010014/904a86d0-11f2-11e6-87ce-dd16e3c9e8a6.png)

So we use two fonts: monospace for block texts and condensed for headers, right?

**Comment by jonnycoull** [comment]
ah thats not a link thats the box in its expanded form (when u click read more) make sense @illus0r ? same on the other issue, so u could see the box and how it works as per your work on the speakers bits already.

**Comment by jonnycoull** [comment]
@illus0r is monospace the current body copy? see example.... @lakruzz wants it to look more like code. so I'm open to suggestion. abolition is headers, and pulled out information. 


![screen shot 2016-05-04 at 10 28 59](https://cloud.githubusercontent.com/assets/17589853/15010269/0bd5338c-11e3-11e6-9eb1-4d60168bdc8c.png)

![screen shot 2016-05-04 at 10 27 15](https://cloud.githubusercontent.com/assets/17589853/15010201/c9f3e0c6-11e2-11e6-89b3-c1b3e1e9e278.png)

**Comment by jonnycoull** [comment]
@illus0r the bottom one is what i currently see online. @meekrosoft tweaked it on here.....

http://www.code-conf.com/academy2016/trd/

**Comment by illus0r** [comment]
@jonnycoull 
1. Links<br> I meant the color scheme on this mockup: it uses *link color* for *not-links* like `twitter`. Other links like `@ETHOMSON` don't. If you think I didn't get the idea of your last comment, could you paraphrase?
2. [Monospace](https://www.google.ru/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=mpnospace) is not the current body copy. Current is `Roboto`. We can set it to something like `Consolas`, `Inconsolata` or similar, just for fun. That'll make the site more _code-like_ but less readable. Guys from ello.co olso used monospaced font before (the switched to [Atlas Grotesk](https://commercialtype.com/catalog/atlas) now)

**Comment by illus0r** [comment]
@lakruzz I was thinking this page will contain bio of the single speaker, not everyone. That's much easy to implement, than listing all conference related speakers.

Bok's solution make sense though: it's convenient way of learning more about a conference.

**Comment by illus0r** [comment]
@jonnycoull I don't see `position`s on your mockups

**Comment by jonnycoull** [comment]
@illus0r position? as in the job he holds? thats the big microsoft or BLACK ABOLITION FONT under his name, sorry if i misunderstood the question. 

And links ah sorry my fault I was thinking that the link was just an underline version of what ever was clickable. colours got it!

**Comment by illus0r** [comment]
@jonnycoull Yep, you're right. I was thinking the company is a separate field. Yep, we can output `company` and `position` within one field. Just like here 
![image](https://cloud.githubusercontent.com/assets/797993/15040791/ece2f22e-12bf-11e6-8805-dcf416dd437f.png)

**Comment by illus0r** [comment]
@jonnycoull so we are looking forward to @lakruzz reply to [my comment](https://github.com/Praqma/code-conf.com/issues/139#issuecomment-216881295), that's the only showstopper.

**Comment by lakruzz** [comment]
@illus0r:
I had a hangout with @jonnycoull I'm good with the one-page design that has all speakers on the same page

**Comment by illus0r** [comment]
Good, I'll close by now
