### ISSUE TITLE
Date span - adjustment

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#145]
When the date is a span - like this

![image](https://cloud.githubusercontent.com/assets/155492/15043226/4132cf7e-12cb-11e6-9a53-0920152d296c.png)

is should read 

22-26 AUG 2016

**Comment by illus0r** [comment]
Make sense! I'll do it

**Comment by illus0r** [comment]
Done. If months differ, I output them.
![image](https://cloud.githubusercontent.com/assets/797993/15073841/6071bd58-13a4-11e6-95d1-ddd7c887d5ef.png)

**Comment by lakruzz** [comment]
Gr8!
