### ISSUE TITLE
New header pic on for CoDe Stockholm

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#148]
We use the same pic for Day Of Containers Stockholm and CoDe Stockholm. Will you change pic on CoDe Stockholm http://www.code-conf.com/code-sthlm-2016/

Intel cor choise of pic; Target audience of CoDe is more c-levels and mangers

**Comment by jonnycoull** [comment]
uploaded. @illus0r

**Comment by lakruzz** [comment]
Back to you @adamhenriques

**Comment by Andrey9kin** [comment]
@adamhenriques @lakruzz @jonnycoull guys I hope you don't mind me fixing those issues. Today is my events day - so I'm trying to get as far as I can since the next events day only in a week.
