### ISSUE TITLE
Frontpage: fix font family on header

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#152]
subtask of #100

Use `marker` font-family for subheader
![image](https://cloud.githubusercontent.com/assets/797993/15247055/344b4c00-191a-11e6-8f24-79b3dca3aea3.png)

**Comment by jonnycoull** [comment]
@adamhenriques was working on a bit of copy for the "blah" thats there now.

**Comment by adamhenriques** [comment]
@jonnycoull is it still on me - or did I delivert it - dont remember?

**Comment by lakruzz** [comment]
This case is about changing the font to marker. 

Where is the font that we need to incorporate? is it one that we need to buy? where from? @jonnycoull do you know that?

**Comment by jonnycoull** [comment]
@lakruzz its been used here, http://www.code-conf.com/doc-cph-2016/

its free. https://www.fontsquirrel.com/fonts/permanent-marker
