### ISSUE TITLE
Frontpage: style main event

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#154]
IN reference to briefing #100

![image](https://cloud.githubusercontent.com/assets/797993/15247264/b5fc64cc-191b-11e6-8668-9d37ccf910cc.png)

**Comment by illus0r** [comment]
- [ ] make main event be narrow, in grid
- [ ] output and style image as link
- [ ] add power icon to title

**Comment by illus0r** [comment]
#188 needed to merge

**Comment by lakruzz** [comment]
@illus0r I closed #188

**Comment by illus0r** [comment]
closed by 5926fc5
