### ISSUE TITLE
Frontpage: implement UP NEXT block

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#156]
IN reference to briefing #100 

![image](https://cloud.githubusercontent.com/assets/797993/15247480/38c825b6-191d-11e6-8e36-e36244a48512.png)

WIthout ![image](https://cloud.githubusercontent.com/assets/797993/15247504/63328ab2-191d-11e6-9938-4c6d68990fc4.png) link by now

**Comment by illus0r** [comment]
- [x] output html
- [ ] style things
- [ ] adapt height

**Comment by illus0r** [comment]
result pushed to `154-Frontpage-style-main-event`

**Comment by illus0r** [comment]
#188 needed to merge

**Comment by lakruzz** [comment]
@illus0r I closed #188

**Comment by illus0r** [comment]
closed by 5926fc5
