### ISSUE TITLE
Frontpage: make Get Involved pullout

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#157]
Subtask of #100

![image](https://cloud.githubusercontent.com/assets/797993/15247702/9c6a7b2c-191e-11e6-8285-17a0761195c9.png)

**Comment by illus0r** [comment]
@jonnycoull 
still need?

**Comment by jonnycoull** [comment]
@illus0r yes along with the other task. @monaslarsen @adamhenriques can you supply a brief description of each item as shown above? @illus0r Ill make a milestone HomepageComplete

**Comment by illus0r** [comment]
@monaslarsen I need your help!
I know, you are on the more important task. When can you make this one?

**Comment by monaslarsen** [comment]
@illus0r I can work on it from Wednesday, I hope that is early enough?

**Comment by illus0r** [comment]
@monaslarsen yep, sure :)

**Comment by jonnycoull** [comment]
I'll get @BrucePhable to draft this copy to get it moving.

**Comment by BrucePhable** [comment]
https://docs.google.com/a/firm20.com/document/d/11ZGR4PNDWr8IC1Gbfq9GrENhlqtwjXnK_v6WL9Z9Z-c/edit?usp=sharing

Suggested descriptions for each one

**Comment by illus0r** [comment]
@BrucePhable Hi there! I've requested access as well. Or just paste the copy right here

**Comment by illus0r** [comment]
@BrucePhable I'm the guy who implement things, so I need it ;)

**Comment by BrucePhable** [comment]
Get Involved Pullout:

**Conferences:** We host conferences on Continuous Delivery all year round. Sign up and join us. 

**Meet-Ups:** CoDe communities are emerging all over Scandinavia. Find one near you. 

**Training:** Get up to speed with our courses on CoDe, Atlassian, Git, Docker & Jenkins. 

**Hackathons:** Informal gatherings where we exchange ideas and do some coding. Just bring your brain and your laptop.

**Comment by illus0r** [comment]
@jonnycoull Where can I find images?

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/19110964/aede1314-8b05-11e6-9dae-87cd8078e62b.png)

- [ ] Get images from Bok
- [ ] Style header
- [ ] Style paragraphs

**Comment by jonnycoull** [comment]
ill have to fish them out from the mock, square you need correct?

**Comment by illus0r** [comment]
@jonnycoull yep, squares are perfect

**Comment by jonnycoull** [comment]
@illus0r this is on me for new images.

**Comment by illus0r** [comment]
@jonnycoull 
What images to use?

**Comment by jonnycoull** [comment]
Uploading now.

![conferance](https://cloud.githubusercontent.com/assets/17589853/19558473/a543608e-96c2-11e6-878d-e2853741a419.jpg)
![hack](https://cloud.githubusercontent.com/assets/17589853/19558474/a5467936-96c2-11e6-8998-e33a527c8288.jpg)
![meeting](https://cloud.githubusercontent.com/assets/17589853/19558475/a546a514-96c2-11e6-85f8-8b8d803eec25.jpg)
![train](https://cloud.githubusercontent.com/assets/17589853/19558476/a54796d6-96c2-11e6-8094-de8cbec71528.jpg)
