### ISSUE TITLE
Frontpage: make 3 navigational banners

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#158]
Subtask of #100

![image](https://cloud.githubusercontent.com/assets/797993/15247788/0fd88d9c-191f-11e6-9310-087404a40da8.png)

**Comment by illus0r** [comment]
@jonnycoull
is that's what we still need?

**Comment by jonnycoull** [comment]
@illus0r yes ill make up some graphics.

**Comment by illus0r** [comment]
Hi, @jonnycoull !
What about graphics for that? I can make it myself, if you have no time

**Comment by jonnycoull** [comment]
Hi @illus0r did u see the above?

**Comment by jonnycoull** [comment]
@illus0r will supply new mock up as discussed.

**Comment by illus0r** [comment]
@jonnycoull 
Looking forward to see it. The issue is frozen until i get it

**Comment by jonnycoull** [comment]
![screen shot 2016-10-20 at 12 26 33](https://cloud.githubusercontent.com/assets/17589853/19558100/7ec502ac-96c0-11e6-9238-a52f8fa08582.png)

uploading SVG now @illus0r

**Comment by jonnycoull** [comment]
@illus0r in icons.

**Comment by illus0r** [comment]
@jonnycoull  What's the subject of email if I click `contact-us`?

**Comment by jonnycoull** [comment]
There must be a info@praqma? Ask Adam

**Comment by illus0r** [comment]
@jonnycoull 
I'm talking about the mail subject. Like *Hi, CoDe-Conf guys!*

It'll take place of bold text on the screenshot 
![image](https://cloud.githubusercontent.com/assets/797993/19596056/67ed08d8-9795-11e6-96d4-62d5799d4923.png)

I'll use the default email `info@praqma.com`. @adamhenriques, any objections?

**Comment by jonnycoull** [comment]
Yep default is fine. I think, I just didn't have the actual address before. @adamhenriques all ok?

**Comment by jonnycoull** [comment]
Hey is this All done @illus0r can we close???? whats left to do?

**Comment by illus0r** [comment]
@timea delivered, the commit hangs like the previous one

**Comment by jonnycoull** [comment]
@illus0r not sure what that means, @timea how can we fix to close this milestone. asap please.

**Comment by illus0r** [comment]
@jonnycoull you can 🔫 the milestone
