### ISSUE TITLE
Prettify footer

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#159]
Related to briefing in #135 

![322e1f22-12d2-11e6-9de6-278e27e6f7fd](https://cloud.githubusercontent.com/assets/17589853/15248332/9288cfe4-1911-11e6-81b3-c4d3019248b4.jpg)

**Comment by jonnycoull** [comment]
No this is a sub task of #135 that one above is old. do not use. @illus0r

**Comment by jonnycoull** [comment]
![322e1f22-12d2-11e6-9de6-278e27e6f7fd](https://cloud.githubusercontent.com/assets/17589853/15248332/9288cfe4-1911-11e6-81b3-c4d3019248b4.jpg)

**Comment by lakruzz** [comment]
This case is only about changing the actual footer (move logo to the right, instead of having it in the middle)

The menu below has it's own case 
and the subscribe form is in #160
