### ISSUE TITLE
Make Newsletter Form

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#160]
Spinn off from #135 

![322e1f22-12d2-11e6-9de6-278e27e6f7fd](https://cloud.githubusercontent.com/assets/17589853/15248348/9f00a7ec-1911-11e6-9fe8-0fd8c4b5afe5.jpg)

**Comment by jonnycoull** [comment]
? where di u get that its old @illus0r its on issue #135 header and footer.

**Comment by illus0r** [comment]
@jonnycoull oh, sorry.
Note for myself: take from @jonnycoull the most fresh mockup when I'm back

**Comment by jonnycoull** [comment]
![322e1f22-12d2-11e6-9de6-278e27e6f7fd](https://cloud.githubusercontent.com/assets/17589853/15248348/9f00a7ec-1911-11e6-9fe8-0fd8c4b5afe5.jpg)

**Comment by illus0r** [comment]
> @illus0r for the latest HEADER & FOOTER look at issue #135 before you race ahead on this.

**Comment by lakruzz** [comment]
This issue is only about implementing the subscribe form:

![image](https://cloud.githubusercontent.com/assets/155492/15285813/e2af8590-1b59-11e6-96e9-0c0a77f73f0b.png)

**Comment by illus0r** [comment]
- [ ] html
- [ ] css
- [ ] js
- [ ] mailchimp

**Comment by illus0r** [comment]
@adamhenriques, @monaslarsen 
Hi there 😀 
Do we have a set up mailchimp account to use with this newsletter?

**Comment by illus0r** [comment]
I'll save the link to mailchimp's doc here http://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website

**Comment by adamhenriques** [comment]
@illus0r yes; Username; praqma, pw; i send on hangout
