### ISSUE TITLE
Add new All Events page

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#161]
Subtask of #100

- [x] take this mockup from @jonnycoull 
![image](https://cloud.githubusercontent.com/assets/797993/15248237/c77c43f6-1921-11e6-990d-9b4a8951c3aa.png)

**Comment by illus0r** [comment]
Hi, @jonnycoull ! Could you post a larger version of this

![](https://cloud.githubusercontent.com/assets/797993/15248237/c77c43f6-1921-11e6-990d-9b4a8951c3aa.png)

**Comment by jonnycoull** [comment]
![subpage_v2](https://cloud.githubusercontent.com/assets/17589853/15580437/a915682c-2360-11e6-9a6c-1049d1a9177a.jpg)
Will those do? @illus0r also, I've uploaded that pen picture into images a while back so you have that.

**Comment by illus0r** [comment]
@jonnycoull 👏 
Can we access this menu on other pages?

![image](https://cloud.githubusercontent.com/assets/797993/15605541/37d1da88-240f-11e6-9105-851b9f3d4ba5.png)

**Comment by jonnycoull** [comment]
Hi @illus0r Every CONFERENCE, TRAINING, MEET-UPS, HACKATHONES etc are on the TOP BAR. which i don't believe you've implemented yet. it was supplied a few weeks ago. essentially that menu is a repeat. its just to make it more obvious you can filter the results quickly or see all as an option. 

IMPORTANT NOTE: ignore training, last i spoke to @lakruzz  this is remaining on PRAQMA's own home site not here. 

I can't see the issue this was on but its somewhere. 

Id suggest that this be your no1. priority sorting the top and bottom. 

![codeconf_menu options_v4](https://cloud.githubusercontent.com/assets/17589853/15605699/7effc88a-23ff-11e6-8724-14cb7a95ab2e.jpg)

**Comment by lakruzz** [comment]
We have a MVP of this now (in case #221)  I'm deferring it to the backlog for now

**Comment by illus0r** [comment]
@jonnycoull 
I guess this is done. Can we get rid of?

**Comment by jonnycoull** [comment]
It is done. @illus0r close away.
