### ISSUE TITLE
mando walls update

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#163]

**Comment by lakruzz** [comment]
@adamhenriques  I can see that this branch is not merged into gh-pages, and I can see that you delivered it tree times 

![image](https://cloud.githubusercontent.com/assets/155492/15284965/ed23c7b6-1b54-11e6-83a6-b50a0cc14db9.png)

(Don't do that - it's like sending the print to the printer three times, if the first one didn't come through, the next one wont either - you're adding to a queue, so when the thing start working again, you'll just process it three times, which isn't what you want).

Maybe Jenkins wasn't working at the time, or something else went wrong - let me know if you need help to sort it out.

**Comment by adamhenriques** [comment]
Can you just delete it?

Regards

Adam Henriques

**Comment by lakruzz** [comment]
Delete _it_  Is that the _branch_, the _issue_ or what exactly do you mean by _it_?

Can you delete _it_ yourself? then please go ahead 👍
