### ISSUE TITLE
show speakers confs on speaker page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#166]
Related to the briefings in #137 

For each speaker list the conferences that they are speaking at:

![image](https://cloud.githubusercontent.com/assets/155492/15286333/ad4a7e52-1b5c-11e6-992a-9ec02acf18e1.png)

**Comment by Andrey9kin** [comment]
@illus0r @lakruzz @timea I have a question about speakers page - will it be any possibility to filter speakers when I'm coming to the speakers page from the conference page? I'm asking because it will be much more speakers than we have now and already now it is very confusing to see all speakers who ever talked on our conferences. To support my point I have @les-praqma just next to me who is as much confused as I'm

**Comment by lakruzz** [comment]
@Andrey9kin @les-praqma 

Check #171

**Comment by Andrey9kin** [comment]
@lakruzz thanks!

**Comment by timea** [comment]
@lakruzz do we have an excel sheet or so where I can see all the conferences, all the speakers in one place?

**Comment by lakruzz** [comment]
No, no sheet, they are all online ...or do I misunderstand? What would you
achieve with a spreadsheet?
On May 26, 2016 16:02, "timea" <notifications@github.com> wrote:

@lakruzz <https://github.com/lakruzz> do we have an excel sheet or so where
I can see all the conferences, all the speakers in one place?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Praqma/code-conf.com/issues/166#issuecomment-221879549>

**Comment by timea** [comment]
I was looking for a faster way then going through all event pages to see which conference the speaker is speaking at (like if Mona or anyone else who is an organizer had a list of the speakers in a text document grouped by conference ), but okay, I was just curious.

**Comment by lakruzz** [comment]
There is no faster way than

```
for each speaker
  for each event
    print event if speaker speaks at event
````
However, computers can do that - kinda pretty fast :-)

**Comment by timea** [comment]
Lovely! :)

**Comment by lakruzz** [comment]
@timea 

This issue needs to be made ready to work on - It currently needs and estimate.

I've assigned the case to you, please just do the following:

- Provide a realistic estimate
- Remove the "Action: Needs grooming" label
- Unassign yourself from the issue (just leave the issue unassigned)

**Comment by illus0r** [comment]
This task should be done before #171, so I'll take this first

**Comment by illus0r** [comment]
@timea do we need `All speakers` page, where every speaker will be listed?

**Comment by timea** [comment]
@illus0r  I believe it is good that we have it. It is just that when we are on one event, that needs a separate one showing only the event related ones.

**Comment by illus0r** [comment]
I've make #239 for that
