### ISSUE TITLE
Better foto on Speakers page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#168]
Spinn off from #137 

Find a better photo for the speakers page http://www.code-conf.com/speakers

![image](https://cloud.githubusercontent.com/assets/155492/15286470/8e3b635e-1b5d-11e6-9c18-c120f8b2e04c.png)

**Comment by jonnycoull** [comment]
![speakerbios](https://cloud.githubusercontent.com/assets/17589853/15314268/cfe1a40c-1c08-11e6-9382-209080b7ff95.JPG)

what would eventually be good is a line up of speakers against the wall aka usual suspects style. @lakruzz

**Comment by lakruzz** [comment]
Closed praqma/praqma.com#278 which was a duplicate issue in a different repo.

I just improved the one that was already there:
![image](https://cloud.githubusercontent.com/assets/155492/15605207/cfbc8984-2404-11e6-9f18-00139a6460fb.png)
