### ISSUE TITLE
List speakers - filter per event

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#171]
This issue is a spin off from @Andrey9kin comment on #166 

> I have a question about speakers page - will it be any possibility to filter speakers when I'm coming to the speakers page from the conference page? I'm asking because it will be much more speakers than we have now and already now it is very confusing to see all speakers who ever talked on our conferences.

__We need to be able to filter speakers page, so that only speakers that actually speak at conference are listed e.g. for  CoDe CPH 2016__

We need something like one of:

1. www.code-conf.com/speakers/codecph2016
2. www.code-conf.com/speakers/#codecph2016
3. www.code-conf.com/codecph2016/speakers/

(1) Would be implemented as a static page per event
(2) Would be implemented as currently; one contains-everything page but is filtered using JS (This is how the use of tags is implemented for filtering stories on praqma.com
(3) Is roughly the same implementation as (1) but the page would be located as a sub under the event.

---
I's advocate from (2) as it probably will be able to reuse quite a lot of the implementation at www.praqma.com/stories/

**Comment by lakruzz** [comment]
@illus0r 
This issue needs to be made ready to work on - It currently needs and estimate.

I've assigned the case to you, please just do the following:

- Provide a realistic estimate
- Remove the "Action: Needs grooming" label
- Unassign yourself from the issue (just leave the issue unassigned)

**Comment by illus0r** [comment]
Ideally
---

- speakers on event pages are linked to speaker's page.
- this link contains `event_id` to filter speakers and `speaker_id` to scroll to speaker we've clicked.

Faster
---
Current script doesn't accept two id's at once.
@lakruzz can we show just a page of filtered speakers, without scrolling to clicked one? We can implement that later.

**Comment by illus0r** [comment]
Title should look like 

![image](https://cloud.githubusercontent.com/assets/797993/15816400/4ebb6628-2bdb-11e6-91d3-559c2c2935e1.png)

I think we should keep the megaphone as it is about the speakers
and lose the switch icon at the end

**Comment by illus0r** [comment]
- [ ] on speakers page link conferencess to conferences' pages
- [ ] make a task for adding a full speakers list (we need a menu item for that)
- improve logo
   - [ ] proper color for title
   - [ ] proper text (title, not basename)
   - [ ] proper `OC` color

**Comment by illus0r** [comment]
closed in f7bedc8
