### ISSUE TITLE
payback time on header.html 

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#173]
https://github.com/Praqma/code-conf.com/blob/gh-pages/_includes/header.html

This is ugly!

How did we end up with hard coded sponsor inquiry in the header - is should be done right - add a sponsor inquiry page, give it a nav-weight 

Do the right thing!

**Comment by illus0r** [comment]
We can make a separate page with *formspree.io* web form. Like on http://www.praqma.com/1hour/

What do you think, @timea?

**Comment by lakruzz** [comment]
_anything_ that is not hardcoded!

So first: _"yes"_ we need a separate page instead of a hardcode menu item.

Secondly - "Yes" a form would be a nice approach. - We can copy the concept from design from http://www.praqma.com/1hour/ but we need to put it into the design and artwork of this context - @jonnycoull  may have a say on that.

**Comment by illus0r** [comment]
I've made a separate page with __formspree.io__ form on it. It has a spam protection. I've unpublished this page so

- [ ] @lakruzz could verify it (especially my copywork)
- [ ] Remove `published: false` form `pages/sponsor.md`
- [ ] Remove line 17 from `_includes/header.html`
- [ ] Send the first letter and verify it

**Comment by illus0r** [comment]
@adamhenriques 
There should be a letter from **formspree** on your mail. You should verify to make this form work http://www.code-conf.com/sponsor/

**Comment by illus0r** [comment]
@adamhenriques 
I've sent you a test email to be 100% sure form works well.
`Hey there, Adam!` should come from zor667@gmail.com.
Please, let me know when you get it :)

**Comment by adamhenriques** [comment]
I did thanks!

[image: ____________________________________________________________]
Adam Henriques
CMO
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>

<http://www.code-conf.com/code-cph-2016/>

**Comment by illus0r** [comment]
Great, thanks, @adamhenriques! I'm closing this one
