### ISSUE TITLE
Posts is the default for pages

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#174]
In `_layouts/page.html` we're using the `post` class as default - shouldn't it be named `page`

```
<article class="post">

  <header class="post-header">
    <h1 class="post-title">{{ page.title }}</h1>
  </header>

  <div class="post-content">
    {{ content }}
  </div>

</article>
```

**Comment by illus0r** [comment]
Yep, that's my error, need to be fixed

**Comment by lakruzz** [comment]
@illus0r 
This issue needs to be made ready to work on - It currently needs and estimate.

I've assigned the case to you, please just do the following:

- Provide a realistic estimate
- Remove the "Action: Needs grooming" label
- Unassign yourself from the issue (just leave the issue unassigned)

**Comment by illus0r** [comment]
@lakruzz ready. But why do we need unassigning?

**Comment by lakruzz** [comment]
... Since it may not be you implementing it :-)

**Comment by lakruzz** [comment]
Hi @timea can you take this one

Payback on some technical debt :-)

**Comment by timea** [comment]
@lakruzz Aye, aye Sir 👍
