### ISSUE TITLE
Add description to each event

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#188]
Each event needs a short twitter-size (140 chars) description 
see an example in #153

It needs to go to a new attribute in the front matter:

```
caption: >
  A twitter sized caption, that briefly describes the conference, the purpose and the audience
```

**Comment by lakruzz** [comment]
- [ ] academy2016.md
- [ ] academy2016.md/aar.md
- [ ] academy2016.md/cph.md	
- [ ] academy2016.md/osl.md	 
- [ ] academy2016.md/trd.md
- [ ] code-cph-2016.md
- [ ] code-sthlm-2016.md
- [ ] doc-cph-2016.md
- [ ] doc-sthlm-2016.md

**Comment by illus0r** [comment]
Really awaiting for that to merge `154-Frontpage-style-main-event` into `gh-pages`

**Comment by monaslarsen** [comment]
Who is ticking off the boxes? @lakruzz @ivan @timea..? 
I'm working on it right now, but I can see the boxes ticking off faster than I can work..?!

**Comment by monaslarsen** [comment]
Ah, I see @lakruzz changed the assignment - so I should not work on it?
