### ISSUE TITLE
Some TODO not taken care of

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#193]
Found this in `_customer_details/biolin/report-parts/front.md`

![image](https://cloud.githubusercontent.com/assets/155492/15555718/41d29630-22ca-11e6-880e-a3a8a1f15f39.png)

No todo's can be left in files!

**Comment by illus0r** [comment]
@lakruzz got it. I've cleaned out TODOs from code-conf.
But `_customer_details/biolin/report-parts/front.md` is from `code-maturity`, isn't it?

**Comment by illus0r** [comment]
Now TODOs exists is in `/press/` folder only. @lakruzz, is this task still usefull?
