### ISSUE TITLE
Something is not right with the weights

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#202]
The Up next is not showing ...up next:

![image](https://cloud.githubusercontent.com/assets/155492/15612002/41a9c0e8-242d-11e6-8ef6-0e104771b8f4.png)

After Trondheim comes 
CoDe Academy CPH
CoDe Academy Aarhus
DOC STHLM
DOC CPH
...

**Comment by lakruzz** [comment]
The order of the result does not reflect the weights:

![image](https://cloud.githubusercontent.com/assets/155492/15612261/4c23ef2a-242e-11e6-804d-ec66dad25595.png)


doc sthl = 3
code sthlm = 3
code academy trd = 10
code cph = 2

**Comment by lakruzz** [comment]
Please verify the following before committing:

Up Next:
- [ ] The events appear in actual chronological order

Conferences
- [ ] "Lighter" events ≈ 1 floats to the top heavier events ≈ 10 sinks to the bottom
- [ ] Even events with no date (e.g. academy2016 ) will be shown if given `weight:1`
- [ ] No past events will ever be shown - regardless of their weights

**Comment by lakruzz** [comment]
@illus0r Id like you to work on this issue as you next!

**Comment by lakruzz** [comment]
Please implement the following featured order:

code academy 2016 `weight:10`
code academy CPH `weight:11`
DOC STHLM `weight: 20`
CODE CPH `weight:30`


The rest should not have any weights

**Comment by lakruzz** [comment]
Please implement the following featured order:

code academy 2016 `weight:10`
code academy CPH `weight:11`
DOC STHLM `weight: 20`
CODE CPH `weight:30`


The rest should not have any weights

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/15651346/2cb3610e-267f-11e6-93cf-301573f5629d.png)

**Comment by lakruzz** [comment]
Please deliver the solution you have, so we can get the right events on the front page.

If you need to make a special case for events with no start date, then take that to a separate issue and close this one.

**Comment by illus0r** [comment]
@lakruzz done! I'll describe the algorithm in readme file.
