### ISSUE TITLE
Sponsor shout-out for CoDe Academy needs a proof read

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#203]
[According to](https://praqma.slack.com/archives/code-academy/p1464333484000010) @RandomSort our [sponsor shoutout](http://www.code-conf.com/press/academy2016/code-academy-2016-sponsor.pdf) is embarrassing.

**Comment by RandomSort** [comment]
This was what I found. I don't know if @monaslarsen should go over it as well :)
"Academey" -> "Academy" (Three places?)
"Conferances" -> "Conferences"
"Achive" -> "Achieve"

**Comment by monaslarsen** [comment]
Uploading the proofed version to code-conf.com /press/
