### ISSUE TITLE
Speaker page

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#207]
Do we want to have all speakers on the same page - and not on event specific pages? http://www.code-conf.com/speakers/

Either way - we should make clear what conference/event the speakers will be presenting at.

**Comment by lakruzz** [comment]
@adamhenriques 
Have a  look at #171 I believe that's what you are asking for.

> Either way - we should make clear what conference/event the speakers will be presenting at.

Should be covered in #166.

...If you ( @adamhenriques  ) agree - then mark this case a duplicate and close it - If you want it to still be open, then you'll have to elaborate how this is different.
