### ISSUE TITLE
All events listing

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#220]
Hammered out from #161 

Create a single page with all events -make it accept filters

- [ ] Event type (e.g. Hackaton, Conference, Meetup)

![subpage_v2](https://cloud.githubusercontent.com/assets/17589853/15580437/a915682c-2360-11e6-9a6c-1049d1a9177a.jpg)

**Comment by illus0r** [comment]
@lakruzz we can seriously reduce time on development is we'll reuse existing event modules on this page

![image](https://cloud.githubusercontent.com/assets/797993/15710390/844ae43e-2812-11e6-8e34-e14da35add65.png)

**Comment by lakruzz** [comment]
Yep - Let's do that to begin with - well spotted.

**Comment by illus0r** [comment]
- [ ] implement `detach()` to make event height flexible
