### ISSUE TITLE
Make a link to *All events* list from the frontpage

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#221]
Subtask of #161
![image](https://cloud.githubusercontent.com/assets/797993/15248256/e63badd6-1921-11e6-84cc-a75243d335cd.png)

**Comment by illus0r** [comment]
Not critical now, still we have the menu 
![image](https://cloud.githubusercontent.com/assets/797993/15776564/2ad904be-2991-11e6-9577-38b1c51893e2.png)

but good to have

**Comment by lakruzz** [comment]
Not relevant since the all events is already in the menu, and then up next is now scrollable
