### ISSUE TITLE
Main page sell copy

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#223]
@adamhenriques we spoke about this a while ago I need a new line for under continuous delivery, at the moment the list of items could be mistaken for another menu. 

Can you give its a once over please? 
![screen shot 2016-06-01 at 13 50 32](https://cloud.githubusercontent.com/assets/17589853/15710272/31c5dfa4-2801-11e6-9ded-e46264fe1e40.png)

**Comment by lakruzz** [comment]
How about:


__...We're building the community of CoDe'ers and DevOps__

**Comment by jonnycoull** [comment]
@lakruzz if your happy with that can @illus0r pop it in?

**Comment by illus0r** [comment]
@lakruzz @jonnycoull yep, I can :)

**Comment by lakruzz** [comment]
go ahead
