### ISSUE TITLE
Subpage for sponsor profile description

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#226]
Can we get a subpage for the sponsors descriptions - just like we have with speakers. So clicking on the sponsor logo - each sponsor will have a subpage with elaborate company profile. 

Example: http://archive.code-conf.com/osl15/sponsors/ca.html

**Comment by lakruzz** [comment]
@adamhenriques 

This case is assigned to you for more information.

Please elaborate on what it's about - it's unclear. Consider using examples or even better screen dumps that unambiguously describes what this case is about.

When you are done, please unassign yourself from the case

**Comment by adamhenriques** [comment]
@timea is I understood @monaslarsen and @illus0r are already on this case

**Comment by timea** [comment]
Hi @adamhenriques and @monaslarsen ! We had a meeting with @lakruzz when we talked about this issue. He has asked you for more info, as he is not sold as product owner that this task is actually needed. Please provide further info about the return on investment  on the case, just as he asked for it :). 

Also for future reference, prioritizing is belonging per principle to @lakruzz(as he is the product owner), in his absence, me. When you would like to push an issue, it needs to be estimated and prioritized always before we work on it. So the way to go is to provide as much info as you can when you create the issue, so we can save time on the back and forth. 

When you create an issue, and it is not assigned to a milestone, it goes in a pool we are looking at regularly. If you feel the issue needs attention, just comment with an @username and we will get back to you asap.

Please let me know if you have any questions. 

Cheers

**Comment by monaslarsen** [comment]
My five cents: Return of investment is first and foremost that the sponsors are promised a 75 word bio when buying a sponsorship - and it has worked, because the sponsors have signed up and sent us their bios, because it is important to them.

**Comment by timea** [comment]
@adamhenriques @monaslarsen @illus0r 

As a summary:

The estimates are done by developers, as we are estimating developer effort.
The prioritization is done by the product owner as we are all serving his needs.
We all are creating issues that are potentially important and need to be checked out by the product owner.

**Comment by timea** [comment]
We have been working on this new flow, and I realize now you were not briefed @adamhenriques and @monaslarsen . Sorry about that. We are working on getting better in the workflows and company communication, knowledge sharing in general.
|

**Comment by adamhenriques** [comment]
@timea the description has been updated and i have removed the label for grooming.

**Comment by illus0r** [comment]
@adamhenriques 
What informations will be stored on that page?
Will this information change from one conference to another?

**Comment by adamhenriques** [comment]
@illus0r information will be Company logo and a brief description as shown in example: http://archive.code-conf.com/osl15/sponsors/ca.html

As these are for the specific conference sponsors - the subpages will be conference specific.

**Comment by illus0r** [comment]
@adamhenriques so every sponsor logo will lead to a separate page. User will see different info on the **Github** page if he get there from different conference pages. That's possible, but you'll have to create 38 separate pages for different sponsor's descriptions. I.e. **Github** will have 9 different pages for different events. Is that what we really need? What information will differ from one **Github** sponsor page to another?

**Comment by adamhenriques** [comment]
@illus0r We can easily reuse the sponsor "profiles" across events. So that each sponsor only have 1landing page no matter what entry the user comes from.

**Comment by illus0r** [comment]
@adamhenriques that's much easier! So every sponsor will have a page. Logos on events pages will lead to these event-independent sponsor pages. Correct? If so, can you add sponsors' descriptions to their md files?

![image](https://cloud.githubusercontent.com/assets/797993/16985905/3ffc5132-4e8c-11e6-8b6f-ba265e1f082e.png)


 On sponsors' pages I can implement this part fast

![image](https://cloud.githubusercontent.com/assets/797993/16985016/6fb2df96-4e86-11e6-9df7-87fa493f0104.png)

If we need to implement the right bar, we need some designs from jonnycoull

![image](https://cloud.githubusercontent.com/assets/797993/16985030/85e4f236-4e86-11e6-8671-973d36d38bdf.png)

**Comment by adamhenriques** [comment]
@illus0r great. All we need is something like;

![screen shot 2016-07-20 at 14 14 41](https://cloud.githubusercontent.com/assets/8004259/16985993/7b24add4-4e84-11e6-970f-1051d979ce16.png)
 no

Can I just add company descriptions as we go?

**Comment by illus0r** [comment]
@adamhenriques Yep, sure! Just add it to sponsor's `md` files

**Comment by adamhenriques** [comment]
@illus0r great tanks!

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/16986882/b8923b48-4e91-11e6-8328-4b0331ec3bdd.png)

**Comment by illus0r** [comment]
@adamhenriques implemented my part. Now it'll hang until texts are ready. Please, ping me, when you're done

**Comment by illus0r** [comment]
This task is small for me, not for Adam :) And, probably we need a separate task for copywork. What do you think, @timea?

**Comment by adamhenriques** [comment]
@illus0r if I click on the logos i still hit the url - will you implement the subpages then ill add the descriptions?

**Comment by timea** [comment]
Yes, a separate task is a good idea @illus0r

**Comment by illus0r** [comment]
@timea @adamhenriques made https://github.com/Praqma/code-conf.com/issues/332 task for that.

@adamhenriques I've brought proper urls to life :)

**Comment by adamhenriques** [comment]
@illus0r great, thanks!
