### ISSUE TITLE
Eventbrite widget gets cut off - needs fixing

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#227]
The eventbrite ticket widget gets cut off in the buttom on (http://www.code-conf.com/code-cph-2016/)

![screen shot 2016-06-02 at 14 22 17](https://cloud.githubusercontent.com/assets/8004259/15744668/a19af4dc-28cd-11e6-922a-3adf5511abf1.png)

**Comment by lakruzz** [comment]
@adamhenriques in reference to #25 

...The solution is to adjust the height - trial'n'error until it fits using the `hight` property:

```
{% include eventbrite-ticket-form.html
eventbriteid=page.checkout.eventbriteid
css_classes="black toprip botrip"
header="Enroll"
height="310"%}
```
