### ISSUE TITLE
Add full speakers list

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#239]
Now speakers are listed by conferences and there is no common speaker's list.
It'll require a menu link as well

@timea please, set a priority and proper milestone for that task

**Comment by lakruzz** [comment]
@illus0r @timea  I'm still the one doing the prioritization :-)

But I'm not sure what this is about @illus0r 

http://www.code-conf.com/speakers/

Is a full speakers list isn't it?

How do they get listed by conference?

Please elaborate - I don't know what I'm prioritizing here

**Comment by lakruzz** [comment]
@illus0r 
This case is assigned to you for more information.

Please elaborate on what it's about - it's unclear. Consider using examples or even better screen dumps that unambiguously describes what this case is about.

When you are done, please unassign yourself from the case

**Comment by timea** [comment]
@lakruzz, yes, understood.


[image: ____________________________________________________________]
Timea Kiss
Continuous Delivery Sorceress
tk@praqma.com
+45 25 66 83 44 <+45%2025%2066%2083%2044>
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/academy2016/?src=mailbanner>

**Comment by illus0r** [comment]
@lakruzz 
>Is a full speakers list isn't it?

Yep! But it's not accessible from any page of the site. So now the page is empty: I didn't waste time to fill unaccessible page.

![image](https://cloud.githubusercontent.com/assets/797993/15824403/b086f0da-2c07-11e6-8b03-896ae735635c.png)

If we need this page (i guess we need), we want to add it's link to the menu and fix the filter so this page was full by default.

**Comment by lakruzz** [comment]
OOh - it wasn't empty when I wrote my comment

**Comment by illus0r** [comment]
@timea what kind of grooming do we need now?

**Comment by monaslarsen** [comment]
Hey @illus0r, I'm on a road trip with Timea and Lars, Lars asks you to work on the newest issue in Praqma.com, the table styling one

**Comment by illus0r** [comment]
Good morning, Mona! Yep, I've started with [306](https://github.com/Praqma/praqma.com/issues/306)

**Comment by illus0r** [comment]
Just wanted to get rid of `grooming` label :D

**Comment by lakruzz** [comment]
http://www.code-conf.com/speakers/ 

- [ ] should show all speakers listed alphabetically.
- [ ] but only if they speak at conference that's not ended yet

@illus0r please set the estimate accordingly

**Comment by illus0r** [comment]
So we'll show only speakers of upcoming events?

**Comment by lakruzz** [comment]
yes

**Comment by illus0r** [comment]
good, so medium

**Comment by jonnycoull** [comment]
![screen shot 2016-08-16 at 16 27 35](https://cloud.githubusercontent.com/assets/17589853/17704937/81099c00-63ce-11e6-8ed6-16d48bbdc16d.png)
remove the SPEAKING AT ( its not needed) then this is done?

**Comment by illus0r** [comment]
To check the result out click `speakers` in the menu

![image](https://cloud.githubusercontent.com/assets/797993/18318376/23a3acc8-752a-11e6-90ab-275a37e1bbf4.png)

**Comment by illus0r** [comment]
http://www.code-conf.com/speakers-all/
