### ISSUE TITLE
Scroll to clicked speaker on speakers' list

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#240]
When I click speker's name on conf's page, I go to this conference's speaker list. 
And I have to scroll to find a speaker I've clicked.

![image](https://cloud.githubusercontent.com/assets/797993/15817779/58d0e3ac-2be2-11e6-9b96-9283085dce25.png)

@timea please, set a priority and proper milestone for that task

**Comment by timea** [comment]
This change is not committed yet. I cannot see the behaviour. Are the
speakers ordered by first name after clicking on the conference's page the
speaker's name? We will create a new milestone together with Lars on
Wednesdays, then we can assign.

**Comment by illus0r** [comment]
@timea I've just pushed
Speakers are ordered by name on speakers page. They are sorted via frontmatter on event pages

ok, I'll set current milestone so as not to loose the issue

**Comment by lakruzz** [comment]
Something like this:

http://www.code-conf.com/speakers/#code-cph-2016?speaker=edtompson

**Comment by illus0r** [comment]
Now that  works like http://localhost:3002/speakers/?tag=doc-sthlm-2016#mhausenblas

**Comment by lakruzz** [comment]
NO!

**Comment by lakruzz** [comment]
The anchor goes before the parameter

**Comment by lakruzz** [comment]
BUT it would be the same as having both as parameters:

Now that works like http://localhost:3002/speakers/?event=doc-sthlm-2016&speaker=mhausenblas

**Comment by lakruzz** [comment]
Have a look at https://github.com/Praqma/code-conf.com/blob/gh-pages/javascripts/praqmajsutils.js

**Comment by lakruzz** [comment]
Used like this:

https://github.com/Praqma/praqma.github.io/blob/master/mailsignature/create.html

**Comment by lakruzz** [comment]
```
<script type="text/javascript">
 var user=getParam ("user");
 var banner=getParam("banner");
.....
```
