### ISSUE TITLE
Improve title on speaker's page

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#241]
![image](https://cloud.githubusercontent.com/assets/797993/15817864/c6ee7142-2be2-11e6-9b4b-eb2b8a040d47.png)

Title should look like 

![image](https://cloud.githubusercontent.com/assets/797993/15816400/4ebb6628-2bdb-11e6-91d3-559c2c2935e1.png)

Timea said
> I think we should keep the megaphone as it is about the speakers
and lose the switch icon at the end

   - [x] proper color for title
   - [x] proper text (title, not basename)
   - [x] proper `OC` color
   - [ ] Make avatars clickable on conf pages

@timea please, set a priority and proper milestone for that task

**Comment by jonnycoull** [comment]
@illus0r @timea CODE-CONF orange is fine for this.

**Comment by illus0r** [comment]
- [ ] Make avatars clickable on conf pages
