### ISSUE TITLE
On speaker's pages fix links to conferences

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#242]
There's a bug on nested events like `/academy2016/aar/`
they are linked to `/aar/`

@timea please, set a priority and proper milestone for that task

**Comment by timea** [comment]
Hey @illus0r , the code academies do not have speakers. This means no speaker will have the code academies in their list. I could not reproduce this.

**Comment by illus0r** [comment]
@timea Yep, i know.
However, if some subevent will have a speaker this bug will pop out.

**Comment by timea** [comment]
@illus0r okay, then I put this on the backlog and we keep an eye on it.

**Comment by timea** [comment]
@lakruzz  as this is a future problem I suggest giving it a new prioritization

**Comment by lakruzz** [comment]
what's the problem, why is the URL not set correctly. it the estimate still valid?

**Comment by illus0r** [comment]
> why is the URL not set correctly

I've decided to deliver faster, this thing seamed not critical to me.

> estimate still valid?

yes
