### ISSUE TITLE
There's not such things as "Hackatones"

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#245]
The right word  is "Hackatons"

![image](https://cloud.githubusercontent.com/assets/155492/15887429/85ed8e40-2d62-11e6-991a-2483d7151cb3.png)

**Comment by jonnycoull** [comment]
@lakruzz @illus0r sorry my bad I checked that a while back. 
![screen shot 2016-06-08 at 17 27 23](https://cloud.githubusercontent.com/assets/17589853/15902204/b06ba6c0-2d9e-11e6-9258-d71954682a60.png)

**Comment by timea** [comment]
@jonnycoull @lakruzz @illus0r  that is alright, it is correct now - as all other items (all event, conferences, meetups) I kept it in plural.
