### ISSUE TITLE
Make images open in new tab

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/code-conf.com#248]
On
http://www.code-conf.com/press/academy2016/

clickable links and images should open in new tab

**Comment by timea** [comment]
@lakruzz  is this something you want implemented?

**Comment by timea** [comment]
@lakruzz do you want this done?

**Comment by lakruzz** [comment]
No thanks

Normally the convention is that if a page is within the same domain it opens in the same window - and if it's outside then it opens in a new window.

All links on http://www.code-conf.com/press/academy2016/ are internal.
