### ISSUE TITLE
Meet-up: summary

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#249]
Subtask of #75

![image](https://cloud.githubusercontent.com/assets/797993/15927302/75b577ee-2e49-11e6-80fa-5c0980596d23.png)

- [x] short description
- [x] date-location
- [x] [image]

**Comment by illus0r** [comment]
Hello, @jonnycoull!
Can you upload the picture for that?

**Comment by jonnycoull** [comment]
Hi @illus0r all done in images, hopefully. let me know if not.
