### ISSUE TITLE
Meet-up: agenda

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#250]
Subtask of #75
Scale down to just `md` text

![image](https://cloud.githubusercontent.com/assets/797993/15927372/019c69d4-2e4a-11e6-92ec-6acaba4c5780.png)

**Comment by illus0r** [comment]
Hi, @jonnycoull!
Could you share the image?

**Comment by jonnycoull** [comment]
Hi @illus0r all done in images, hopefully. let me know if not.

**Comment by illus0r** [comment]
- [ ] make include for header
- [ ] style it

**Comment by timea** [comment]
@lakruzz This issue does not have a priority, but @illus0r asked me to help on this one. 
@illus0r can we do that, when you break down a briefing task to assign Lars so he gives a priority to each of them?

**Comment by lakruzz** [comment]
All right but it doesn't really make sense _not_ to have this, so it's part of what defines the success of the milestone.

**Comment by illus0r** [comment]
@lakruzz 
I wanted to remove pover icon from events, that are not brands.
![image](https://cloud.githubusercontent.com/assets/797993/16076126/7f316566-32fa-11e6-8fab-ffd2a3e15bb4.png)
We need it on **CoDe STKHLM** and don't need here. Should I create a task to remove it? That's liquid deal, not content update.
![image](https://cloud.githubusercontent.com/assets/797993/16076194/ce4c4f58-32fa-11e6-8bc3-473b6fe57ac4.png) ![image](https://cloud.githubusercontent.com/assets/797993/16076178/b5b834a2-32fa-11e6-8cd6-5489ac1b76af.png)
