### ISSUE TITLE
Meet-up: header

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#251]
Subtask of #75

Reuse existing module without any modifications.

![image](https://cloud.githubusercontent.com/assets/797993/15927446/754407de-2e4a-11e6-93e3-13bf95f682dd.png)

**Comment by illus0r** [comment]
Hi, @jonnycoull!
Can you upload the image for this page?

**Comment by jonnycoull** [comment]
Hi @illus0r all done in images, hopefully. let me know if not.

**Comment by illus0r** [comment]
@timea 
made something **very** minimal. I've pushed to `251-Meet-up-header` branch, please have a look, if I can publish it.

Anyway I'll improve it somehow tomorrow.

![image](https://cloud.githubusercontent.com/assets/797993/15932224/84ac8d2c-2e63-11e6-9fab-9f56d12d937e.png)

**Comment by timea** [comment]
@illus0r  I very much like it! Publish it!

**Comment by illus0r** [comment]
I'll update pictures
