### ISSUE TITLE
Meet-up: workshops

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#253]
Subtask of #75

Try to reuse `pullout`+`3columns`. If no way — just `3columns`

![image](https://cloud.githubusercontent.com/assets/797993/15927740/0749a674-2e4c-11e6-8ede-d235d8323ac2.png)

**Comment by illus0r** [comment]
Hey, @jonnycoull!
Can you upload these 3 images for the page?

**Comment by jonnycoull** [comment]
@illus0r yeah man I can do that now. SQUARE images for these right? any specific pixel size? Also @lakruzz I got a few of these from GITHUBS website, but if there a sponsor I thought they might like that? maybe best to run it by them first?

**Comment by illus0r** [comment]
@jonnycoull yep, squares! 280x280 will do.

**Comment by illus0r** [comment]
@jonnycoull ahh, you've already uploaded! Great, size seams to be is good

**Comment by jonnycoull** [comment]
@illus0r cool, let me know if you need anything else.

**Comment by lakruzz** [comment]
@jonnycoull the beer glass is fine, but the octocat (used for the workshop in the middle) is for a workshop run in collaboration with GiHub and Praqma, An orange octocat? Maybe just an orange backgound, or an Octocat wearing a Praqma Cap? ...don't know.

**Comment by jonnycoull** [comment]
Could put a PRAQMA logo next to the cat, they have s set of rules... @lakruzz thats why I asked if it would be ok on the original issue to use their pics originally , if you have a marketing contact I can speak to them if you want. if you haven't done so yet?
![screen shot 2016-06-13 at 11 43 12](https://cloud.githubusercontent.com/assets/17589853/16005027/f2097492-315c-11e6-9c2b-ab2ea6ebb1d5.png)

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/16005336/05459e3c-3167-11e6-96c0-f943ec78e30e.png)


We have a different GitHub organisation where we're collaborating with the GitHubbers: http://github.com/githubpartners/praqma - I've created a case there, where I* asking them to add your GitHub handle so you can access - then we can chat with them directly

**Comment by jonnycoull** [comment]
Great thanks, I've made image with the two icons, joined with some flow artwork to replace just the cat for now, and ill see how I get on with the above? @lakruzz 
![gitmeetsquare2](https://cloud.githubusercontent.com/assets/17589853/16005538/bd4b6a28-315f-11e6-85ff-dff05c441203.jpg)

**Comment by lakruzz** [comment]
I'm closing this one, it seems that it's implemented
