### ISSUE TITLE
Meet-up: make look good on the All events list

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#254]
Subtask of #75

- [ ] remove power icon
- [ ] make text smaller

![image](https://cloud.githubusercontent.com/assets/797993/15929105/919a2130-2e53-11e6-8780-c609cc8096ba.png)

**Comment by jonnycoull** [comment]
Hi @illus0r you know that chart and mock up I sent recently on SLACK, it might help with instances like this. So each piece of copy has in bold a sort of lesser sub head (which is bold copy) . So It could be a case that its GITHUB MEET-UP then in the lesser sub head, NEXT GENERATION SOFTWARE DEVELOPMENT. as it looks a bit clunky that size? as an option ? @lakruzz attached again for ref.

[CODECONF_JC_HOME_V5.pdf](https://github.com/Praqma/code-conf.com/files/306938/CODECONF_JC_HOME_V5.pdf)

**Comment by illus0r** [comment]
@jonnycoull thanks for your input

In fact this blue strip 
![image](https://cloud.githubusercontent.com/assets/797993/15960519/debc4708-2f08-11e6-8631-0b31d39eb989.png)
Should have the same content as this blue strip
![image](https://cloud.githubusercontent.com/assets/797993/15960546/041e71e2-2f09-11e6-8f4a-61b6a2304fef.png)

Otherwise will have to invent some extra rules of naming. But we can! If so, we need one more task instead of this one.

**Comment by illus0r** [comment]
@monaslarsen 
Hi, Mona! Can you help me with copy on that page?

![image](https://cloud.githubusercontent.com/assets/797993/15965492/dada65d4-2f26-11e6-92b1-e1887a5a3933.png)


I mean bottom text. It goes from `_events/next-generation....md`, from this code
```
caption: >
  GitHub and Praqma have entered into partnership in Scandinavia - we believe it’s a perfect
  match, come and hear why! We’re jointly inviting you to a breakfast-to-lunch seminar of
  three short workshops that will give you insight on how businesses are transforming by
  building methodologies and practices that will drive software development into the future.
```
Now it's huge and needs some contraction or complete rewriting

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/16008655/54a87398-3179-11e6-90d1-ca86c390ae2f.png)

**Comment by lakruzz** [comment]
A caption can not span more than one line ...Doooh!

**Comment by lakruzz** [comment]
E.g. __Nxt-Gen VIP meetup__

**Comment by illus0r** [comment]
@lakruzz 
I wanted to remove pover icon from events, that are not brands.
![image](https://cloud.githubusercontent.com/assets/797993/16076126/7f316566-32fa-11e6-8fab-ffd2a3e15bb4.png)
We need it on **CoDe STKHLM** and don't need here. Should I create a task to remove it? That's liquid deal, not content update.
![image](https://cloud.githubusercontent.com/assets/797993/16076194/ce4c4f58-32fa-11e6-8bc3-473b6fe57ac4.png) ![image](https://cloud.githubusercontent.com/assets/797993/16076178/b5b834a2-32fa-11e6-8cd6-5489ac1b76af.png)

**Comment by lakruzz** [comment]
@illus0r 
Yes - please take it to a different issue - we'll close this one with reference to the fact that the text needed to be fixed - not the implementation
