### ISSUE TITLE
Style fonts on meetup pages

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#256]
![image](https://cloud.githubusercontent.com/assets/155492/16006424/593ef794-316d-11e6-922d-36574bf42d48.png)

Why are we using bold font for body text - it's different from what's suggested in #75 

![image](https://cloud.githubusercontent.com/assets/155492/16006499/c3900f3e-316d-11e6-92b6-d8569aa19f2c.png)

- let's clean up the SASS...

**Comment by lakruzz** [comment]
Appears to be only a problem on Lars PC, but in all three browsers: Safari, Chrome and Firefox

**Comment by illus0r** [comment]
@lakruzz 
Can't reproduce it. I've tried automated crossbrowser testing, here are results:

https://www.browserstack.com/screenshots/7cc96c0268b6dd56f1113a92e3a24b2ebea7bf09
http://browsershots.org/http://www.code-conf.com/im-a-github-man/

None of browsers have this problem. I've [asked on Slack](https://praqmacollaborator.slack.com/archives/random/p1465993952000002) as well.

How these news can change the priority?
