### ISSUE TITLE
refactor event-main.html

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#257]
```
{% include event-main.html
background-image=page.event_header.img
brand-txt=page.brand-txt
brand-txt-size=4.0
subtitle=page.subtitle
dot-text=page.dot-txt
dot-txt-size=page.dot-txt-size
brand-lead=page.event_header.ribbon
color=page.color %}
```

Rename some something more generic (e.g. `decorated-picture`)

add features to make it support the intended use (agenda) in meetup pages 

Assert it goes good - otherwise produce an error output - (don't fail silently)

**Comment by illus0r** [comment]
@lakruzz 
>add features to make it support the intended use (agenda) in meetup pages

We don't need new features for meet-ups, do we?

**Comment by illus0r** [comment]
Or what features do we need?

**Comment by illus0r** [comment]
Closed in https://github.com/Praqma/code-conf.com/commit/7fbe98364a0bd99b75c10cfbee9f37bde689dfa8

The mess with delivering to `delivered/gh-pages` is because of making `git purge-all-delivered` after `git workon 257`

**Comment by illus0r** [comment]
I assign it to you, @lakruzz because I don't know answer [to this comment](https://github.com/Praqma/code-conf.com/issues/257#issuecomment-241405315). And I guess @jonnycoull doesn't know as well
