### ISSUE TITLE
Add the "Work smarter with GitHub" meetup

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#259]
Add meetup:

http://www.meetup.com/code-u/events/230840654/

**Comment by lakruzz** [comment]
Use the meetup on Wednesday to produce another entry

**Comment by lakruzz** [comment]
The issue would normally go to the "content update" milestone, which is maintained by Mona, But since the Meetup format is still being worked on by @timea and @illus0r it could be a collaboration btw @timea  and @monaslarsen 

The thing is, we want volume and diversity, to see that the format we create fits the diversity of how we actually use it.

#263 #262 #264

**Comment by illus0r** [comment]
Need help with copy

![image](https://cloud.githubusercontent.com/assets/797993/16084144/51b1f742-3320-11e6-9114-5c4b40143a90.png)
