### ISSUE TITLE
Pictures for docker-meetup

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#268]
http://www.code-conf.com/docker-meetup/
This event needs its own identity with its pictures. @jonnycoull is already at it

**Comment by timea** [comment]
@lakruzz Prio 2 is assumed, as the original task it belongs to #262 had prio 2.

**Comment by timea** [comment]
@lakruzz What do we do in this case? A new case is born from an already existing one. When you are not available and we still want to keep the milestone, we just roll on - @jonnycoull is already working on the task, without your approval. Kind of off, but aiming for finishing.

**Comment by jonnycoull** [comment]
@timea that link is dead I need to see the meet up to make the pics?

**Comment by timea** [comment]
@jonnycoull yes, sorry, Lars is presenting the site, so he unpublished them.

Here are some screenshots from my local.

![image](https://cloud.githubusercontent.com/assets/4135651/16088590/1fc06086-3328-11e6-8d3b-37207f344426.png)

![image](https://cloud.githubusercontent.com/assets/4135651/16088598/303fbfba-3328-11e6-8088-17fd91bfa0b7.png)

**Comment by timea** [comment]
@jonnycoull  the meetup page is http://www.meetup.com/Docker-Aarhus/events/231441979/

**Comment by jonnycoull** [comment]
![screen shot 2016-06-15 at 20 02 02](https://cloud.githubusercontent.com/assets/17589853/16093502/0efca348-3334-11e6-8b2b-4c720b07dbaf.png)
hi @timea @illus0r here's docker! images uploading.

**Comment by lakruzz** [comment]
@timea yes feel free to make conscious decisions about priority when I'm not available:

I'm the benevolent dictator - you are the trusted lieutenant  - and @jonnycoull is a one-man-army :-)

Getting things done is good.

**Comment by jonnycoull** [comment]
aye! lets do this.  @lakruzz @illus0r @timea all images now in. beware, I'm creating new issues. who knows what will happen!

**Comment by timea** [comment]
@jonnycoull haha, great! We will take a look at them today!

@lakruzz well then, I assume for now to make all pic stuff prio 1 and we
will be done by the meeting.

On Wed, Jun 15, 2016 at 9:14 PM, jonnycoull <notifications@github.com>
wrote:

> aye! lets do this. @lakruzz <https://github.com/lakruzz> @illus0r
> <https://github.com/illus0r> @timea <https://github.com/timea> all images
> now in. beware, I'm creating new issues. who knows what will happen!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Praqma/code-conf.com/issues/268#issuecomment-226290473>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD8a47qll2lc0i6uv4Bg_csBYT6lY0c0ks5qME8OgaJpZM4I2gsi>
> .
>



-- 

[image: ____________________________________________________________]
Timea Kiss
Continuous Delivery Sorceress
tk@praqma.com
+45 25 66 83 44 <+45%2025%2066%2083%2044>
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/academy2016/?src=mailbanner>
