### ISSUE TITLE
Pictures for working with GitHub meetup

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#270]
http://www.code-conf.com/working-with-github/

@lakruzz What do we do in this case? A new case is born from an already existing one. When you are not available and we still want to keep the milestone, we just roll on - @jonnycoull is already working on the task, without your approval. Kind of off, but aiming for finishing.

**Comment by jonnycoull** [comment]
![screen shot 2016-06-15 at 17 48 20](https://cloud.githubusercontent.com/assets/17589853/16089656/0ea042d4-3324-11e6-90f1-eeadbc81d117.png)
![screen shot 2016-06-15 at 18 06 59](https://cloud.githubusercontent.com/assets/17589853/16089655/0e4991f0-3324-11e6-839f-f93253337ebe.png) mock up for colour and page items

**Comment by jonnycoull** [comment]
images uploading to, images. @timea @illus0r #270
