### ISSUE TITLE
Pictures for Automation Night

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#272]
In reference to #263 

@jonnycoull 
THe exisiting meetup page is http://www.meetup.com/CoDe-U-AROS/events/230864013/
here is how it looks locally

![image](https://cloud.githubusercontent.com/assets/4135651/16088799/016b7dcc-3329-11e6-80b2-f0ed0875a5b5.png)

![image](https://cloud.githubusercontent.com/assets/4135651/16088805/0913987a-3329-11e6-8f90-9b057191f350.png)

**Comment by jonnycoull** [comment]
![screen shot 2016-06-15 at 18 57 25](https://cloud.githubusercontent.com/assets/17589853/16091322/084acd62-332b-11e6-82b5-f93fc32a38ad.png)
Mock up. images in @illus0r @timea
