### ISSUE TITLE
Pictures for Dev Ops Day Oslo

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#273]
In reference to #264 

@jonnycoull 
the meetup page is http://www.meetup.com/DevOps-Norway/events/229686627/

This is how it looks locally

![image](https://cloud.githubusercontent.com/assets/4135651/16088927/71ea43e4-3329-11e6-9f7b-f04f37475db6.png)

**Comment by jonnycoull** [comment]
new mock up and colour way. @timea @illus0r 

![screen shot 2016-06-15 at 19 31 24](https://cloud.githubusercontent.com/assets/17589853/16092438/d00c9e1c-332f-11e6-80bc-a76df5647408.png)
