### ISSUE TITLE
fix the brown headline on main page

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#274]
Can we please change the colour of the brown logo to the correct colour please, @illus0r @timea 

https://slack-files.com/files-pri-safe/T0DC2A72Q-F1DCPDG1Y/codeconf_jc_home_v5.pdf?c=1466017616-7206f7f1281d8de604216518a80f91a9e3ee2603

https://slack-files.com/files-pri-safe/T0DC2A72Q-F1DCCMYVB/codeconf_colours.pdf?c=1466017595-9f3f8d9b5db69b47dae06cea37a373fe9a02b26a

for reference

**Comment by timea** [comment]
@jonnycoull hey there!

The link to the files is broken. You can always rightclick your local file, and push ctrl-V in the issue text area (where I am writing right now too) and it will upload from your memory.

Can you include the files like this?

Thanks!
