### ISSUE TITLE
Fix/tidy main nav bar

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#275]
hello again can we today up the main nav bar please to match the mock up. 

main logo. as you see then the main elements and the secondary smaller ones on the right higher plus social icons.

https://slack-files.com/files-pri-safe/T0DC2A72Q-F1DCPDG1Y/codeconf_jc_home_v5.pdf?c=1466017814-761775934faafa9a1c93aa1eb8d0c54dd88e16c3

thanks, were getting live events and @lakruzz has this site and showing it to clients, lets make it look nice.

**Comment by timea** [comment]
@jonnycoull hey there!

The link to the files is broken. You can always rightclick your local file, and push ctrl-V in the issue text area (where I am writing right now too) and it will upload from your memory.

Can you include the files like this?

Thanks!

**Comment by timea** [comment]
Do you mean it should look like this? @jonnycoull 
![image](https://cloud.githubusercontent.com/assets/4135651/16118130/e78a7c7a-33d5-11e6-9e83-882d922f58bb.png)

What happens with the 

![image](https://cloud.githubusercontent.com/assets/4135651/16118136/f7f4afae-33d5-11e6-81dc-13fa0b707d49.png)

**Comment by jonnycoull** [comment]
![screen shot 2016-06-16 at 14 59 15](https://cloud.githubusercontent.com/assets/17589853/16119342/f246e75a-33d2-11e6-942e-6b706550881d.png)
Hi @timea thanks for looking at this here's a grab of how I see it working. its a bit deeper than the original, but it allows for a hierarchy of design and menu importance. does my screenshot make sense?

**Comment by jonnycoull** [comment]
SO @timea so put your conferences, training, meet-ups where my mockup says CONFERENCES MEET-UPS HACKATHONES. and the rest go top right with the social buttons. SPONSORS, pAPERS ETC.

**Comment by timea** [comment]
@jonnycoull Thanks for the screenshot, this is different from what I found. Is this a design that was already okayed by @lakruzz?

**Comment by jonnycoull** [comment]
Yep it had the big green light a while back. @timea , words or actual menu names may have changed but the idea is there.

**Comment by meekrosoft** [comment]
So guys, what is the feedback that is awaited?  From @lakruzz ?

**Comment by illus0r** [comment]
Hmmm, may be prioritizing?

**Comment by timea** [comment]
@meekrosoft @illus0r I was not sure what was the latest approved design by Lars. Got the info since.

**Comment by jonnycoull** [comment]
@illus0r @timea can we get this actioned please? it will form part of @illus0r other query in issue #325 thanks.

**Comment by jonnycoull** [comment]
![bottom design](https://cloud.githubusercontent.com/assets/17589853/16983408/97869180-4e6c-11e6-8647-93b0dcc288c2.png)
![top bar design](https://cloud.githubusercontent.com/assets/17589853/16983407/97858fd8-4e6c-11e6-96b9-c0665d42026f.png)

**Comment by jonnycoull** [comment]
the orange bits on the bottom design are what the mouse over state is. top bar has smaller copy top right plus social icons.

**Comment by illus0r** [comment]
@lakruzz @timea do we really need Google+ link in the header? It looks like we don't update it very often ;) 
https://plus.google.com/114839349065089373679
https://plus.google.com/106972418521266551481
https://plus.google.com/100636273457335734278 — last update 13 weeks ago

**Comment by lakruzz** [comment]
@illus0r 
https://plus.google.com/100636273457335734278/videos is interesting, the two others are not.

**Comment by illus0r** [comment]
@timea OK then, I was wrong with my estimate. It's really small, but if we don't care about mobile version. Now I've implemented the new menu, but it became even more ugly un mobile

I think I'll implement some fast and very dirty styling hack and make a separate task for mobile menu styling (if it doesn't exist)

![image](https://cloud.githubusercontent.com/assets/797993/17026583/32eefee4-4f69-11e6-9c30-803c2c1421b4.png)

![image](https://cloud.githubusercontent.com/assets/797993/17026592/4010672a-4f69-11e6-862c-7b928792707f.png)

**Comment by illus0r** [comment]
Came up with this horror

![image](https://cloud.githubusercontent.com/assets/797993/17027014/dbc338e0-4f6a-11e6-90d4-7c832ef246cc.png)

The task to improve this shit is #288 :)

**Comment by jonnycoull** [comment]
my eyes. can we implement a burger menu on mobile? @illus0r

**Comment by illus0r** [comment]
@jonnycoull sure, that's for #288

**Comment by illus0r** [comment]
header's part is closed in https://github.com/Praqma/code-conf.com/commit/053823c133ab1aaa12170a37a5aace9ca3eaf320

footer is for #330
