### ISSUE TITLE
Meet-ups vs Meetups

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#277]
In the design we have Meet-Ups in both the menu and in the event pages in the type. 
When I searched online meet-ups, I only got results typed as meetups.
Though it looks really cool in the design with orange dash. 
@lakruzz  thoughts?

![image](https://cloud.githubusercontent.com/assets/4135651/16111662/cf4b2442-33b3-11e6-9616-d2b0ac047fe4.png)

**Comment by jonnycoull** [comment]
That's possibly some bad grammar on my part, what's the correct way of
wrighting it? But the short orange hyphen is a code conf style thing. But
can and should be used in sub heads to keep a theme running.

**Comment by lakruzz** [comment]
I think the correct spelling is "meet ups" - which means that technically both "meetups" and "meet-ups" are wrong.

meetup.com kinda introduce the spelling "meetup" but I guess mostly for convenience in url and twitter handle.

I think we should either stay with the current "Meetups"  or use the "Meet-ups" that @jonnycoull suggested in the mockup  - it's not something I have strong opinions about.

**Comment by jonnycoull** [comment]
Stylistically it's a nice nod to the core brand so could we use the short
orange hyphen? And then we sort of own our own brand meet-ups

**Comment by timea** [comment]
+1 on our self branded meet-ups!

On Thu, Jun 16, 2016 at 11:42 AM, jonnycoull <notifications@github.com>
wrote:

> Stylistically it's a nice nod to the core brand so could we use the short
> orange hyphen? And then we sort of own our own brand meet-ups
>
> On Thursday, 16 June 2016, Lars Kruse <notifications@github.com> wrote:
>
> > I think the correct spelling is "meet ups" - which means that technically
> > both "meetups" and "meet-ups" are wrong.
> >
> > meetup.com kinda introduce the spelling "meetup" but I guess mostly for
> > convenience in url and twitter handle.
> >
> > I think we should either stay with the current "Meetups" or use the
> > "Meet-ups" that @jonnycoull <https://github.com/jonnycoull> suggested in
> > the mockup - it's not something I have strong opinions about.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/Praqma/code-conf.com/issues/277#issuecomment-226437237
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AQxmXUlBKLuytpfDx79z2jrs7YDkLUhrks5qMRnXgaJpZM4I3L3A
> >
>
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Praqma/code-conf.com/issues/277#issuecomment-226437890>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD8a44B0cL_s-tyxXMiejWh_VDOvJo4Fks5qMRqIgaJpZM4I3L3A>
> .
>



-- 

[image: ____________________________________________________________]
Timea Kiss
Continuous Delivery Sorceress
tk@praqma.com
+45 25 66 83 44 <+45%2025%2066%2083%2044>
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/academy2016/?src=mailbanner>

**Comment by lakruzz** [comment]
No change needed - we're good

**Comment by lakruzz** [comment]
Issue created
