### ISSUE TITLE
Meetups: Font in the summary is not the correct one

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#279]
in reference to #75

**Comment by illus0r** [comment]
@jonnycoull which font did you use?
![image](https://cloud.githubusercontent.com/assets/797993/16149633/d874e796-349a-11e6-9717-7c861f75187c.png)

**Comment by illus0r** [comment]
Hmm, can we use Roboto Mono (so as not to involve 4-th font family 😀 )

![image](https://cloud.githubusercontent.com/assets/797993/16149973/e7fba356-349c-11e6-9e26-0eaab40f4a8c.png)

**Comment by jonnycoull** [comment]
Hi @illus0r its Courier. standard mono type font. to look more like code so this is to be used for all body copy. (its what you've probably seen on the newer mock ups. @lakruzz requested it a while back.

**Comment by illus0r** [comment]
@jonnycoull 
Thanks for your feedback!
Can you find something similar on https://fonts.google.com/?category=Monospace ? That could simplify the job.

**Comment by jonnycoull** [comment]
Cutive Mono looks about the closest i think, has that soft round edge. like courier. but only one size so Im thinking Anon. @illus0r ?

https://fonts.google.com/specimen/Anonymous+Pro?category=Monospace

**Comment by illus0r** [comment]
@jonnycoull that's some pages after applying Anon to body

![image](https://cloud.githubusercontent.com/assets/797993/16152558/2674d36a-34ab-11e6-982a-469bc6fab1af.png)

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/16152612/6d4710aa-34ab-11e6-8d79-df46411f8687.png)

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/16152629/7e1d3440-34ab-11e6-8edc-f7bfcb684b0b.png)

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/16152651/90dd1622-34ab-11e6-969c-32b2084c6e59.png)

**Comment by illus0r** [comment]
closed it in #278

**Comment by timea** [comment]
@lakruzz as a heads up, we worked together with @jonnycoull on the approved designs to make the meetup pages prettier. The font is changed on the site, small improvements were made.
