### ISSUE TITLE
Meetups: Text and picture ratio is not correct in the summary

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#280]
In reference to #75

**Comment by illus0r** [comment]
Sorry, I can't fit the mesh accurately by your mockup because of the grid. Well, I can, but if you need indeed :D Now it looks like on this picture:

![image](https://cloud.githubusercontent.com/assets/797993/16150659/13b9c7bc-34a1-11e6-8d3d-619dfcf2c4cc.png)

**Comment by illus0r** [comment]
If you need, reopen this task
