### ISSUE TITLE
Meetups: Workshops background is missing

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#282]
In reference to #75

**Comment by timea** [comment]
#75 has 
![image](https://cloud.githubusercontent.com/assets/4135651/16113013/64adbf8a-33ba-11e6-8f11-72c9348b32b0.png)
vs we have 
![image](https://cloud.githubusercontent.com/assets/4135651/16113019/74d22108-33ba-11e6-8361-e6c6a591f42b.png)

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/16149294/7813cb1c-3498-11e6-96ad-146df881aba6.png)

**Comment by jonnycoull** [comment]
@timea can the copy be tidied as well or is that hidden in another issue?

**Comment by timea** [comment]
@jonnycoull That does not have an issue yet. That would be a new issue in
the content update milestone, with a mention to @monalarsen :)

On Fri, Jun 17, 2016 at 2:43 PM, jonnycoull <notifications@github.com>
wrote:

> @timea <https://github.com/timea> can the copy be tidied as well or is
> that hidden in another issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Praqma/code-conf.com/issues/282#issuecomment-226759148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD8a46pFwjS0DNmXlqDY0n1w1tybhTARks5qMpaDgaJpZM4I3Mjf>
> .
>



-- 

[image: ____________________________________________________________]
Timea Kiss
Continuous Delivery Sorceress
tk@praqma.com
+45 25 66 83 44 <+45%2025%2066%2083%2044>
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/academy2016/?src=mailbanner>
