### ISSUE TITLE
Meetups: Workshop text is with wrong fonts

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#283]
In reference to  #75

**Comment by lakruzz** [comment]
@timea 
This case is assigned to you for more information.

Please elaborate on what it's about - it's unclear. Consider using examples or even better screen dumps that unambiguously describes what this case is about.

When you are done, please unassign yourself from the case

---

What is the "Workshop text" ? 

Could you elaborate - what page are we talking about @timea What do you see - and what would you rather see?

**Comment by timea** [comment]
What I mean is 
#75 has
![image](https://cloud.githubusercontent.com/assets/4135651/16112899/d3d4d4f8-33b9-11e6-9342-c13f091b9fde.png)
vs we have 
![image](https://cloud.githubusercontent.com/assets/4135651/16112917/e4e0345e-33b9-11e6-83ad-a7dbd49e2c13.png)

I collected all deviations from the design, so we can prioritize them in the next meeting.
