### ISSUE TITLE
Meetups: 'What are you waiting for' wrong font

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#284]
In reference to #75

**Comment by lakruzz** [comment]
@timea 
This case is assigned to you for more information.

Please elaborate on what it's about - it's unclear. Consider using examples or even better screen dumps that unambiguously describes what this case is about.

When you are done, please unassign yourself from the case

**Comment by timea** [comment]
What I mean is 
#75 has 
![image](https://cloud.githubusercontent.com/assets/4135651/16112960/156c3550-33ba-11e6-8504-ac3ce3c4c4af.png)
vs we have 
![image](https://cloud.githubusercontent.com/assets/4135651/16112977/260c4e2c-33ba-11e6-97d0-02c4dbbbc887.png)
