### ISSUE TITLE
Automation Night -> Automation nights

### ISSUE THREAD

**Issue by RandomSort** [Praqma/code-conf.com#287]
The title at http://www.code-conf.com/automation-nights-aar/ is Automation Night, it should be Automation Nights . Perhaps Automation Nights Aarhus .
I'm undecided on the use of the plural or singular term in the body text.
/end nitpicking

**Comment by timea** [comment]
@RandomSort the thing is, if we put the 's' on, it breaks the design in some places... Sorry. We needed short names, otherwise the layout is ... lets just say wrong. I will make an issue to take the off button off, so we can have your s displaying.

**Comment by timea** [comment]
@RandomSort 
![image](https://cloud.githubusercontent.com/assets/4135651/16144722/2012c210-3475-11e6-81ec-c3c612a927c3.png)

**Comment by timea** [comment]
Actually @RandomSort #266 is your way to happiness :)
