### ISSUE TITLE
Buggy mobile menu

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#288]
![image](https://cloud.githubusercontent.com/assets/797993/16146526/22ca56e6-3487-11e6-82b8-d83e0028622f.png)

**Comment by jonnycoull** [comment]
Could there be some sort of auto code that detects a headline over a certain amount of characters / size and adjusts the font size to shrink it to fit? @illus0r

**Comment by illus0r** [comment]
@jonnycoull I'd like to make a 🍔  menu :)

**Comment by jonnycoull** [comment]
@illus0r make it so, its the best solution on mobile. do you need a icon?

**Comment by illus0r** [comment]
@jonnycoull yep! Thanks!
And it's possible a good idea *not* to make a mobile menu design before I implement something. We can style it later, if we'll need.

**Comment by illus0r** [comment]
After #275 it became even more ugly

![image](https://cloud.githubusercontent.com/assets/797993/17027067/1af6f09c-4f6b-11e6-8db6-874e1d73dbf9.png)

And It became more sophisticated, need some js work, so it's large now.

**Comment by illus0r** [comment]
![screenshot_2016-08-26-07-52-43](https://cloud.githubusercontent.com/assets/155492/18009503/d54599e6-6bac-11e6-81a6-849e941c6ada.png)

Snapshot from my android

**Comment by illus0r** [comment]
- [ ] style mobile view
   - [ ] set social icons into the place
   - [ ] align menu items
- [ ] style desktop view
- [ ] check tablet view
- [ ]

**Comment by illus0r** [comment]
almost done. need to test everywhere

**Comment by illus0r** [comment]
BTW removed vertical scroll from this element on mobile

![image](https://cloud.githubusercontent.com/assets/797993/18127793/3c57a34a-6f8b-11e6-8214-87815c0c2ade.png)

**Comment by lakruzz** [comment]
Thanks @illus0r 

...we needed this, goo to see it implemented 👍
