### ISSUE TITLE
Amend style for bottom section in meet-ups.

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#289]
Hi @timea @illus0r Could we polish the base section of the meet ups please? to add in the separate section, too much white currently. 

this... 
![screen shot 2016-06-17 at 11 44 17](https://cloud.githubusercontent.com/assets/17589853/16148327/e0350cbe-3480-11e6-965e-2ba1df37686f.png)

needs to become....
![screen shot 2016-06-17 at 11 47 08](https://cloud.githubusercontent.com/assets/17589853/16148429/76c7ee1c-3481-11e6-93a9-96db8e242949.png)

**Comment by timea** [comment]
@jonnycoull thanks for the input! There are already tasks for that! #282 #283

When you create an issue, please do not assign priority or people, just create the issue. You can always poke us with @illus0r  and @timea, just this way we keep our process :)
