### ISSUE TITLE
Polish a top-nav

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#29]

**Comment by illus0r** [comment]
@jonnycoull I want to get an idea of how do menu items look like:
- [ ] hover
- [ ] active

Could you submit just a small part of a mockup showing these states?

**Comment by illus0r** [comment]
@lakruzz 
We didn't decide yet if we use the social buttons in the *topnav* or not. I also need a **hover** and **active** states for a mockup.

**Comment by illus0r** [comment]
We need to links on it at all (for the Easter MVP) right?

**Comment by lakruzz** [comment]
@illus0r 
I think you are right, @mike or I might do a short "About Code-Conf"  page, but let's see.

**Comment by illus0r** [comment]
Hi, @jonnycoull! I still need these menu link states

**Comment by illus0r** [comment]
I'm talking about the first comment

**Comment by jonnycoull** [comment]
IDLE - WHITE
OVER - 70% WHITE
ACTIVE - CODE CONF ORANGE
