### ISSUE TITLE
Update event calendar on frontpage

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#293]
Calendar needs to be updated. (Academy Trondheim)

Can we have the calendar update itself based on end date?

**Comment by illus0r** [comment]
@adamhenriques 
It updates on every rebuild. Can you describe the problem? How can I see it?

**Comment by illus0r** [comment]
@adamhenriques @jonnycoull 
What should I do to close this task?

**Comment by jonnycoull** [comment]
I think this was to auto update the calander so when the last day rolls by
it comes off? Adam is that right?

**Comment by illus0r** [comment]
What's your point, @adamhenriques? 
I see further events only. What's desirable behavior?

![image](https://cloud.githubusercontent.com/assets/797993/18309349/9404fd42-7501-11e6-8376-e205746777d1.png)

**Comment by adamhenriques** [comment]
This is an old issue and solved
