### ISSUE TITLE
Individual Conference Description/teasers

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#300]
Could we get teasers on the individual conference landing pages describing the format of the conference. We only have for CoDe Sthlm: http://www.code-conf.com/code-sthlm-2016/ http://www.code-conf.com/events/?tag=conferences

We need that for all events to sell/explain the conference format.

**Comment by monaslarsen** [comment]
- Copy CoDeConf Sthlm to Cph
- Write up DoC Sthlm + Cph
