### ISSUE TITLE
Change the color of code-sthlm-2016 so we can see the switch button on the site

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#303]
For use on the orange bars where the orange icon isn't visible. thats the only use. 

link here...

images/on-symbolblk.png

@illus0r @timea

**Comment by jonnycoull** [comment]
I think this is closed? @timea

**Comment by illus0r** [comment]
@jonnycoull nope 
![image](https://cloud.githubusercontent.com/assets/797993/17701083/0f92f87a-63d1-11e6-8fa2-e471b4e24e57.png)
I've added a small label, so I'll start soon

**Comment by jonnycoull** [comment]
ah. on it.

**Comment by jonnycoull** [comment]
![on-symbolblk](https://cloud.githubusercontent.com/assets/17589853/17705188/7062b2a0-63cf-11e6-9d71-d64a9f246d38.png)

**Comment by jonnycoull** [comment]
Uploaded to images plus SVG @illus0r

**Comment by illus0r** [comment]
The same this as to #301 — doesn't work correctly in some places on production. My jekyll is `3.2.1` and should work as on GH pages. 

It starts to be a problem, so I'll try to solve this tomorrow to finalize this and #301 tasks.

**Comment by illus0r** [comment]
That's how I see it on local 
![image](https://cloud.githubusercontent.com/assets/797993/18280779/00fab80a-7463-11e6-9495-4cc7fc0a05ae.png)

**Comment by illus0r** [comment]
closed in 54073ab
