### ISSUE TITLE
Dead / not working links on code-conf.com

### ISSUE THREAD

**Issue by bicschneider** [Praqma/code-conf.com#304]
That's it. 242 links checked. 25 warnings found. 5 errors found. 

[linkchecker-code-conf.zip](https://github.com/Praqma/code-conf.com/files/342958/linkchecker-code-conf.zip)

LinkChecker 8.6

LinkChecker comes with ABSOLUTELY NO WARRANTY! This is free software, and you are welcome to redistribute it under certain conditions. Look at the file `LICENSE' within this distribution.

Start checking at 2016-06-30 15:33:00+000 

URL	`../fonts/bootstrap/glyphicons-halflings-regular.eot'
Parent URL	http://www.code-conf.com/css/main.css, line 106, col 59 (HTML) (CSS)
Real URL	http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.eot
Size	5KB
Check time	0.593 seconds
Result	Error: 404 Not Found

URL	`../fonts/bootstrap/glyphicons-halflings-regular.woff'
Parent URL	http://www.code-conf.com/css/main.css, line 106, col 297 (HTML) (CSS)
Real URL	http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.woff
Size	5KB
Check time	0.595 seconds
Result	Error: 404 Not Found

URL	`../fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular'
Parent URL	http://www.code-conf.com/css/main.css, line 106, col 452 (HTML) (CSS)
Real URL	http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
Size	5KB
Check time	0.608 seconds
Result	Error: 404 Not Found

URL	`../fonts/bootstrap/glyphicons-halflings-regular.ttf'
Parent URL	http://www.code-conf.com/css/main.css, line 106, col 373 (HTML) (CSS)
Real URL	http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.ttf
Size	5KB
Check time	1.076 seconds
Result	Error: 404 Not Found

URL	`//eventbrite.co.uk/tickets-external?eid=20856339874&ref=etckt'
Parent URL	http://www.code-conf.com/doc-cph-2016/, line 1134, col 7
Real URL	http://www.eventbrite.co.uk/tickets-external?eid=20856339874&ref=etckt
Check time	0.842 seconds
Info	Redirected to `http://www.eventbrite.co.uk/tickets-external?eid=20856339874&ref=etckt'.
Redirected to `https://www.eventbrite.co.uk/tickets-external?eid=20856339874&ref=etckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`//eventbrite.co.uk/tickets-external?eid=24617023179&ref=etckt'
Parent URL	http://www.code-conf.com/academy2016/aar/, line 240, col 7
Real URL	http://www.eventbrite.co.uk/tickets-external?eid=24617023179&ref=etckt
Check time	1.075 seconds
Info	Redirected to `http://www.eventbrite.co.uk/tickets-external?eid=24617023179&ref=etckt'.
Redirected to `https://www.eventbrite.co.uk/tickets-external?eid=24617023179&ref=etckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`//eventbrite.co.uk/tickets-external?eid=20692623193&ref=etckt'
Parent URL	http://www.code-conf.com/doc-sthlm-2016/, line 1265, col 7
Real URL	http://www.eventbrite.co.uk/tickets-external?eid=20692623193&ref=etckt
Check time	0.899 seconds
Info	Redirected to `http://www.eventbrite.co.uk/tickets-external?eid=20692623193&ref=etckt'.
Redirected to `https://www.eventbrite.co.uk/tickets-external?eid=20692623193&ref=etckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`//eventbrite.co.uk/tickets-external?eid=24616072335&ref=etckt'
Parent URL	http://www.code-conf.com/academy2016/osl/, line 240, col 7
Real URL	http://www.eventbrite.co.uk/tickets-external?eid=24616072335&ref=etckt
Check time	0.848 seconds
Info	Redirected to `http://www.eventbrite.co.uk/tickets-external?eid=24616072335&ref=etckt'.
Redirected to `https://www.eventbrite.co.uk/tickets-external?eid=24616072335&ref=etckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`http://www.eventbrite.com/e/test-tickets-24616072335?ref=ebtnebtckt'
Name	`Eventbrite tickets'
Parent URL	http://www.code-conf.com/academy2016/osl/, line 242, col 5
Real URL	http://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-oslo-tickets-24616072335?ref=ebtnebtckt
Size	0B
Check time	0.933 seconds
Info	Redirected to `http://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-oslo-tickets-24616072335?ref=ebtnebtckt'.
Redirected to `https://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-oslo-tickets-24616072335?ref=ebtnebtckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`http://www.eventbrite.com/e/test-tickets-24617023179?ref=ebtnebtckt'
Name	`Eventbrite tickets'
Parent URL	http://www.code-conf.com/academy2016/aar/, line 242, col 5
Real URL	http://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-aarhus-tickets-24617023179?ref=ebtnebtckt
Size	0B
Check time	1.297 seconds
Info	Redirected to `http://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-aarhus-tickets-24617023179?ref=ebtnebtckt'.
Redirected to `https://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-aarhus-tickets-24617023179?ref=ebtnebtckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`http://www.eventbrite.com/e/test-tickets-20856339874?ref=ebtnebtckt'
Name	`Eventbrite tickets'
Parent URL	http://www.code-conf.com/doc-cph-2016/, line 1136, col 5
Real URL	http://www.eventbrite.co.uk/e/day-of-containers-copenhagen-2016-tickets-20856339874?ref=ebtnebtckt
Size	0B
Check time	1.218 seconds
Info	Redirected to `http://www.eventbrite.co.uk/e/day-of-containers-copenhagen-2016-tickets-20856339874?ref=ebtnebtckt'.
Redirected to `https://www.eventbrite.co.uk/e/day-of-containers-copenhagen-2016-tickets-20856339874?ref=ebtnebtckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`../fonts/bootstrap/glyphicons-halflings-regular.woff2'
Parent URL	http://www.code-conf.com/css/main.css, line 106, col 219 (HTML) (CSS)
Real URL	http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.woff2
Size	5KB
Check time	1.710 seconds
Result	Error: 404 Not Found

URL	`http://www.lego.com'
Name	`www.LEGO.com'
Parent URL	http://www.code-conf.com/speakers/?tag=doc-cph-2016&scrollto=diptanu, line 651, col 259
Real URL	http://www.lego.com
Size	0B
Check time	0.703 seconds
Warning	Content size is zero.
Result	Valid: 303 See Other

URL	`http://www.elastx.se'
Name	`Elastx'
Parent URL	http://www.code-conf.com/doc-sthlm-2016/, line 1463, col 17
Real URL	http://elastx.se/se
D/L time	0.468 seconds
Size	11.40KB
Check time	1.047 seconds
Info	Redirected to `http://elastx.se/se'.
Modified	2016-06-30 15:35:24.000000Z
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: 200 OK

URL	`//eventbrite.co.uk/tickets-external?eid=24615294007&ref=etckt'
Parent URL	http://www.code-conf.com/academy2016/cph/, line 240, col 7
Real URL	http://www.eventbrite.co.uk/tickets-external?eid=24615294007&ref=etckt
Check time	0.696 seconds
Info	Redirected to `http://www.eventbrite.co.uk/tickets-external?eid=24615294007&ref=etckt'.
Redirected to `https://www.eventbrite.co.uk/tickets-external?eid=24615294007&ref=etckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`http://www.eventbrite.com/e/test-tickets-20692623193?ref=ebtnebtckt'
Name	`Eventbrite tickets'
Parent URL	http://www.code-conf.com/doc-sthlm-2016/, line 1267, col 5
Real URL	http://www.eventbrite.co.uk/e/day-of-containers-stockholm-2016-tickets-20692623193?ref=ebtnebtckt
D/L time	0.843 seconds
Size	29.89KB
Check time	1.274 seconds
Info	Redirected to `http://www.eventbrite.co.uk/e/day-of-containers-stockholm-2016-tickets-20692623193?ref=ebtnebtckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: 200 OK

URL	`http://www.eventbrite.com/e/test-tickets-24615294007?ref=ebtnebtckt'
Name	`Eventbrite tickets'
Parent URL	http://www.code-conf.com/academy2016/cph/, line 242, col 5
Real URL	http://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-copenhagen-tickets-24615294007?ref=ebtnebtckt
Size	0B
Check time	1.034 seconds
Info	Redirected to `http://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-copenhagen-tickets-24615294007?ref=ebtnebtckt'.
Redirected to `https://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-copenhagen-tickets-24615294007?ref=ebtnebtckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`https://www.linkedin.com/in/jornerikjensen'
Name	`jornerikjensen'
Parent URL	http://www.code-conf.com/speakers/?tag=doc-cph-2016&scrollto=diptanu, line 655, col 24
Real URL	https://www.linkedin.com/in/jornerikjensen
Size	9KB
Check time	2.061 seconds
Warning	Access denied by robots.txt, skipping content checks.
Result	Valid: 200 OK

URL	`//eventbrite.co.uk/tickets-external?eid=24850613855&ref=etckt'
Parent URL	http://www.code-conf.com/code-sthlm-2016/, line 1052, col 7
Real URL	http://www.eventbrite.co.uk/tickets-external?eid=24850613855&ref=etckt
Check time	0.629 seconds
Info	Redirected to `http://www.eventbrite.co.uk/tickets-external?eid=24850613855&ref=etckt'.
Redirected to `https://www.eventbrite.co.uk/tickets-external?eid=24850613855&ref=etckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`//eventbrite.co.uk/tickets-external?eid=23441015709&ref=etckt'
Parent URL	http://www.code-conf.com/code-cph-2016/, line 1385, col 7
Real URL	http://www.eventbrite.co.uk/tickets-external?eid=23441015709&ref=etckt
Check time	0.595 seconds
Info	Redirected to `http://www.eventbrite.co.uk/tickets-external?eid=23441015709&ref=etckt'.
Redirected to `https://www.eventbrite.co.uk/tickets-external?eid=23441015709&ref=etckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`https://twitter.com/lnxchk'
Name	`@lnxchk'
Parent URL	http://www.code-conf.com/speakers/?tag=doc-cph-2016&scrollto=diptanu, line 885, col 23
Real URL	https://twitter.com/lnxchk
Size	270.86KB
Check time	2.771 seconds
Modified	2016-06-30 15:35:27.000000Z
Warning	could not get content: error: [Errno 104] Connection reset by peer
Result	Valid: 200 OK

URL	`https://www.chef.io/'
Name	`Chef'
Parent URL	http://www.code-conf.com/code-cph-2016/, line 1559, col 17
Real URL	https://www.chef.io/
Size	9KB
Check time	0.846 seconds
Modified	2016-06-28 01:00:19.000000Z
Warning	Access denied by robots.txt, skipping content checks.
Result	Valid: 200 OK

URL	`http://powersolutions.danfoss.com/'
Name	`Danfoss'
Parent URL	http://www.code-conf.com/academy2016/aar/, line 349, col 17
Real URL	http://powersolutions.danfoss.com/home/
D/L time	0.371 seconds
Size	190.34KB
Check time	4.253 seconds
Info	Redirected to `http://powersolutions.danfoss.com/home/'.
Modified	2016-06-30 15:35:26.000000Z
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: 200 OK

URL	`https://docker.com/'
Name	`Docker'
Parent URL	http://www.code-conf.com/doc-cph-2016/, line 1178, col 17
Real URL	https://www.docker.com/
D/L time	0.614 seconds
Size	10.02KB
Check time	2.694 seconds
Info	Redirected to `https://www.docker.com/'.
Modified	2016-06-30 14:50:56.000000Z
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: 200 OK

URL	`http://www.eventbrite.com/e/test-tickets-23441015709?ref=ebtnebtckt'
Name	`Eventbrite tickets'
Parent URL	http://www.code-conf.com/code-cph-2016/, line 1387, col 5
Real URL	http://www.eventbrite.co.uk/e/continuous-delivery-devops-conference-copenhagen-2016-tickets-23441015709?ref=ebtnebtckt
D/L time	0.811 seconds
Size	30.31KB
Check time	1.157 seconds
Info	Redirected to `http://www.eventbrite.co.uk/e/continuous-delivery-devops-conference-copenhagen-2016-tickets-23441015709?ref=ebtnebtckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: 200 OK

URL	`http://www.eventbrite.com/e/test-tickets-24573031599?ref=ebtnebtckt'
Name	`Eventbrite tickets'
Parent URL	http://www.code-conf.com/academy2016/trd/, line 242, col 5
Real URL	http://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-trondheim-tickets-24573031599?ref=ebtnebtckt
Size	0B
Check time	0.618 seconds
Info	Redirected to `http://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-trondheim-tickets-24573031599?ref=ebtnebtckt'.
Redirected to `https://www.eventbrite.co.uk/e/continuous-delivery-academy-2016-trondheim-tickets-24573031599?ref=ebtnebtckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`//eventbrite.co.uk/tickets-external?eid=24573031599&ref=etckt'
Parent URL	http://www.code-conf.com/academy2016/trd/, line 240, col 7
Real URL	http://www.eventbrite.co.uk/tickets-external?eid=24573031599&ref=etckt
Check time	0.629 seconds
Info	Redirected to `http://www.eventbrite.co.uk/tickets-external?eid=24573031599&ref=etckt'.
Redirected to `https://www.eventbrite.co.uk/tickets-external?eid=24573031599&ref=etckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: syntax OK

URL	`http://www.deliveryofthingsworld.com'
Name	`Delivery Of Things World'
Parent URL	http://www.code-conf.com/code-sthlm-2016/, line 1247, col 17
Real URL	http://deliveryofthingsworld.com/en/
D/L time	0.535 seconds
Size	18.81KB
Check time	6.599 seconds
Info	Redirected to `http://deliveryofthingsworld.com/'.
Redirected to `http://deliveryofthingsworld.com/en/'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: 200 OK

URL	`http://www.nykredit.dk/'
Name	`Nykredit'
Parent URL	http://www.code-conf.com/code-cph-2016/, line 2095, col 17
Real URL	http://www.nykredit.dk/
Check time	6.166 seconds
Modified	2016-06-13 08:09:05.000000Z
Warning	Access denied by robots.txt, skipping content checks.
Result	Valid: 200 OK

URL	`http://www.eventbrite.com/e/test-tickets-24850613855?ref=ebtnebtckt'
Name	`Eventbrite tickets'
Parent URL	http://www.code-conf.com/code-sthlm-2016/, line 1054, col 5
Real URL	http://www.eventbrite.co.uk/e/continuous-delivery-devops-conference-stockholm-2016-tickets-24850613855?ref=ebtnebtckt
D/L time	5.826 seconds
Size	30.38KB
Check time	2.015 seconds
Info	Redirected to `http://www.eventbrite.co.uk/e/continuous-delivery-devops-conference-stockholm-2016-tickets-24850613855?ref=ebtnebtckt'.
Warning	HTTP 301 (moved permanent) encountered: you should update this link.
Result	Valid: 200 OK

Statistics
Number of domains: 34 
Content types: 92 image, 136 text, 0 video, 0 audio, 13 application, 1 mail and 0 other. 
URL lengths: min=18, max=118, avg=54. 

That's it. 242 links checked. 25 warnings found. 5 errors found. 
Stopped checking at 2016-06-30 15:33:12+000 (11 seconds)

LinkChecker 8.6, Copyright © 2000-2013 Bastian Kleineidam
Get the newest version at http://wummel.github.io/linkchecker/.
Write comments and bugs to https://github.com/wummel/linkchecker/issues.
Support this project at http://wummel.github.io/linkchecker/donations.html.

**Comment by lakruzz** [comment]
We need a way to filter http 301 errors (permanent redirects) out, they
don't even qualify as warnings.

**Comment by DharaniSP** [comment]
Hi Lars,

1.Configure a global rule.
2.Add it to post-build step.
3.In job_dsl : For job linkcheck add the following code

job('Web_'+site.split('http://')[1] + '-linkcheck') {
..
...
..
consoleParsing {
          globalRules('LinkCheckerError')
          unstableOnWarning() //optional
          failBuildOnError() //optional
      }
..
..
}


4. In Addition to this,

 install log parser plugin, which can parse and highlight the
errors/warnings.


Regards,
Dharani

**Comment by DharaniSP** [comment]
These steps  are for a better view of logs :)
