### ISSUE TITLE
Work with Ivan on adding headlines and white boxes for event-descriptions

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/code-conf.com#316]
All events now have an info-box, but need more styling - white headlines, line changes etc.

Examine existing options in the current stylesheet and apply or have more options added through Ivan

**Comment by illus0r** [comment]
@monaslarsen 
Привет, Мона! How can I help you with this task?

**Comment by jonnycoull** [comment]
@monaslarsen can you explain this in more detail?

**Comment by monaslarsen** [comment]
Hey @ivan and @jonnycoull 
Right now an event like: http://www.code-conf.com/code-sthlm-2016/
has headlines in the dark and the description text is put on white strips. 
That looks cool for shorter information, but for longer text paragraphs, the MarCom team has talked about something more reading friendly, like a box that is all white.

**Comment by jonnycoull** [comment]
@illus0r is working to fix a colour issue with those particular bits.  The layout was never meant for long paragraphs.  short and sweet. bullet points. 
![screen shot 2016-10-21 at 12 33 13](https://cloud.githubusercontent.com/assets/17589853/19597135/a1e3956c-978a-11e6-8cf6-1171e340e8b6.png)

**Comment by monaslarsen** [comment]
Great :)

**Comment by jonnycoull** [comment]
@illus0r dont take that photo literally I don't want that page to be grey I'm just illustrating the white icons

**Comment by jonnycoull** [comment]
@monaslarsen @illus0r a rebate of another issue that is being looked at now.
