### ISSUE TITLE
Make past events page

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#325]
The reason is to show past events so participants could see all our feats. That's good for SEO.

**Comment by illus0r** [comment]
My thoughts:
- This page is not important for the site's main function. So it shouldn't show in the main navigation. When user looks for outdated event he'll scroll to the bottom. So link to it should appear in the bottom of every event list (all events, conferences, hackathons, meet-ups) that's natural.
- All events pages should link to same **past events** page, that contains all past events without spitting into types (meet-ups, hackathons etc.)
- Past events should be showed like **past**. They should be grayed out in the list. _Eventbrite_ and _join us_ stuff should be disabled.

**Comment by illus0r** [comment]
Hi, @jonnycoull! Can you design this things? We need to understand, how 
- [ ] the list 
- [ ] past event page 
- [ ] and link to it 

should be presented

**Comment by jonnycoull** [comment]
Hi @illus0r just seen this, ill have a think....

**Comment by jonnycoull** [comment]
Hi @illus0r as per #275 some of it will help resolve this which had the archive or what ever the chosen name is in the top bar in the smaller top right names. also on the footer design that still hasn't been implemented from #275 its been a month I thought this would have been resolved by now. Attached is the revised look of the pen mark that wasn't used in your version of the events pages. PAST EVENTS, AL EVENTS, CONFERENCES etc can all be inserted into the pen circle. on each page. Also in PAST EVENTS (or archive what ever the name will be) it will need a filter to do the same function as the top bar of the existing menu so you ca see just past conferences . THIS WONT adjust the headline in the red circle it will stay PAST EVENTS or ARCHIVE, just highlight the section in the filter below it. @timea

**Comment by jonnycoull** [comment]
![past present](https://cloud.githubusercontent.com/assets/17589853/16983601/777d284e-4e6d-11e6-80cc-11bb1e9b263f.png)

**Comment by jonnycoull** [comment]
@illus0r @timea ill upload that now.

**Comment by illus0r** [comment]
@jonnycoull can you send me such image for the background?
![image](https://cloud.githubusercontent.com/assets/797993/17057109/aee3bfa0-5020-11e6-9da8-a27d3659b602.png)
No title, just marker and stroke, 
990px width.

**Comment by jonnycoull** [comment]
Hi I uploaded it yesterday to images

**Comment by illus0r** [comment]
Hm, I didn't find it. I'll have a look now

**Comment by illus0r** [comment]
@jonnycoull nope, only this one 
![image](https://cloud.githubusercontent.com/assets/797993/17058228/d1540b60-5027-11e6-8387-3bfae3315e20.png)

**Comment by illus0r** [comment]
@jonnycoull I need the pic like this, but without `UP NEXT...`
And 990x250 px
Can you make it for me?

**Comment by illus0r** [comment]
That's how it looks now
![image](https://cloud.githubusercontent.com/assets/797993/17058293/59d9972a-5028-11e6-856b-8fcc8b3edfab.png)

**Comment by jonnycoull** [comment]
@illus0r image uploaded to images mastereventimage2.jpg

**Comment by illus0r** [comment]
@jonnycoull 
What's priority of setting it? That's small task.

**Comment by jonnycoull** [comment]
@illus0r if it can be done quickly get it changed as the other pic looks low res. pick as you see fit that can be quickly executed.

**Comment by illus0r** [comment]
I guess this stuff should be closed still it's the last issue in the milestone.
