### ISSUE TITLE
Implement new footer

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#330]
After #275

![](https://cloud.githubusercontent.com/assets/17589853/16983408/97869180-4e6c-11e6-8647-93b0dcc288c2.png)

**Comment by illus0r** [comment]
- [ ] output rough *event* links
- [ ] output rough *compary info*
- [ ] reuse social
- [ ] add signature on the bottom *Copyright Praqma all rights reserved*
- [ ] highlight active links

**Comment by illus0r** [comment]
Preliminary result

![image](https://cloud.githubusercontent.com/assets/797993/17249424/91500722-55a8-11e6-846a-17fbe8271193.png)

**Comment by illus0r** [comment]
I won't contract menu sections by now, because some of them have multiline items

**Comment by illus0r** [comment]
Finally!

![image](https://cloud.githubusercontent.com/assets/797993/17330133/3a3c6eac-58ce-11e6-937f-7f4391f8a444.png)

![image](https://cloud.githubusercontent.com/assets/797993/17330140/4289ea12-58ce-11e6-85ff-7e7e5b9f3df8.png)

**Comment by jonnycoull** [comment]
Nice one mate!
