### ISSUE TITLE
Add presentation title for Key Notes

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#337]
Currently the presentation title doesnt show for all the keynotes as opposed to the regular speakers where the presentation titles are shown. 

http://www.code-conf.com/doc-sthlm-2016/
&
http://www.code-conf.com/code-cph-2016/

Can we have this changed so that we we can display the title of the keynotes

**Comment by illus0r** [comment]
@adamhenriques, sure!

**Comment by adamhenriques** [comment]
Great, thanks!

Regards

Adam Henriques

**Comment by illus0r** [comment]
Duplicates #356
