### ISSUE TITLE
Link on the subpage to the sponsor does not work

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#339]
On a conference page, we can click the sponsors, we get to a subpage with a description of the company. The logo showing up on the subpage should lead us to the sponsor's website.

For example the octocat here should lead to enterprise.github.com
![image](https://cloud.githubusercontent.com/assets/4135651/17099982/fcebd87a-526b-11e6-9ead-d8436a1bad92.png)

**Comment by illus0r** [comment]
Make sense! I'll do it
