### ISSUE TITLE
Linkchecker errors

### ISSUE THREAD

**Issue by timea** [Praqma/code-conf.com#340]
from linkchecker 

1)
URL        `http://www.prtaqma.com'
Name       `Praqma'
Parent URL http://www.code-conf.com/about/, line 152, col 4
Real URL   http://www.prtaqma.com
Check time 0.184 seconds
Result     Error: Hostname not found

2)
URL        `../fonts/bootstrap/glyphicons-halflings-regular.woff2'
Parent URL http://www.code-conf.com/css/main.css, line 106, col 219
Real URL   http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.woff2
Check time 0.606 seconds
Size       5KB
Result     Error: 404 Not Found

3) 
URL        `../fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular'
Parent URL http://www.code-conf.com/css/main.css, line 106, col 452
Real URL   http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
Check time 1.020 seconds
Size       5KB
Result     Error: 404 Not Found

4)
URL        `../fonts/bootstrap/glyphicons-halflings-regular.eot'
Parent URL http://www.code-conf.com/css/main.css, line 106, col 59
Real URL   http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.eot
Check time 2.664 seconds
Size       5KB
Result     Error: 404 Not Found

5)
URL        `../fonts/bootstrap/glyphicons-halflings-regular.woff'
Parent URL http://www.code-conf.com/css/main.css, line 106, col 297
Real URL   http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.woff
Check time 3.429 seconds
Size       5KB
Result     Error: 404 Not Found

6)
URL        `../fonts/bootstrap/glyphicons-halflings-regular.ttf'
Parent URL http://www.code-conf.com/css/main.css, line 106, col 373
Real URL   http://www.code-conf.com/fonts/bootstrap/glyphicons-halflings-regular.ttf
Check time 3.868 seconds
Size       5KB
Result     Error: 404 Not Found

**Comment by bicschneider** [comment]
@timea : fixed
