### ISSUE TITLE
Docker meetup group as sponsor

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#344]
How did the CPH Docker meetup group get to become sponsor at http://www.code-conf.com/doc-cph-2016/

@adamhenriques? @monaslarsen?

![image](https://cloud.githubusercontent.com/assets/155492/17293206/3a846e6c-57ef-11e6-9775-ebc9ec0817c0.png)

Did they pay anything to get their logo there - from the size of the logo, - compared to Docker - it looks like they paid A LOT! 

...Which I somehow assume that the actually DIDN'T - Could we we adjust the logo-size accordingly?

**Comment by adamhenriques** [comment]
They became communitysponsors as part of collaboration giving us access to the group.

Regards

Adam Henriques
