### ISSUE TITLE
CoDe:U meetup group as sponsor for DoC and CoDe in Stockholm and Copenhagen

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/code-conf.com#349]
Obviously, we have to point out correct meetup group for Stockholm (www.meetup.com/CoDe-U-STHLM/) and Copenhagen (http://www.meetup.com/CoDe-U/)

**Comment by monaslarsen** [comment]
Hey @Andrey9kin, just checking: What we need to do is ADD the two meetup groups as sponsors for all four events?

**Comment by Andrey9kin** [comment]
@monaslarsen adding meetup groups logos as we already did with the Docker meetup group for DoC in Stockholm
