### ISSUE TITLE
Display presentation title for KeyNotes

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#356]
Currently the keynotes at out events dont display the presentation title like the "regular" presentations. Can we enable this?

![screen shot 2016-08-15 at 16 03 14](https://cloud.githubusercontent.com/assets/8004259/17666717/dc713f8a-6301-11e6-9cd6-0a3f4eb4b655.png)

**Comment by illus0r** [comment]
Hi, @jonnycoull! What's prio for this change?
Uh, I may be wrong about new set of team responsibilities, let me know if setting priorities is not your duty.

**Comment by adamhenriques** [comment]
@illus0r ive added the prio - we need it asap at the conference is just 1 month out. Thanks.

**Comment by jonnycoull** [comment]
@illus0r there you go, adam has spoken.

**Comment by jonnycoull** [comment]
Hi @illus0r we need to make the BIG speakers copy like the seller ones... Also use that style so Big headline for Name, slightly smaller for job, as it is. Then a sub head like the small speakers. then the body copy smaller again. like the smaller speakers. @adamhenriques needs this ASAP. top pro. 

NAME: JOB TITLE: 
PRESENTATION TITLE: (currently un displayed) 
BODY COPY:
TWITTER HANDELS, ETC.

**Comment by illus0r** [comment]
@jonnycoull 
1. What do you mean by `seller`?
Not sure I understood all suggested style fixes correctly, can you make a mockup or plan a short hangout after I'll fix code part?

**Comment by jonnycoull** [comment]
Basically the presentation title is missing.  see this quick mocks to illustrate..... @illus0r 
![screen shot 2016-08-19 at 11 37 17](https://cloud.githubusercontent.com/assets/17589853/17807352/d1425b82-6601-11e6-9b51-12a57681c3cf.png)
![screen shot 2016-08-19 at 11 37 25](https://cloud.githubusercontent.com/assets/17589853/17807353/d161cd28-6601-11e6-86e2-f2a4bf5a38eb.png)

**Comment by jonnycoull** [comment]
@illus0r also while were here when you click on a small box (read more) there should be a (read less) option to make it go back? maybe make that another issue.

**Comment by illus0r** [comment]
yep, sure, I'll make another one

**Comment by illus0r** [comment]
But it need to go to another milestone. This one should stop getting new tasks, otherwise It'll last forever.

**Comment by illus0r** [comment]
@jonnycoull this way now
![image](https://cloud.githubusercontent.com/assets/797993/17808445/e17bffa0-6618-11e6-994c-326d403b759d.png)

**Comment by illus0r** [comment]
Added titles, but not sure about scaling down the base font

**Comment by jonnycoull** [comment]
It needs to be some how slightly different to the body copy. can it be bold? @illus0r

**Comment by illus0r** [comment]
@jonnycoull 
fixed small speakers as well to repeat the pattern
![image](https://cloud.githubusercontent.com/assets/797993/17809108/e73e4afc-661c-11e6-9275-1aaf41ebd2e8.png)
![image](https://cloud.githubusercontent.com/assets/797993/17809112/f222e036-661c-11e6-816c-7414b5ff7e04.png)

**Comment by jonnycoull** [comment]
Great @illus0r lets close it up.
