### ISSUE TITLE
Fix calendar / tidy

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#364]
Id like to fix the calendar so it looks and functions a bit smoother. can we have the scroll function operate inside the black box, not scroll all the box its self as it does currently. see mock. so it operates within the green highlighted area? @illus0r 
![screen shot 2016-08-19 at 13 39 06](https://cloud.githubusercontent.com/assets/17589853/17810120/fee975e6-6612-11e6-890e-018a089ed0f3.jpg)

**Comment by illus0r** [comment]
@jonnycoull 
Sure man! 

I want to remove it from this milestone. Every milestone should be closed for new issues till the end. How can we plan the due date if it keeps growing?

I'd ask you to not to estimate the size of the task. I.e. I can't guarantee I'll do it in 2 hours.

**Comment by illus0r** [comment]
Sure, I can fix the size, but I can miss it and count the issue too small or too big

**Comment by illus0r** [comment]
- [ ] set scroll as shown on Bok's mockup
- [ ] make it look acceptable on IE
- [ ] set height to auto on mobile
- [ ] make a fadeout effect to notify user about scrolling opportunity.

**Comment by illus0r** [comment]
Made it look this way on Chrome, FF and IE.
Now there's a scroll, but without ugly IE scrollbars.
It'll be good to add some tips like gradients and small scrollbar though. I'll make a separate task for that.

![image](https://cloud.githubusercontent.com/assets/797993/18313903/7f10f36a-7519-11e6-8102-f38c912602d2.png)
