### ISSUE TITLE
Event ribbon bug

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#365]
The bottom ribbon straches to fit top one.
Added some random text to make but obvious.

![image](https://cloud.githubusercontent.com/assets/797993/17810294/f03eca16-6624-11e6-96ca-05262b7092ae.png)

**Comment by jonnycoull** [comment]
Odd, it wasn't doing that before.

**Comment by illus0r** [comment]
It did, but we had such cases to see it
