### ISSUE TITLE
Sven Peters portrait is not a perfect

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#378]
http://www.code-conf.com/speakers/?tag=code-cph-2016&scrollto=svenpeters

![image](https://cloud.githubusercontent.com/assets/155492/18009272/bfea417e-6bab-11e6-9eea-7bd6c9f339d6.png)

**Comment by illus0r** [comment]
@lakruzz 
can I set tasks for bugs like that and place them into content update?
