### ISSUE TITLE
Hide Hackathons link if no hackathons

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#379]
![image](https://cloud.githubusercontent.com/assets/797993/18009304/44726298-6bb4-11e6-803a-f81c84196de2.png)

Or entirely remove the section from the site if we don't need it for now.

**Comment by illus0r** [comment]
@lakruzz @jonnycoull 
I started working on this one and then realized: we'd better keep this links. If there's no upcoming events on them, we'll show a message "Hey, dude! We have no upcoming hackathons. Subscribe and we'll notify you about new events!"

**Comment by illus0r** [comment]
@lakruzz @jonnycoull 
what's your point about this idea? Can I make a task for that for the current milestone?

**Comment by jonnycoull** [comment]
@lakruzz @illus0r might be a job for praqma's new mascot, and a speech bubble. I'm speaking with Lars this week so il get back to you then.

**Comment by jonnycoull** [comment]
UPDATE: I'm getting bruce to scrub some text for this then when i have the robot ill place the image. @illus0r

**Comment by illus0r** [comment]
@jonnycoull good, I'm stopping until your input

**Comment by jonnycoull** [comment]
I now have copy, and robot. so this will be done today. @illus0r

**Comment by jonnycoull** [comment]
![screen shot 2016-09-22 at 15 13 04](https://cloud.githubusercontent.com/assets/17589853/18751510/32feee2c-80d7-11e6-83fe-a3ef872f1ea2.png)

Mock up, this is an MVP we have commissioned a more specific robot, he'll be with us monday. image uploaded.

**Comment by lakruzz** [comment]
I like this, let's go with something like this.

I have cleared the action label, and assigned back to @illus0r so we can proceed

**Comment by illus0r** [comment]
Great, I can work with it :)

**Comment by jonnycoull** [comment]
Final version is ready... @illus0r @lakruzz 

![noevents](https://cloud.githubusercontent.com/assets/17589853/18954021/01944cac-8649-11e6-9c6b-d70a92094d7a.jpg)

**Comment by jonnycoull** [comment]
![noevents](https://cloud.githubusercontent.com/assets/17589853/18954086/3b167e6e-8649-11e6-9665-f62add7c8166.jpg)

Im uploading a blank one as well so you can make that text responsive? @illus0r

**Comment by jonnycoull** [comment]
![noeventsblabk](https://cloud.githubusercontent.com/assets/17589853/18954104/4dae8dfa-8649-11e6-89d3-8de4562e9c93.jpg)

**Comment by lakruzz** [comment]
@jonnycoull These are really cool :-)

**Comment by illus0r** [comment]
- [ ] show the image if no events
- [ ] make it responsive

**Comment by illus0r** [comment]
We have no newsletter form on mobile.
So we should whether implement it or remove small text on mobile.

**Comment by jonnycoull** [comment]
hmm. this probably needs to be a separate task but with cookies could we have a pop up news letter form on mobile, and if they have been before and filled in it doesn't pop up?? as most people access web that way now.

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/19107729/518eb45c-8af6-11e6-8c01-69126ee14c7d.png)


![image](https://cloud.githubusercontent.com/assets/797993/19107676/0c107ff0-8af6-11e6-9992-422a05da1fa4.png)

**Comment by illus0r** [comment]
@jonnycoull can you make a new task for that discussion?

**Comment by illus0r** [comment]
@jonnycoull milestone 🔫
