### ISSUE TITLE
Portraits: all in color or all in black and white

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#380]
We lack consistency here:

http://www.code-conf.com/speakers/

![image](https://cloud.githubusercontent.com/assets/155492/18009349/1dc28c8e-6bac-11e6-9d19-df735ff48bbf.png)

is it deliberate (why?) or coincidental (we don't do oops!)

**Comment by jonnycoull** [comment]
@lakruzz @monaslarsen do we have all colour images of some of these guys?

**Comment by illus0r** [comment]
@jonnycoull I guess it's easier to make b/w version :D

**Comment by jonnycoull** [comment]
@lakruzz I think it lies in your source imagery. NOTE. @monaslarsen @adamhenriques we NEED colour images of our speakers. ASAP. do you have them? if not i will make black and white.

**Comment by jonnycoull** [comment]
@have images, updating today. @illus0r  to emil speakers images location

**Comment by illus0r** [comment]
@jonnycoull they are kept under `/images/speakers/`

**Comment by jonnycoull** [comment]
@illus0r @lakruzz ready to close but Andrey Devyatkin image still seems to be black n white even after I've changed it. any ideas?

**Comment by illus0r** [comment]
@jonnycoull no worries, it's all good.
![image](https://cloud.githubusercontent.com/assets/797993/20484011/37771a66-b006-11e6-81ad-20a0dab01dd2.png)

But some of your images are huuuuge 🐘 
and not square.
![image](https://cloud.githubusercontent.com/assets/797993/20484064/758f6fb0-b006-11e6-9a54-32eba7fe2733.png)
225x225 is enough

**Comment by jonnycoull** [comment]
size should be fixed now.
