### ISSUE TITLE
Margin in mobile mode - needs to be fixed 

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#382]
![screenshot_2016-08-26-07-53-29](https://cloud.githubusercontent.com/assets/155492/18009538/06876d90-6bad-11e6-8ee1-f2de83de0724.png)

Screenshot from my android - no margin at all.

Footer seems OK though:

![screenshot_2016-08-26-07-53-22](https://cloud.githubusercontent.com/assets/155492/18009573/21db42d8-6bad-11e6-8126-bab0f22f0aad.png)

**Comment by lakruzz** [comment]
@illus0r, marked this "Up next"

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/18168010/4b700486-705c-11e6-92ab-bee2eb50a987.png)

![image](https://cloud.githubusercontent.com/assets/797993/18168025/56e2031e-705c-11e6-94f2-1df92a13868b.png)
