### ISSUE TITLE
Layout on past events is broken

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#383]
We shouldn't ruin our web site, just because the event is past:

http://www.code-conf.com/academy2016/cph/
![image](https://cloud.githubusercontent.com/assets/155492/18017586/6afd634a-6bd2-11e6-88c5-816605f2f403.png)

http://www.code-conf.com/academy2016/trd/
![image](https://cloud.githubusercontent.com/assets/155492/18017607/952e8766-6bd2-11e6-95ee-6b87c294e0c0.png)

**Comment by jonnycoull** [comment]
I don't think the bar should be that big. Is it a bug

**Comment by lakruzz** [comment]
Right

**Comment by illus0r** [comment]
Oh, already done in #386
