### ISSUE TITLE
How is "Am I done" different

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#384]
...from "Waiting for feedback"?

![image](https://cloud.githubusercontent.com/assets/155492/18017704/2895831a-6bd3-11e6-8b63-b1c88a9d6adf.png)

One could argue, that if you think you are done, but you don't know, you request a feedback, but en general if you think you might be done, but don't know for sure, then the briefing or assignment wasn't sufficient in the first place.

We don't want labels we don't use.

**Comment by jonnycoull** [comment]
This was to make it easier to see if the task was near completion and to
check if it can be closed after I ok it.

**Comment by lakruzz** [comment]
@jonnycoull 

Right, I guessed that from the name of the label. But I would argue that if @illus0r thinks he's done, but wants your approval first then if he:

* Writes a comment "Am i done?"
* Add the ![image](https://cloud.githubusercontent.com/assets/155492/18018321/75599328-6bd6-11e6-873e-b789bff3c091.png) label
* Assigns it you

Then that would have the exact same meaning! - hence the new "Am i done?" label is redundant (in our world of programming, redundancy is evil)

**Comment by illus0r** [comment]
@lakruzz 
I wanted to make @jonnycoull's life easier. 

In your approach he have to write a comment "yep, you are", or "nope, you aren't" and assign the issue back to me. If he agree to make it the part of his workflow, I'm fine with it.

**Comment by jonnycoull** [comment]
@illus0r we'll go back to the old way, can u delete that label? @illus0r

**Comment by illus0r** [comment]
@jonnycoull yep, no problem

**Comment by illus0r** [comment]
done
