### ISSUE TITLE
Code CPH looks awful android phone

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#386]
![screenshot_2016-08-28-19-23-32](https://cloud.githubusercontent.com/assets/155492/18035365/4eacfa00-6d55-11e6-99b3-17edad83882a.png)

**Comment by illus0r** [comment]
I want to get rid of manual setting of the font-size.
I'll use js to adjust it. Or more rough but efficient: via liquid by letter count.

**Comment by illus0r** [comment]
care about
- [ ] speaker icon
- [ ] power icon
- [ ] (past) mark

**Comment by illus0r** [comment]
Font size adapts according to its width

![image](https://cloud.githubusercontent.com/assets/797993/18134390/e303b704-6fa6-11e6-9047-8d0577ff61fe.png)


![image](https://cloud.githubusercontent.com/assets/797993/18134463/28061392-6fa7-11e6-84e5-0a6576333593.png)

**Comment by illus0r** [comment]
And yep, I'm out of limits, it took too long

**Comment by lakruzz** [comment]
@illus0r looking good, I believe a rough estimation based on character count relative to font size would would be just fine as a start.

**Comment by illus0r** [comment]
Yep, you are right. I'd better start with small and sufficient.
