### ISSUE TITLE
"graduate" Code Academy CPH and Aar

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/code-conf.com#389]
![selection_028](https://cloud.githubusercontent.com/assets/4633181/18130279/acdd288a-6f8e-11e6-82a5-846fbfd63280.png)

http://www.code-conf.com/academy2016/

**Comment by illus0r** [comment]
I'm working on it in #301 
It should automatize the procedure. Gonna finish it today

Can we close it as duplicate?

**Comment by sofusalbertsen** [comment]
Duplicate of #301

**Comment by illus0r** [comment]
I didn't finish it by now. commented here https://github.com/Praqma/code-conf.com/issues/301#issuecomment-244380928
