### ISSUE TITLE
Show company and position for all speakers on agenda

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/code-conf.com#393]
Currently, we show company and position only for the keynotes.
It is quite hard for people to judge about the conference agenda since in most of the cases they don't know the speakers and they use a company name and job title as justification.

I would very much like to see that, especially for upcoming  CoDe conf in Stockholm.
What is the backlog grooming process? How can I get this done or get an answer that it won't be done?

@adamhenriques @lakruzz @monaslarsen please advice

**Comment by jonnycoull** [comment]
@Andrey9kin  what is it exactly you'd like to see? and where on the site. thanks. J

**Comment by Andrey9kin** [comment]
@jonnycoull take a look on keynote card http://www.code-conf.com/doc-sthlm-2016/
There it says 

Kelsey Hightower  Evangelist, Google
or
Viktor Farcic Docker Captain & Senior Consultant, CloudBees

But for the rest of the cards, it is only a name, not a name and position
So I would like all cards to state name and position not only keynotes

Do you see what I mean?

**Comment by jonnycoull** [comment]
@Andrey9kin yes i do. let me get that resolved.

**Comment by jonnycoull** [comment]
@illus0r can we have all speakers on the site to have the same details visible like they keynote....from @Andrey9kin 
So I would like all cards to state name and position not only keynotes, a small adjustment to include their position as well.  can you set a priority and time scale on this, I'm presuming it shouldn't take too lone to fix?

**Comment by illus0r** [comment]
Привет, @Andrey9kin! Извини, что сразу не ответил. Бок уже всё разрулил. Задача маленькая, но сделать её смогу только на следующей неделе, сейчас я на другом проекте.

**Comment by Andrey9kin** [comment]
Привет, @illus0r! Let's keep it in English ;) Sure, next week is fine.

**Comment by Andrey9kin** [comment]
@illus0r it is just fine for private conversations and I would love to chat with you. But when it is more than two of us involved or there is a probability that we need to involve more people then English is better

**Comment by illus0r** [comment]
Closed by https://github.com/Praqma/code-conf.com/commit/96e1d05a21c160434db071f38f199d3eadd8a812

**Comment by Andrey9kin** [comment]
@jonnycoull @illus0r nice! Thanks!

**Comment by illus0r** [comment]
You are welcome :)
