### ISSUE TITLE
Up next block: reveal the scrolling

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#394]
Subtask of #364

![image](https://cloud.githubusercontent.com/assets/797993/20485405/6dd42030-b00c-11e6-95e8-30dc12b863d4.png)

If there's a lot of links in upnext block, bottom one is cut, no scrollbar appears. 
Add a scrollbar and black gradients on top and bottom of the list, if contents is greater than parent div.

**Comment by illus0r** [comment]
@jonnycoull set should have prio, feel free to change

**Comment by illus0r** [comment]
![untitled](https://cloud.githubusercontent.com/assets/797993/20567782/1a31c9a0-b1ab-11e6-9652-40e23313c884.gif)

**Comment by jonnycoull** [comment]
@illus0r looks cool!

**Comment by illus0r** [comment]
closed by 814c01b14dd69d91ff7da290f7b64d20e1ef5333

**Comment by illus0r** [comment]
@jonnycoull thanks, man. And it works even on windows :)

**Comment by jonnycoull** [comment]
@illus0r you da man!
