### ISSUE TITLE
Implement Bock's mockup

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#400]
Subtask of #342

![](https://cloud.githubusercontent.com/assets/17589853/17704531/33cfaf16-63cd-11e6-93cf-1673b916827b.png)

**Comment by illus0r** [comment]
Me
>Hi, mate.
You've drawn this mockup for agenda and I'm about to implement it.
But I see some things that can confuse new participants:
* It looks like I can't jump between branches. But I can.
* It looks like SWAP TRACK, LUNCHBUFFET e.t.c. are for first branch only.

>I'd be happy to spend some time to come up with alternative mockup, which fixes that. I'd make it adapted to mobile. But, sure, I can go on with this mockup, it's good enough. What's your decision?

Bok
> Just take those lines off and that should solve the problem

**Comment by illus0r** [comment]
@jonnycoull  this mockup uses nonstandard fonts. I'll switch to this one, ping me if you object

![image](https://cloud.githubusercontent.com/assets/797993/19884145/56d75cfa-a029-11e6-97e3-e304853de849.png)

**Comment by illus0r** [comment]
@jonnycoull I'm going to right align time. So I'll fix this:
![image](https://cloud.githubusercontent.com/assets/797993/19884323/586b576e-a02a-11e6-826d-202710aa4a85.png)

**Comment by illus0r** [comment]
@jonnycoull and remove the date, cause it duplicates existing info (from date-location section)

**Comment by illus0r** [comment]
@jonnycoull 
Is that another mention of the same date? Or what value to use?
![image](https://cloud.githubusercontent.com/assets/797993/19884620/9fa7e632-a02b-11e6-818a-25a974481575.png)

**Comment by jonnycoull** [comment]
Hi, ah ignore my code font, use the one we agreed on previously for the
site. And yes times to 24hr clock so 08:00 for exe so all same style.

**Comment by illus0r** [comment]
@jonnycoull 
Removed the `?` form the header because we know the answer.
And to be in time I should simplify the header. I can save time reusing existing `decorated-picture` include. It'll look this way.
![image](https://cloud.githubusercontent.com/assets/797993/19885445/a98013d8-a02f-11e6-8a57-40023bf4f633.png)

**Comment by illus0r** [comment]
@jonnycoull is this ok?

![image](https://cloud.githubusercontent.com/assets/797993/19887047/4b8ea6c4-a037-11e6-99e1-9bf004bc411a.png)
![image](https://cloud.githubusercontent.com/assets/797993/19887066/6dbde03e-a037-11e6-96b8-df525107f630.png)

**Comment by illus0r** [comment]
Previous image consists of two, so the margin above LUNCH looks smaller

**Comment by jonnycoull** [comment]
Why does it say past?

Looks like it's getting there

**Comment by illus0r** [comment]
@jonnycoull It says past on past events only. What's the reason of removing it?

**Comment by jonnycoull** [comment]
Because the past big should be at the top where it says Stockholm etc not
by the agenda.

**Comment by illus0r** [comment]
@jonnycoull make sense. I'll make a separate task for that, but it's smaller than small. Just not to reopen this one
