### ISSUE TITLE
Show full address for venue on the event page

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/code-conf.com#403]
Currently, event page shows only the city not event a venue name
http://www.code-conf.com/code-sthlm-2016/

Proposal is to show at least venue name and maybe full address but this is up to discussion

**Comment by Andrey9kin** [comment]
I'm changing status because we are getting emails about location of the events and the website doesn't really tell

**Comment by illus0r** [comment]
We could also show the map. What do you think guys?

**Comment by Andrey9kin** [comment]
For me, it would be enough to have a venue name and address. We could do
them as a link to the map or venue website. I don't think that map will be
a good fit to the web page. However, I'm not a designer to judge :)

**Comment by illus0r** [comment]
yep, I think you're right, map is overkill. @jonnycoull, how we can we output  a venue name and address?

**Comment by jonnycoull** [comment]
@illus0r @Andrey9kin 
![screen shot 2016-09-23 at 10 22 53](https://cloud.githubusercontent.com/assets/17589853/18781030/08a8946a-8178-11e6-9e8f-bcac949e38d7.png)
I think we can combine the two, so if you click on the location text icon, this drop down will appear. small map (if you click it takes you to hotel site that has the real one) similarly a link/web address for the hilton. 

NOTE: Ivan i see this page is still orange! its supposed to be purple as per the colour code chart i supplied yourself and timea.

**Comment by jonnycoull** [comment]
Hi @illus0r @Andrey9kin  Ive designed a drop down box so when you tap the location it appears, click X to make it disappear. So i think we can still include a map it just makes it visually referancable. So a small map (if you click it takes you to hotel site that has the real one) similarly a link/web address for the hilton under the text of the address. 

NOTE: Ivan i see this page is still orange! its supposed to be purple as per the colour code chart i supplied yourself and timea.

![screen shot 2016-09-23 at 10 26 23](https://cloud.githubusercontent.com/assets/17589853/18781115/570310c2-8178-11e6-87e4-6677075b6b70.png)

**Comment by Andrey9kin** [comment]
@jonnycoull Then we need to make sure that people understand that location
is clickable. I'm not sure that I would guess it myself. Do you see what I
mean?

**Comment by jonnycoull** [comment]
@Andrey9kin @illus0r it would have to have the same highlight option as other clickable copy. so when the mouse rolls over it, it changes. Most people would automatically tap it. It original was supposed to open a google address but i see that hasn't happened.

**Comment by jonnycoull** [comment]
@illus0r @Andrey9kin or just have it visible all the time. ALSO, why it maybe isn't there as the venue has changed to this, @adamhenriques this right?? update venue to: MeetingRoom, Alströmergatan 20, 112 47 Stockholm

**Comment by Andrey9kin** [comment]
@jonnycoull that was me who changed it. And yes we are moving from Hilton
to the meeting room.
For me it would be enough to change Stockholm to the actual address + venue
name.

**Comment by jonnycoull** [comment]
@Andrey9kin yes but that doesn't fit with the others in the row, its too much info.  so @illus0r add the box with map and full address please as per the mock up. loose the X to close.

**Comment by illus0r** [comment]
> Then we need to make sure that people understand that location
is clickable 

I agree with @Andrey9kin, we need to make the link to look different. Slight underline would be enough. It should be dotted because we stay on the same page after clicking.

![image](https://cloud.githubusercontent.com/assets/797993/19079273/c1425e52-8a5b-11e6-8d10-d92695992baf.png)

**Comment by illus0r** [comment]
@jonnycoull 
> loose the X to close.

Did you mean to not to implement the cross?

**Comment by jonnycoull** [comment]
@illus0r So, loose the X if the map is always displayed, keep the X (to close) if  WHERE is a clickable button to show map. I think for consistency on the site no dotted line. but use something like the "read more" on the speakers, like "click to see map" or "see map here"
![screen shot 2016-10-04 at 16 06 07](https://cloud.githubusercontent.com/assets/17589853/19079800/bf543e80-8a4c-11e6-95ef-4479cdb1eed1.png)

**Comment by adamhenriques** [comment]
@illus0r @Andrey9kin  as a temperarely solution i have embedded a clickable link for the venue as I had a couple a people asking where the conference was

**Comment by illus0r** [comment]
@jonnycoull it's easier to make map always shown. We can make it togglable later. What do you think?

**Comment by jonnycoull** [comment]
I'm happy with that solution @illus0r

**Comment by illus0r** [comment]
@jonnycoull @lakruzz does it make sense to make another collection: `_plases` to reuse this address info?

**Comment by illus0r** [comment]
And @jonnycoull thanks for using real data on the mockup. It helps me to make the right map without questions.

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/19565304/0ec7f4a8-96ef-11e6-8ce3-3533332ccce7.png)

![image](https://cloud.githubusercontent.com/assets/797993/19565350/2ca3392e-96ef-11e6-8a27-c6b4ceb08c30.png)

**Comment by jonnycoull** [comment]
Lovely stuff. would it be a pain to get that small black triangle on mobile
too?

**Comment by illus0r** [comment]
Hey, @jonnycoull! Is that `done`?

**Comment by illus0r** [comment]
@jonnycoull ahh, sorry didn't see your comment

**Comment by illus0r** [comment]
@jonnycoull 
![image](https://cloud.githubusercontent.com/assets/797993/19567884/1df74d4e-96f8-11e6-9fde-4a396cf4fd0a.png)

**Comment by illus0r** [comment]
@jonnycoull Is that done now?

**Comment by illus0r** [comment]
@jonnycoull please, reopen this task if you need some improvents

**Comment by jonnycoull** [comment]
Thanks Ivan
