### ISSUE TITLE
The abstract text should scroll

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#406]
![image](https://cloud.githubusercontent.com/assets/155492/18942500/c4bf4806-8619-11e6-92ce-261e46a8f8e5.png)

When the text exceed the visual area, it should scroll, so it's possible to read it all.

**Comment by illus0r** [comment]
Oh, I hoped to solve this problem reducing the text :) All right, I'll do it. But I'll hide the scroll completely because it's ugly on Windows

**Comment by jonnycoull** [comment]
@illus0r @lakruzz this i in the wrong repository. will move.

**Comment by illus0r** [comment]
@lakruzz why do you want to keep it opened?
