### ISSUE TITLE
Pop up subscription in mobile

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#409]
@illus0r using cookies (if i have that right) can we have a pop up box that you can close if you don't want it (a bit like you see for cookies permissions on websites) so mobile users can subscribe easily. 

So if they have subscribed, they don't see it. if they haven't it pops up. 

Is that possible. 

Use design from existing site to build it, with an edition of a small close icon. (X) like we have on the map issue.

**Comment by illus0r** [comment]
@jonnycoull `Content Update` milestone is used by editors to update content. All development work should go to other milestones. Current one is `Cleanup 2` but it's closed for adding new items, we need another one for new stuff

**Comment by jonnycoull** [comment]
ok.

**Comment by illus0r** [comment]
That doesn't solve the problem https://github.com/Praqma/code-conf.com/issues/379#issuecomment-251608430

Ok, I've seen the popup and closed it. Now I see this 
![image](https://cloud.githubusercontent.com/assets/797993/19109551/987ae0d6-8afe-11e6-9833-04bb817c72a9.png)
What should I do? How to make it popup again?

**Comment by jonnycoull** [comment]
You lost me I'm afraid @illus0r 
![screen shot 2016-10-05 at 13 20 57](https://cloud.githubusercontent.com/assets/17589853/19112767/9a1a46c0-8afe-11e6-9ebc-c6c2a2ed903f.png)
 I'm referring to this box. to make it available.

**Comment by jonnycoull** [comment]
then the copy goes in as normal as the normal site has it.

**Comment by jonnycoull** [comment]
@illus0r what size of task would this be?

**Comment by illus0r** [comment]
I got your thinking.
But I won't be able to launch this popup intentionally, right?

**Comment by illus0r** [comment]
- [ ] cookies notification
- [ ] show mailing form on chrome

**Comment by jonnycoull** [comment]
@illus0r BIG, split into smaller issues.

**Comment by illus0r** [comment]
@jonnycoull here's breakdown:

- [ ] draw a design for popup
- [ ] show it 2 (?) sec after loading
- [ ] write to cookies, when I load it
- [ ] don't open, if we did it before (this year)
- [ ] style it by the mockup

**Comment by illus0r** [comment]
@jonnycoull will that work?
![image](https://cloud.githubusercontent.com/assets/797993/20628796/2a25361e-b339-11e6-9303-2399b5f941ae.png)

And there's one more thing :-) If someone comes to our site he's not interested in newsletter right after first page loading. We want him to spend some time on the site before we ask about subscription. So it's good to show this form on third-fifth page loading. What's your thinking?

**Comment by jonnycoull** [comment]
Sounds like a plan! All eventualities covered

**Comment by jonnycoull** [comment]
![2a25361e-b339-11e6-9303-2399b5f941ae](https://cloud.githubusercontent.com/assets/17589853/20666462/321bc8fe-b55c-11e6-9f9f-8f324eb51d0f.png)

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/20666518/985a1d46-b575-11e6-9416-d1bb749b2df4.png)

**Comment by jonnycoull** [comment]
@illus0r to implement mock up.

**Comment by jonnycoull** [comment]
@illus0r can we close this??

**Comment by illus0r** [comment]
@jonnycoull Nope, it's in the progress.

**Comment by illus0r** [comment]
- [ ] use js on mobile only
- [ ] replace `window.history.length` with cookies solution
- [ ] remake the cross button
- [ ] remove abolition font bottom margins
