### ISSUE TITLE
Colour match site

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#413]
To match colours to the original document. 
[CODECONF_COLOURS.pdf](https://github.com/Praqma/code-conf.com/files/536786/CODECONF_COLOURS.pdf)

**Comment by jonnycoull** [comment]
Also tweak icons where needed. images have been uploaded to git

![screen shot 2016-10-18 at 17 10 13](https://cloud.githubusercontent.com/assets/17589853/19486267/bedf7dde-9555-11e6-87f6-4bfe8343c00a.png)

**Comment by illus0r** [comment]
@jonnycoull this link to similar task didn't appear :-(

**Comment by illus0r** [comment]
@jonnycoull how to find the similar task form wrong `praqma.com` repository?

**Comment by illus0r** [comment]
Task interferes with #316

**Comment by jonnycoull** [comment]
Hi @illus0r its #390 the similar task in praqma, its closed. 

prio here is fixing colours, not copy that doesnt exist yet. on 316.

**Comment by jonnycoull** [comment]
HI @illus0r hows progress on this, as CODE-STOCKHOLMS page ( the next selling event) is still wrong colours for exe the CO in CODE is black. needs to be orange. amongst other things.

**Comment by jonnycoull** [comment]
@illus0r Hi mate, you need to fix this now, months have gone by and colours are STILL all over the place. see here OSLO is a pale purple, why??? This is the last time I'll ask on this matter. go through this chart and fix the site accordingly. today. 

![screen shot 2016-10-28 at 11 55 17](https://cloud.githubusercontent.com/assets/17589853/19804347/abd99cc6-9d05-11e6-88b4-d8b51dd0c3e8.png)
[CODECONF_COLOURS.pdf](https://github.com/Praqma/code-conf.com/files/558185/CODECONF_COLOURS.pdf)

**Comment by illus0r** [comment]
@jonnycoull sorry, I wasn't online yesterday and didn't see you message. I'll fix it now. I'm starting with colors

**Comment by illus0r** [comment]
https://github.com/Praqma/praqma.com/issues/390

**Comment by illus0r** [comment]
@jonnycoull I didn't find the `code-osl` event on the site. I guess, you want to rename [this one](http://code-conf.com/academy2016/osl/), am I right?

**Comment by illus0r** [comment]
Ah, missed this info
> ALL OSLO EVENTS TO USE THIS COLOUR EXCLUDING CODE ACADEMY.

@jonnycoull So I'll repaint all events, mentioned in PDF guidelines and fix colors only. They will look like

![image](https://cloud.githubusercontent.com/assets/797993/19830139/ccb74e26-9df9-11e6-9301-5072dd526ae3.png)

**Comment by jonnycoull** [comment]
Yes but the CO and DE need to be orange too

**Comment by illus0r** [comment]
@jonnycoull not a porblem, I'll fix. But they are black on PDF

And sorry for spoiling your weekend. I understand, that catching up on weekend is not normal. But I really want to fix problems I made for you. 

![image](https://cloud.githubusercontent.com/assets/797993/19830174/9240a9e4-9dfa-11e6-84a0-f43e6c66c677.png)

**Comment by illus0r** [comment]
@jonnycoull That's how they look in orange, let me know if you want to undo

**Comment by jonnycoull** [comment]
Hi Ivan, in orange looking good.

**Comment by illus0r** [comment]
@jonnycoull repainted the rest, is it ok?

![image](https://cloud.githubusercontent.com/assets/797993/19830258/8264cecc-9dfc-11e6-8ce8-de5aa525ab52.png)

![image](https://cloud.githubusercontent.com/assets/797993/19830260/95948d2a-9dfc-11e6-861f-898cc89363f2.png)

![image](https://cloud.githubusercontent.com/assets/797993/19830267/bc2e65fa-9dfc-11e6-9d48-840a5409cd31.png)

**Comment by jonnycoull** [comment]
Thanks @illus0r for fixing much appreciated. especially since its the weekend.

**Comment by illus0r** [comment]
@jonnycoull Thanks, man. I should notify you a week before that I wont do it in time. Shame on me 😁

I've pushed changes. I'll have to go soon, I'll be back late and want to continue the work. Would be nice to brief the tasks.

As I got, we'll close this task after that is complete:

- On [CODE-STHLM](https://github.com/Praqma/praqma.com/issues/390)
 - [ ] CO- to orange.
 - [ ] BLACK ICONS TO WHITE.
 - [ ] SUB HEADS TO ORANGE. (not on mock but needs doing)

What should be done else?

**Comment by jonnycoull** [comment]
I'm away from my main machine to check, but this looks right. Also good to
check through all locations and events to make sure correct colours are
used through the whole site. Where colours are darker, as per previous
examples the icons need changing to their white versions so more legible.
Also I noticed that the location icon has been used in the extras it should
be a circle with two arrows. It was uploaded some time ago. It appears to
have changed at some point.

**Comment by illus0r** [comment]
@jonnycoull, done-done?
![image](https://cloud.githubusercontent.com/assets/797993/19865472/6eff63c6-9fad-11e6-8087-036bd1222aa7.png)

**Comment by illus0r** [comment]
@timea 
placed the commit, but it's not integrated. http://code.praqma.net/ci/ doesn't load.

**Comment by jonnycoull** [comment]
hi @illus0r almost, or you can make this a new issue but it is related. that "location" icon needs switching out for this one. 
![extrasicon](https://cloud.githubusercontent.com/assets/17589853/19867429/af299f14-9f9b-11e6-89cc-18f771a0e024.png)
![extrasiconwhite](https://cloud.githubusercontent.com/assets/17589853/19867431/af429ec4-9f9b-11e6-9138-47acbeaca530.png)

**Comment by jonnycoull** [comment]
so colours done, issue 433 holds icon fault.

**Comment by jonnycoull** [comment]
actually just looked. CO in stockholm is still black. needs to be orange @illus0r  

![screen shot 2016-10-31 at 18 58 46](https://cloud.githubusercontent.com/assets/17589853/19867548/25b3585a-9f9c-11e6-9022-1098254fbd70.png)

**Comment by illus0r** [comment]
@jonnycoull have a look at https://github.com/Praqma/code-conf.com/issues/413#issuecomment-257375480, the commit doesn't integrate :(

**Comment by jonnycoull** [comment]
So how can we make it work? @illus0r

**Comment by illus0r** [comment]
@jonnycoull I poked Mads, Timea and Lars. Have no idea whom to poke next.

**Comment by jonnycoull** [comment]
Well I know Lars is very busy this week, try do do what you can
