### ISSUE TITLE
Second keynote speaker photo isn't shown properly

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/code-conf.com#415]
<img width="1019" alt="screen shot 2016-10-21 at 14 41 22" src="https://cloud.githubusercontent.com/assets/1671664/19598780/fe553e1a-979c-11e6-8754-99fdfc535cca.png">

I'm about to add the second speaker to the CoDe conf in Stockholm, but for some reason, his photo displayed in an oval. Is it how it is supposed to be?

**Comment by jonnycoull** [comment]
Possible that his image wasn't supplied as a square (the code makes it a
circle)

**Comment by Andrey9kin** [comment]
@adamhenriques

**Comment by Andrey9kin** [comment]
@jonnycoull do you have a possibility to adjust the photo? It is already committed on master. I tried to crop it but it doesn't seem to help

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/20260578/5e038ef8-aa6b-11e6-8a4d-564b5ae8f637.png)

It's fixed
