### ISSUE TITLE
Font size isn't good

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#417]
IN our header:
![image](https://cloud.githubusercontent.com/assets/155492/19679054/9ac1ff26-9aa0-11e6-9950-101cad827541.png)

The font size for call for papers, speakers, past events etc:
![image](https://cloud.githubusercontent.com/assets/155492/19679072/b18f8822-9aa0-11e6-99a9-2fe7e116c857.png)

Is far too small

**Comment by lakruzz** [comment]
@jonnycoull

**Comment by jonnycoull** [comment]
![screen shot 2016-10-25 at 17 03 02](https://cloud.githubusercontent.com/assets/17589853/19693839/f22d8ff8-9ad4-11e6-9436-0bc7c1d664a9.png)

@illus0r could you adjust the tracking (space between letters) to increase legibility please. size by a small amount.

**Comment by illus0r** [comment]
@jonnycoull How should I change the font-size?

**Comment by jonnycoull** [comment]
@illus0r you work in pixels right? look at my mock up scales should be similar to that

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/19883185/e243fccc-a023-11e6-944e-ccf8d5b1e741.png)
@jonnycoull is it ok?

**Comment by jonnycoull** [comment]
That looks better to me
