### ISSUE TITLE
Fix extas icon

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#433]
Currently shows location icon in extras on events. needs to be extras icon. 

![6eff63c6-9fad-11e6-8087-036bd1222aa7](https://cloud.githubusercontent.com/assets/17589853/19867452/ce6a99d2-9f9b-11e6-9980-7e7c23092277.png)
![extrasicon](https://cloud.githubusercontent.com/assets/17589853/19867457/d10d7b46-9f9b-11e6-8f62-79d1031d4f13.png)
![extrasiconwhite](https://cloud.githubusercontent.com/assets/17589853/19867458/d12a03b0-9f9b-11e6-8489-701300aa4e16.png)

**Comment by illus0r** [comment]
@jonnycoull but you've provided two icons, which to use?

**Comment by jonnycoull** [comment]
HI @illus0r the white icon  on on dark colours like the purple (as is on the current)  on the rest black as they are to match.

**Comment by illus0r** [comment]
- [ ] update pics on every similar pullout
- [ ] update colors of rest pullout all over the site

**Comment by illus0r** [comment]
Used white headers somewhere
![image](https://cloud.githubusercontent.com/assets/797993/19928027/b8e31418-a10d-11e6-86be-3e622b18f442.png)

**Comment by illus0r** [comment]
Note for myself: 

- [ ] http://localhost:3000/doc-cph-2016/
- [ ] http://localhost:3000/academy2016/osl/
- [ ] http://localhost:3000/events-past/

**Comment by illus0r** [comment]
@jonnycoull this task is awaiting for your feedback. Should I redesign other items this way?

**Comment by jonnycoull** [comment]
@illus0r this looks good. what other items are you referring too?

**Comment by illus0r** [comment]
@jonnycoull these ones

![image](https://cloud.githubusercontent.com/assets/797993/20002841/1a680518-a294-11e6-8c48-dcd952b1d514.png)


![image](https://cloud.githubusercontent.com/assets/797993/20002850/23060350-a294-11e6-9429-34e95727903f.png)
