### ISSUE TITLE
Add code alliance meetup

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#435]
@illus0r I'm really swamped in work and I could need a hand with the new meetup for the Code Alliance I'm announcing on Dec 5t

I've made a draft, but only got to work on it for a couple of mins - I'm busy at a customer, but this is becoming urgent.

Thef markdown is [here](https://github.com/Praqma/code-conf.com/blob/435-Add-code-alliance-meetup/_events/code-alliance-5th.md) on a branch called `435-Add-code-alliance-meetup`.

The information we need in there is already created by @adamhenriques in an [eventbrite setup](https://www.eventbrite.co.uk/e/the-continuous-delivery-alliance-gathering-tickets-29007858285)  You might need help with pictures, I hope @jonnycoull can help you.

If not, then try to finish without pics - I'll finde some as soon as I can.

**Comment by illus0r** [comment]
@lakruzz gotcha! I'll have a closer look tomorrow morning. I've `checkout`ed, but I see no event, strange. I'll investigate tomorrow

**Comment by jonnycoull** [comment]
@adamhenriques let me know what u need, ill jump on it tomorrow.

**Comment by illus0r** [comment]
I didn't see this page because of `--inclremental` option in `jekyll build`. Now I do.

**Comment by adamhenriques** [comment]
@illus0r will you confirm that youre on this one? and if you need anything else to move forward

**Comment by illus0r** [comment]
@adamhenriques I'm on it. Fixed the label. I've just started, reading the eventbrite now. Thanks, I'll be back if I need some help.

**Comment by adamhenriques** [comment]
@illus0r great thanks!

**Comment by illus0r** [comment]
@jonnycoull this page is a copy of another one, we need some graphics. When you'll be ready to help with?

Now page looks like (please, ignore repeating newsletter form)

![image](https://cloud.githubusercontent.com/assets/797993/19964081/c372c310-a1d0-11e6-8363-0e423380177d.png)

**Comment by illus0r** [comment]
@lakruzz @adamhenriques @jonnycoull 
Updated description, date, time, location, agenda, link to eventbrite.
@lakruzz and @jonnycoull, Who could supply images?

![image](https://cloud.githubusercontent.com/assets/797993/19965251/32638aba-a1d7-11e6-8a66-d7552d5baa64.png)
