### ISSUE TITLE
CoDe conf STHLM on front page as the highlighted event instead of CoDe Academy

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/code-conf.com#438]
@adamhenriques is it something you can take care of?

**Comment by adamhenriques** [comment]
@illus0r will you work your magic here, thanks!

**Comment by illus0r** [comment]
@adamhenriques 
It's an easy change, I'll explain how to do it in future.
Events on the main page are sorted by weight. So first one is the event with minimum weight.

![image](https://cloud.githubusercontent.com/assets/797993/20263451/c71e6442-aa77-11e6-9a4a-76a8aab52acd.png)

Default weight of the event is 9999999, so, if the weight is not set, the item, probably, will sink to the bottom.

**Comment by illus0r** [comment]
@lakruzz @timea the CI is down, so I keep pushing changes directly to `gh-pages`.

**Comment by Andrey9kin** [comment]
@illus0r thanks!
