### ISSUE TITLE
Use white boxes instead of white stripes for CoDe STHLM

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/code-conf.com#441]
<img width="959" alt="screen shot 2016-11-08 at 10 11 43" src="https://cloud.githubusercontent.com/assets/1671664/20093206/1b7662f0-a59c-11e6-8b62-c1f63570c3c5.png">

Would it be possible to use a solid white box as a background for the text on the snapshot instead of the white stripe? Currently is it hard to read due to bright purple background

http://www.code-conf.com/code-sthlm-2016/

**Comment by illus0r** [comment]
+1
@jonnycoull what's your point?

**Comment by jonnycoull** [comment]
@illus0r as nobody can write short copy we'll have to change the layout. the design was only ever meant for a shot piece of blurb, not long paragraphs. @illus0r adjust to copy in boxes similar to other parts of the site to solve this.

**Comment by illus0r** [comment]
@jonnycoull didn't get you. Do you mean to remove gaps between white line boxes on whole site?

**Comment by jonnycoull** [comment]
Just have the copy in a normal white box @illus0r as per this rough  mock ( yes i know its the wrong  font, use the one that on the site) and make it the sae everywhere its used. 

<img width="1009" alt="screen shot 2016-11-11 at 11 19 34" src="https://cloud.githubusercontent.com/assets/17589853/20213637/86bc888e-a801-11e6-9868-b323c8bfb0ef.png">

**Comment by Andrey9kin** [comment]
@illus0r @jonnycoull yes, this is exactly what I meant

**Comment by illus0r** [comment]
@jonnycoull will that work? I tried to make paragraph margins smaller, but didn't find an easy way to do it.
![image](https://cloud.githubusercontent.com/assets/797993/20264613/83685928-aa7d-11e6-93a8-681b40f30729.png)

![image](https://cloud.githubusercontent.com/assets/797993/20264647/b23d49ca-aa7d-11e6-870d-4af2b17637dc.png)

**Comment by jonnycoull** [comment]
Is there no way to lessen the gaps between copy?

**Comment by illus0r** [comment]
It's possible to do easily by merging paragraphs into a single paragraph. So they have a regular leading indent between

![image](https://cloud.githubusercontent.com/assets/797993/20265250/00344af4-aa81-11e6-8407-0a0cb525eb58.png)

But these margins will stay huge

![image](https://cloud.githubusercontent.com/assets/797993/20265276/38b551ac-aa81-11e6-9f1b-8cda45abd55f.png)

**Comment by jonnycoull** [comment]
That's ok.

**Comment by illus0r** [comment]
Fixed the rest and pushed
