### ISSUE TITLE
Change link for "Let's be friends"

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/code-conf.com#442]
Correct link is
https://www.facebook.com/codeconferences/

**Comment by monaslarsen** [comment]
<img width="387" alt="screen shot 2016-11-14 at 14 21 23" src="https://cloud.githubusercontent.com/assets/13627068/20266288/c9440d6e-aa75-11e6-9254-a599ddf91617.png">

**Comment by illus0r** [comment]
@monaslarsen is it clear how to fix it? Let me know if you need some tips

**Comment by monaslarsen** [comment]
Thanks @illusor, I should actually be able to do it myself, just hoped you
had time to do it, but I'll do it today myself :)

[image: ____________________________________________________________]
Mona Skorstengaard Larsen
Marketing Manager
mona@praqma.com
+45 40 21 95 04 <+45%2040%2021%2095%2004>
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/code-sthlm-2016/>
