### ISSUE TITLE
Fix display bug hiding eventbrite checkout

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/code-conf.com#453]

**Comment by meekrosoft** [comment]
<img width="1039" alt="screen shot 2016-11-29 at 09 02 53" src="https://cloud.githubusercontent.com/assets/145429/20701386/06957c54-b613-11e6-9e56-eea73ff2efd3.png">

**Comment by adamhenriques** [comment]
Mike,

We had the problem earlier;

...The solution is to adjust the height - trial'n'error until it fits using
the hight property:

{% include eventbrite-ticket-form.html
eventbriteid=page.checkout.eventbriteid
css_classes="black toprip botrip"
header="Enroll"
height="310"%}


[image: ____________________________________________________________]
Adam Henriques
Sales & Marketing
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/code-sthlm-2016/>

**Comment by meekrosoft** [comment]
Cheers @adamhenriques  - I found it.  Just waiting on Jenkins, but I guess that is down again?

**Comment by adamhenriques** [comment]
Yes, apperently a dockerhost is down.

[image: ____________________________________________________________]
Adam Henriques
Sales & Marketing
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/code-sthlm-2016/>
