### ISSUE TITLE
Make four titles to be clickable

### ISSUE THREAD

**Issue by JasmineCrozier** [Praqma/code-conf.com#457]
![screen shot 2016-12-12 at 11 41 02 am](https://cloud.githubusercontent.com/assets/24294535/21096395/0820a178-c060-11e6-9175-bddd2d3e6feb.png)

I would like these three links to be clickable: Conferences, Meet-ups, Hackathons towards the relevant code-conf pages.

However, "Training" could be linked to http://www.praqma.com/training/ (tbc)

**Comment by jonnycoull** [comment]
Should be easy, @illus0r make so on rollover headline white with underline, maybe we can swap image also?

**Comment by illus0r** [comment]
Doable!

**Comment by jonnycoull** [comment]
@illus0r Thinking white, with icon for each. or different shots. will have to dig through archive, carry on with other issues

**Comment by illus0r** [comment]
@jonnycoull if was complicated to wrap images in links, so I didn't do it by now. I can make an include for that, but I decided to ask for your advice. Do we need this?
