### ISSUE TITLE
Generic wrapper

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#48]
something like this:

![image](https://cloud.githubusercontent.com/assets/155492/13842499/c894c7ce-ec2e-11e5-8b10-0ba34615422a.png)

**Comment by illus0r** [comment]
@lakruzz 
We are not going to "take it out from the brackets", right? Just make it the same across every include.

**Comment by illus0r** [comment]
I didn't find a way **equal wrappers for all includes** can be useful. I took some classes into include variables, and made couple of fixes, but no more.

**Comment by lakruzz** [comment]
@illus0r 
OK!  
Not sure I understand, based on your comment, what happened, but your commit looks healthy enough - I just skim read it!

Keep it up! :+1:
