### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#50]
We only support two sizes:

Small <380
and medium > 380

@illus0r will have to come up with some minimal functioning design for moblie.

It doesn't have to be brilliant at this stage - it just has to be _not ugly_

@illus0r Feel free to grab hold of @jonnycoull and discuss it with him!

**Comment by illus0r** [comment]
I'll try to do it in 4 hours and then show the resut. It can turn out 4 hours are enough for good enough.
