### ISSUE TITLE
Complete the content

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#51]
We want to implement the data for Day of Containers in both Stockholm and Copenhagen

**Comment by lakruzz** [comment]
I Have asked @adamhenriques to give us the data we need for

- [ ] CoDe CPH
- [ ] CoDe STHLM
- [ ] Day of Containers CPH
- [ ] Day of Containers STHLM

He'll probably deliver it as for google docs - inking them onto this case - 

@adamhenriques, when you  are done - please assign the case back to me.

**Comment by adamhenriques** [comment]
@lakruzz for the two DOC's;

Copenhagen; https://docs.google.com/a/praqma.net/document/d/1APMfQiAmy1vNHXh36UE2xJ5EAirfCJF6_ragKy-2-6E/edit?usp=sharing

Stockholm; https://docs.google.com/a/praqma.net/document/d/1Q4slakcOWS-xBC2TA8Qvv2jQi_Rs7cXvit_JE9KBKgU/edit?usp=sharing

**Comment by adamhenriques** [comment]
For CoDeCPH16

https://docs.google.com/a/praqma.net/document/d/1kWniusaiD3ewLQkVvbtHCjo9aQctNGgQPpYjhycI6uM/edit?usp=sharing

**Comment by lakruzz** [comment]
continues in #61 closing this one
