### ISSUE TITLE
Implement the Front page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#57]
Follows #49

**Comment by illus0r** [comment]
@lakruzz we decided to make the only page with a conference for first publishing. Should we move this issue into next milestone?

**Comment by illus0r** [comment]
- [ ] unpublish CoDe STHLM
- [ ] get event colors from @jonnycoull

**Comment by illus0r** [comment]
CODE_STOCKHOLM - 660066 
DOC _STOCKHOLM - 9d006e
CODE_COPENHAGEN - 006666
CODE_COPENHAGEN - 539184
