### ISSUE TITLE
Mobile eventbrite

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#59]
spin off from #50 

I've used an eventbrite button on mobile because table is too big. Will this option work for us? It may require some extra settings on your side, [code of the button](https://github.com/Praqma/code-conf.com/blob/gh-pages/_includes/eventbrite-ticket-form.html) probably should be fixed.

![image](https://cloud.githubusercontent.com/assets/797993/13879626/76a8fab0-ed29-11e5-9092-43aa90c283ba.png)

Eventbrite provides different ways of button customization, I'd add an EB logo onto it

**Comment by lakruzz** [comment]
Yes - it's exactly what I had in mind :-) :+1:
