### ISSUE TITLE
Add content for CoDe STHLM

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#61]
Closed #51 without CoDe STHLM, moved it to it's own isseu

**Comment by lakruzz** [comment]
@adamhenriques have we cancelled the Continuos Delivery conference in Stockholm? So it does need to go online, is that is?

**Comment by adamhenriques** [comment]
@lars, no it is still on - so needs to go live, but in a very basic form. Ill supply content tomorrow. 

Regards

Adam Henriques
