### ISSUE TITLE
Style speakers

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#62]
![image](https://cloud.githubusercontent.com/assets/155492/13899489/fe81b3de-edef-11e5-8bc5-4b2ccdc4e967.png)

Make it look like Bok's mock-up:

![image](https://cloud.githubusercontent.com/assets/155492/13899499/3254afcc-edf0-11e5-8386-82f4d9f4d6e8.png)

**Comment by illus0r** [comment]
@lakruzz wow :) Fix my checklist before I estimate.

I'll work with http://new.code-conf.com/doc-cph-2016/

- [ ] add speaker icon to header
- [ ] make speaker names and social text in color
- [ ] fix font sizes and families
- [ ] move elements to be close to a mockup while it doesn't break the grid

**Comment by illus0r** [comment]
@lakruzz 
I'd use more readable font for abstracts. What do you think about?
![image](https://cloud.githubusercontent.com/assets/797993/13920452/26861c4a-ef84-11e5-869f-b16f4bd2b9ba.png)

**Comment by illus0r** [comment]
@lakruzz I tried not to fight against the grid too much, so the screen differs from original mockup. If you wanna bring it closer to a mockup, give me some directions, what to fix.

![image](https://cloud.githubusercontent.com/assets/797993/13920933/883f4478-ef86-11e5-99cd-2eba41a60220.png)


![image](https://cloud.githubusercontent.com/assets/797993/13920891/41a3b36e-ef86-11e5-8c95-bc9fea58ddcd.png)

**Comment by jonnycoull** [comment]
Hi Ivan, its nearly there. on the left hand side. it needs to line up. its about 5mm off to the right from the speaker down everything needs to be in a alignment coloumn. then that should bring in the right hand side. Does that make sense?

**Comment by illus0r** [comment]
@jonnycoull 
Hi! Did you mean alignment like this?

![image](https://cloud.githubusercontent.com/assets/797993/13949359/93460bd6-f035-11e5-803e-5fd678d37acb.png)

If yes, that's a good point. I'll need more time for that.

**Comment by jonnycoull** [comment]
yep thats it Ivan, spot on. Also don't forget the white line between main speakers and sub speakers.

**Comment by illus0r** [comment]
yep, sure!
