### ISSUE TITLE
Remove violet lines from the `date, location, time` icons

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#69]
![image](https://cloud.githubusercontent.com/assets/797993/13949745/dc0d8ad6-f037-11e5-81a6-3993e3204f97.png)

**Comment by illus0r** [comment]
these icons have transparent parts, filled by underlaying color. Now they have some violet rubbish

**Comment by jonnycoull** [comment]
Ill have to recreate these as plain negative items. and re-export

**Comment by jonnycoull** [comment]
Hi Ivan, not sure they uploaded properly. now in IMAGES, with a no 2 at the end. these should work.

**Comment by jonnycoull** [comment]
Hi Ivan, I put the new files on git and slack did u see them?
