### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#71]
size 152x152 (but good looking in 16x16)
filename should be **favicon.png**

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/13983267/ed8f4d78-f0ee-11e5-9319-24bb5fd5de8b.png)

**Comment by lakruzz** [comment]
http://www.favicon.cc/

**Comment by lakruzz** [comment]
16x16 px

**Comment by jonnycoull** [comment]
![favbig 1](https://cloud.githubusercontent.com/assets/17589853/13986031/05c591dc-f0f8-11e5-9fb8-e796db9582e9.png)
![favbig 2](https://cloud.githubusercontent.com/assets/17589853/13986030/05c532be-f0f8-11e5-91b5-0d7054775f7a.png)


![favsml 1](https://cloud.githubusercontent.com/assets/17589853/13986032/05c5ad02-f0f8-11e5-89be-5f1314420b67.png)
![favsml 2](https://cloud.githubusercontent.com/assets/17589853/13986029/051cd4c0-f0f8-11e5-8da3-fed7a4d8ebc2.png)

**Comment by jonnycoull** [comment]
I can't upload ICO to here.

**Comment by jonnycoull** [comment]
![favicon](https://cloud.githubusercontent.com/assets/17589853/13986582/0c696c90-f0fb-11e5-9db8-3600a1e6fd96.png)

**Comment by lakruzz** [comment]
http://stackoverflow.com/questions/2208933/how-do-i-force-a-favicon-refresh
