### ISSUE TITLE
Plain listing of all events 

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#72]
We need a plain vanilla (full - non-edited) listing - of all events:

Conferences:
Meetups:
Training:
Hackatones:

(spin off from #49)

**Comment by lakruzz** [comment]
This what our curretn front page is trying to do.

If we created this list or directory of all that's available, then we coulld let the frontpage show what is featured, up next or something.

This one is related to #88

**Comment by jonnycoull** [comment]
![screen shot 2016-04-19 at 15 44 44](https://cloud.githubusercontent.com/assets/17589853/14643594/e2869c3e-0646-11e6-90b2-9d82dceae54a.png)

**Comment by jonnycoull** [comment]
a page that links from the above panel a full listing page.

**Comment by jonnycoull** [comment]
So while I'm planning on how to today up the home page, here's how the panel and links will navigate. So any direct link for exe DOC-STOCKHOLM, if you click that it takes you directly to the page, also any of the direct links in the mini list. Now, if you press CONFERANVCES - MEETUPS etc in the top bar or SEE ALL in the mini bar the below image is where you will end up. a directory of all events, which can be filtered specifically or list all. in list all view theres a small sub head to say what it is, conference meet up etc. Maybe you can use internet wizardry @illus0r so when a conferences passes it auto jiggles to move stuff around and slips it into an archive. also the headings are what indicates a link so if you hover over the square, the underlines appear. make sense? I know it isn't using actual data, but @lakruzz does this look ok? Also all the pages here are in one long file to save uploads. cool?
![subpage](https://cloud.githubusercontent.com/assets/17589853/14748522/10c8578c-08b2-11e6-89a7-e4b88c10ce30.jpg)

**Comment by jonnycoull** [comment]
image for top uploaded. @illus0r

**Comment by jonnycoull** [comment]
@illus0r image has been uploaded for the top, then this can be closed.

**Comment by illus0r** [comment]
Great, closing
