### ISSUE TITLE
Style the meetup pages

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#75]
Bok had a preliminary lay-out for the meetup pages. We need to finish that.

**Comment by jonnycoull** [comment]
@lakruzz what goes in a meet up page, information wise?

**Comment by jonnycoull** [comment]
Hi @lakruzz @illus0r so I've had a go at a page, code cafe for examlple (or is that a hackathon) regardless other than a colour I think we can reuse some elements on both. here's a V1, so main body copy times and the usual, plus a button to take you too meet-ups own site. (or have it work internally one for you @illus0r ) So and overview then maybe pull out 3 things that will happen that day? just an idea, really need an example of an old one to work off of. 

![codeconf_meetups](https://cloud.githubusercontent.com/assets/17589853/14861557/b146dc6e-0ca5-11e6-90b6-af57e4237893.jpg)

**Comment by illus0r** [comment]
@jonnycoull Great!
The main point of the page is `Sign up` button, now it's not notable, especially near the bright photo.

![image](https://cloud.githubusercontent.com/assets/797993/14884920/e85b91ee-0d50-11e6-9627-827bae5b4218.png)

What user will do after scrolling down the page? Now he is supposed to scroll back to top to sign up. I'd duplicate or moved this button to the bottom of the page, possible with call to action. Like 
*"Wanna join? `Sing up now!`"*

`Let's hang out` block looks encouraging. I'd move `Learn` to first place though. Still I believe `Eat` is a pleasant bonus, not the essence 😀 

And what'll happen if description is three times longer? :trollface:

**Comment by jonnycoull** [comment]
• Another button at the base then, to make it easy for the user. good thinking batman.
• A sort of bullet pointed aspects of the meet up, thats all dummy copy in there for now. So the description isn't a huge long block of text.
• the writer will craft an amazing piece of copy that fits to length, lets not waffle on. if its longer id suggest another panel image next to it, but I think you could get across a brief description in that and using the 3 panels below to flesh anything out.

**Comment by jonnycoull** [comment]
![codeconf_meetups_v2](https://cloud.githubusercontent.com/assets/17589853/14985628/383d5e98-1140-11e6-985c-7a7fc576c046.jpg)
Big strap at the bottom? @illus0r @lakruzz

**Comment by jonnycoull** [comment]
@lakruzz should we have a hangout on this?

**Comment by lakruzz** [comment]
YES I want this online as soon as possible!!!

The GitHub event should be one that fits this format:

[Next.Generation.Software.Development.Seminar.pdf](https://github.com/Praqma/code-conf.com/files/304518/Next.Generation.Software.Development.Seminar.pdf)

**Comment by lakruzz** [comment]
Let's create some task that can implement a MVP of this page and add it to the milestone named [Meetup pages](https://github.com/Praqma/code-conf.com/issues?milestone=12)

**Comment by lakruzz** [comment]
Use the content from Next.Generation.Software.Development.Seminar.pdf (attached above)

**Comment by lakruzz** [comment]
Have a look at past events in http://www.meetup.com/code-u/   and  http://www.meetup.com/Jenkins-Copenhagen-JAM/ for more inspiration - these events are representative for what we're trying to communicate

**Comment by jonnycoull** [comment]
I've made one out of jenkins jam. @lakruzz take a look. will rework for GITHUB as well.

![codeconf_meetups_jam](https://cloud.githubusercontent.com/assets/17589853/15905992/fb4976d0-2dae-11e6-8a47-e9cb10721a0d.jpg)

**Comment by jonnycoull** [comment]
@lakruzz and GIThub, thoughts? as you can see the workshops etc could be interexcangable with whatever elements you need. 

![codeconf_meetups_git](https://cloud.githubusercontent.com/assets/17589853/15907333/a3df616a-2db4-11e6-81eb-14f0e9877a3a.jpg)

**Comment by illus0r** [comment]
@lakruzz what a proper moment of closing `Size 0` issues?

**Comment by lakruzz** [comment]
When we have hammered out all the issues we need from it -we don't need the
briefing case (open) anymore - it's still available for reference even if
it's closed.

Have a quick reed of
http://www.praqma.com/stories/milestones-and-officehours/

**Comment by illus0r** [comment]
Thanks! I'll read tomorrow morning.

**Comment by timea** [comment]
As everything is listed in other issues, this issue can be closed.
