### ISSUE TITLE
Redirect link for Day of Containers

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/code-conf.com#79]
http://www.code-conf.com/day-of-containers-cph16/ 
must be redirected to the new DoC site

**Comment by monaslarsen** [comment]
http://www.code-conf.com/day-of-containers-cph16/ 
to
https://www.eventbrite.co.uk/e/day-of-containers-copenhagen-2016-tickets-20856339874

and 
http://www.code-conf.com/day-of-containers-sthlm16/ 
http://www.eventbrite.co.uk/e/day-of-containers-stockholm-2016-tickets-20692623193

**Comment by illus0r** [comment]
How to access the code-conf.com repo?

**Comment by monaslarsen** [comment]
Good question - what if you use https://github.com/CoDeConf/CoDeConf.github.io instead?

**Comment by illus0r** [comment]
@monaslarsen `master` branch or which one?

**Comment by monaslarsen** [comment]
I'm sorry, I'm not trained in that part yet :/
I guess we will need to talk to @lakruzz..?!

**Comment by illus0r** [comment]
@monaslarsen wait, I'll try to understand

**Comment by illus0r** [comment]
@monaslarsen 
Please, use evenbrite's admin section to generate `html` widget for the widgets. They should look like

```
<div style="width:100%; text-align:left;" ><iframe  src="//eventbrite.co.uk/tickets-external?eid=20856339874&ref=etckt" frameborder="0" height="260" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:100%; text-align:left;" ><a class="powered-by-eb" style="color: #dddddd; text-decoration: none;" target="_blank" href="http://www.eventbrite.co.uk/r/etckt">Powered by Eventbrite</a></div></div>
```

Links are now enough

**Comment by monaslarsen** [comment]
I don't need new widgets - I need the link to redirect :)

**Comment by illus0r** [comment]
@monaslarsen what do you mean by `redirect`? Send the user automatically to another page without a prompt? Or you want to provide a link to an eventbrite?

**Comment by monaslarsen** [comment]
Send the user automatically to another page without a prompt! :dart:

**Comment by illus0r** [comment]
@monaslarsen Yo :hushed: User will loose navigation at once. It will not understand, where did he jump. Big link is definitely better. What do you think about?

**Comment by monaslarsen** [comment]
I have an even better idea: Can you just change the places where it says the date?
Old sites refer to March and April, but I need them to refer to the dates in August!

**Comment by illus0r** [comment]
I have no access to a repo. Here's a patch
[patch.txt](https://github.com/Praqma/code-conf.com/files/193573/patch.txt)

**Comment by illus0r** [comment]
@monaslarsen even better! I made a pull request https://github.com/CoDeConf/CoDeConf.github.io/pull/39
You can just apply it

**Comment by lakruzz** [comment]
Eeeeh sorry to disappoint you guys @illus0r and @monaslarsen  

BUT  CoDeConf/CoDeConf.github.io is deprecated - I've just changed the url from www.code-conf.com to was.code-conf.com

The new orange is this repo, where you have this issue: Praqma/code-conf.com

I have just changed the URL from new.code-conf.com to www.code-conf.com

**Comment by illus0r** [comment]
:tada:
