### ISSUE TITLE
Use rouge - not pygments

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#82]
The page build completed successfully, but returned the following warning:

You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

**Comment by illus0r** [comment]
@lakruzz Where do we highlight code on code-conf? :hushed:
I can change the value in config, though :)

**Comment by lakruzz** [comment]
The _config.yml says

    highlighter:pygments

it should be changed to 

   highlighter: rouge

....that's it (gh-pages no longer supports pygments)

**Comment by illus0r** [comment]
I take this

**Comment by illus0r** [comment]
Done by Lars in edf2693
