### ISSUE TITLE
Make an academy page

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#84]
> Yep, lets’ start by handing over the original mock up to @illus0r  - he might have feed back.
But the most important part - is to get content on code-conf.com/academy2016 - the copy is roughly what went into the poster/flyer - but it needs to be hosted on code-conf.com in our recognizable lay-out - not on praqma.com (as it currently is) 
[Lars on Slack](https://praqmacollaborator.slack.com/archives/code-conf/p1459764523000004)

Poster/flyer: [code_acadamey.pdf](https://github.com/Praqma/code-conf.com/files/206123/code_acadamey.pdf)
Mockup: [codeconf_academey.pdf](https://github.com/Praqma/code-conf.com/files/206535/codeconf_academey.pdf)

Info to be added
===

**A modern continuous delivery bootcamp for graduates**

Continuous Delivery Academy!
---
So you’re a student in the field of Computer Science - cool! But still, you get that sinking feeling that you’re missing out on important best practices of the modern  era of Continuous Delivery and DevOps ? 

It’s free Honestly!  
--- 
Students are offered a free seat at the code academy! The only catch is that each day there will be a pitch from one of the sponsors about their company. But then again, they’re only here to recruit, so it makes sense right? But seriously, the lunch will be free . 

Learn the latest skills! 
--- 
Five days of intense hands-on continuous delivery training; A primer on Agile teaching you to groom tasks. Advanced version control with Git. Build and test automation with Jenkins. Test Driven Development to build quality in! Build, Ship, Run with Docker . 

Where it’s happening! 
--- 
Academies will take place from mid Aug to start Sept in Copenhagen, Aarhus, Oslo & Trondheim. Training will be in English, a full week 9-16 every day. You’re eligible to enroll if you are either a student or unemployed recent graduate in a fi eld related to computer scienc e 

But why? 
--- 
Here’s the thing - demand for Continuous Delivery and DevOps skills is far outstripping what is available the in the job market. We at Praqma are feeling this most acutely. So we thought; Why do we only train our new recruits? Why not train everyone looking for work! So that not only Praqma employees get these skills but all people entering the industry ? 

Supporters 
--- 
Each location will have fi ve companies supporting the academy, Companies are looking to recruit in this fi eld - you’ll be given a pitch by each one of them. Each Academy season has a set of technology sponsors as well. They are just happy to support the Continuous Delivery and DevOps revolution - and throw you swags.

**Comment by illus0r** [comment]
The most dumb version can look this way

![image](https://cloud.githubusercontent.com/assets/797993/14313477/8bbe7eae-fbfa-11e5-93da-79efa45472d3.png)

**Comment by illus0r** [comment]
@lakruzz 
Pushed something to `84-Make-an-academy-page` branch
Need your feedback

![image](https://cloud.githubusercontent.com/assets/797993/14314511/4a4ab0f4-fc00-11e5-9d61-d649b20f7052.png)

**Comment by jonnycoull** [comment]
[CODECONF_ACADEMEY.pdf](https://github.com/Praqma/code-conf.com/files/206287/CODECONF_ACADEMEY.pdf)

Can you take a look at this i posted it on Slack, maybe you didn't see it? @illus0r

**Comment by jonnycoull** [comment]
I'm putting images in the repository.

**Comment by illus0r** [comment]
- [ ] crop 6 images
- [ ] style *Where it’s happening*
- [ ] style *Interested?*

**Comment by lakruzz** [comment]
@illus0r @jonnycoull 
Fine.

Good work @illus0r! I was about to say _"It needs a little bit of love from Bok"_ and then I saw his mock-up @jonnycoull I love it!

Could we go in that direction?

__Note:__ You don't have to make room for the form, we'll just put a registration from Eventbrite there (as on the events):

![image](https://cloud.githubusercontent.com/assets/155492/14319500/bc44d156-fc11-11e5-9036-19e3e2a3f695.png)

 and then we'll ask he questions as part of the signup process.

**Comment by illus0r** [comment]
@lakruzz what's eventbrite event id?

**Comment by illus0r** [comment]
@lakruzz 
Pushed to a `84-Make-an-academy-page` branch :octocat: 

Not everithing is according to mockup. Some things like eventbrite changed and needed redesigning. Some things changed in sake of readability (made left alignment for text) and consistency (made `p` font as on the rest of the site)

I made some changes to text. Sorry, I've removed some exclamations from headers because they made text overstressed. To much exclamations — none exclamations at all. You can bring them back though :)
Some minor copy changes as well: replaced `-` with `—`, set quote, highlighted with bold cities in `location` section.

That's strange to find a date in `location` 😶 

Didn't push to gh-pages still we have no *eventbrite id*

![image](https://cloud.githubusercontent.com/assets/797993/14352146/bf1c59b0-fcdb-11e5-886b-d2a930218c46.png)
![image](https://cloud.githubusercontent.com/assets/797993/14352151/cd559618-fcdb-11e5-9122-2a38157bfa73.png)
