### ISSUE TITLE
Call For Papers box

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#86]
I would a call for papers box as below on the individial conference pages somewhere. Is this possible? If so - it should point to ; http://goo.gl/forms/jtYzixrCSE

![screen shot 2016-04-08 at 12 13 14](https://cloud.githubusercontent.com/assets/8004259/14381044/a38c603e-fd83-11e5-8fb9-3815901c8a90.png)

**Comment by lakruzz** [comment]
@adamhenriques regarding the form. Please consider if these questions are really relevant to ask in the form:

![image](https://cloud.githubusercontent.com/assets/155492/14417602/be277254-ffb7-11e5-896c-e495b6e925cc.png)

**Comment by adamhenriques** [comment]
@lakruzz have reveiwed and updated form.

**Comment by illus0r** [comment]
@adamhenriques so we need to make a link under the speakers, which leads to [the google form](https://docs.google.com/forms/d/1w81_c5vqhcWcWRHLv2I1RpOYPE25OPpqxexVfx3W_O8/viewform?c=0&w=1). Right?

**Comment by illus0r** [comment]
@adamhenriques should it form be available on every *speakers* module?

**Comment by adamhenriques** [comment]
@illus0r could we place it next to "Sponsor Inquiries"?

**Comment by illus0r** [comment]
@adamhenriques I can everything :) But I'm not sure that's a good idea: we already have a lot there
![image](https://cloud.githubusercontent.com/assets/797993/14852073/dbcebb14-0c8c-11e6-89f6-9de0c54c7b70.png)

We could move this link to footer, that'll require some redesigning. That refers to #91

**Comment by jonnycoull** [comment]
To quote Jaws, "were gonna need a bigger boat". OK @illus0r ill make an amended menu system like we spoke about.

**Comment by adamhenriques** [comment]
Good point. As long as its visible im good with that. 

Regards

Adam Henriques

**Comment by lakruzz** [comment]
One thing is that we need a link in the menu (taken care of in #135)  

But we also need a design to hold the form!

Maybe it's just the plain standard layout - I'll give it a go!

**Comment by lakruzz** [comment]
@adamhenriques I've closed this one. Have a look at http://www.code-conf.com/cfp/

Is that what you wanted?

![image](https://cloud.githubusercontent.com/assets/155492/15048909/de029562-12eb-11e6-8c14-c2cf1f4800f6.png)
