### ISSUE TITLE
A sponsor button / contact

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#87]
I would like if we could have a sponsor contact somewhere - this can be just a button for email / request for contact 

![screen shot 2016-04-08 at 12 13 30](https://cloud.githubusercontent.com/assets/8004259/14381241/1f236bce-fd85-11e5-840b-4c0b7dc3fdc5.png)

**Comment by illus0r** [comment]
@adamhenriques good thing! What form should the button lead to?

**Comment by adamhenriques** [comment]
Im thinking either just opening an email preset to go to me - then I can
engage with them. At least they would be an easy fix in the shot run - or
is there a better solution?

[image: ____________________________________________________________]
Adam Henriques
CMO
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>

**Comment by illus0r** [comment]
@adamhenriques Good, that looks doable with ease. I'll branch out a task for @jonnycoull

**Comment by illus0r** [comment]
> just opening an email preset

@lakruzz fixed this, but it should be improved: not everybody has email client set up properly. I didn't.

**Comment by illus0r** [comment]
possible solution is formspree.io form
