### ISSUE TITLE
Update footerbar

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#90]
We need to update footer bar on http://www.code-conf.com/ from saying "The Continuous Development People" to " The Continuous Delivery Company"

**Comment by lakruzz** [comment]
Super high, alert, stop press priority on this one @adamhenriques

**Comment by illus0r** [comment]
May be footer should be as on *code-maturity*?
> The Continuous Delivery and DevOps Company

@lakruzz how to treat tasks with priority set by @adamhenriques?

**Comment by adamhenriques** [comment]
So no priority?

Regards

Adam Henriques

**Comment by lakruzz** [comment]
Mr Wolf:

"Pretty pleas with sugar on to. Just clean the fucking car"

**Comment by lakruzz** [comment]
We need to establish a way of working, where my footprint on the process is mininized. I don't wanna do micro management.

If @adamheriques says it needs to be done. Then his word is as good as mine.

**Comment by lakruzz** [comment]
I don't kbow what

> So no priority?

Means.

In my book this is URGENT!

**Comment by lakruzz** [comment]
We are __NOT__ "the continuous development people"

**Comment by illus0r** [comment]
I'll fix soon
