### ISSUE TITLE
Sponsor's button design

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#91]
Subtask of #87

We need a kind of 
![image](https://cloud.githubusercontent.com/assets/797993/14463786/15ade29c-00d5-11e6-871c-ba4bb4ed1a89.png)

button in our sponsoring section

**Comment by jonnycoull** [comment]
@illus0r where does this button live?

**Comment by illus0r** [comment]
@jonnycoull have a look at patent task #87. Be back with any questions

**Comment by jonnycoull** [comment]
@illus0r i'd have a top bar nav thats SPONSOR INQUIRES. so its always easy to get to. also on the main page at the bottom a sponsor box.

**Comment by illus0r** [comment]
@jonnycoull can you suggest a mockup to discuss with Lars?

**Comment by jonnycoull** [comment]
@illus0r @lakruzz here's my suggestion, that its always important to find easy access to this on every page so it should live in the menu bar. see attached. Also maybe an additional small link on pages that have sponsors at the base of the page saying. _Interested in sponsorship. Click here._
Ive also added all the menu items i believe we need currently. maybe a contact one too? but easily aded. small orange line dividing up the words.

![menu](https://cloud.githubusercontent.com/assets/17589853/14744944/d3a80ec6-08a0-11e6-9be5-6b5500af463f.jpg)

**Comment by illus0r** [comment]
@jonnycoull Good! 

It's easy to mix **sponsor inquiries** item with _event navigation_. Moving the _event nav_ next to the logo helps us to separate menu items (_event navigation_ from _company related_). The good side effect is that users can get an idea of **code-conf** just looking at logo and menu items next to it.

Have a look, vertical lines do not split items, they visually join them. They bring some visual noise as well. The best way to separate items is to make a gaps between.

![image](https://cloud.githubusercontent.com/assets/797993/14782425/f05dc6e8-0af1-11e6-8d3f-cab2b2954549.png)

**Comment by jonnycoull** [comment]
@illus0r can we put it the way I had it please that looks messy being aligned left and right. also the reason for the lines is that sponsor inquires is two words, i don't want it to look like its two separate items, hence the equal gaps and the lines to create a visual aid for the items. all items are main site navigation so they need to be together.  and to let the band / logo breathe.  also at some point I'm thinking we need CONTACT on there as well so this is another reason why I have designed it as such.

**Comment by jonnycoull** [comment]
Our answer lies in issue #135 so I think we can close this.
