### ISSUE TITLE
GitHub on Praqma.com

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#96]
If we want Git on frontpage - what is the angle;

- Services - what do we offer?

**Comment by lakruzz** [comment]
@adamhenriques hmmm are we talking about code-conf.com? This belongs to a different [repo](https://github.com/Praqma/praqma.com) doen't it?

**Comment by adamhenriques** [comment]
Yes, sorry. This is Praqma.com

Regards

Adam Henriques

**Comment by lakruzz** [comment]
@adamhenriques I'm closing this one then - you should create the issue in the right repo
