### ISSUE TITLE
Headers needs ID's

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#97]
Exemplified by the tickets block:

![image](https://cloud.githubusercontent.com/assets/155492/14521327/13b6c88c-0229-11e6-9e07-50003864405e.png)

It's implemented as:

```
<h1>Tickets</h1>
```

But I need it to be 
```
<h1 id="tickets" >Tickets</h1>
```

(MarkDown automatically adds id's to headers!)

I want to be able to do:
```
http://www.code-conf.com/code-cph-2016/#tickets
```

**Comment by illus0r** [comment]
still we use html to render snippets, we'll have to do this manually.
```
<h1 id="tickets">Tickets</h1>
```
Other possible solutions: 1️⃣ usage of js or 2️⃣ usage of markdown inside includes. 2️⃣ seams more complicated than current solution:

```
<div markdown="1">
# Tickets
</div>
```

**Comment by illus0r** [comment]
Fixed other includes. For others
```
    <h1 id="{{ include.caption | slugify }}">{{ include.caption }}</h1>
```
suits better
