### ISSUE TITLE
Hide date-location factoids if no data given

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#98]
![image](https://cloud.githubusercontent.com/assets/797993/14562492/a3c93728-0325-11e6-9b55-3127675b7094.png)

**Comment by lakruzz** [comment]
@illus0r go ahead

**Comment by lakruzz** [comment]
@illus0r seems like you have implemented this - did you forget to close it?

![image](https://cloud.githubusercontent.com/assets/155492/14585497/eaebe4a8-0478-11e6-83ae-321aef625e0c.png)

**Comment by lakruzz** [comment]
@illus0r it seems like you implemented this already - did you forget to close?

![image](https://cloud.githubusercontent.com/assets/155492/14585498/036120f2-0479-11e6-81c3-a7c3e3fa8ce8.png)

**Comment by illus0r** [comment]
@lakruzz not me. Current state is not beautiful: wether we have a hole in the list 
![image](https://cloud.githubusercontent.com/assets/797993/14636768/295c9e1c-0636-11e6-948b-31f84ed119ad.png)


...or broken rhythm

![image](https://cloud.githubusercontent.com/assets/797993/14636800/41a90ef6-0636-11e6-9ef7-467048c9106e.png)

the simplest solution is to fill tha gap with some useful info: date range, place (list available cities) or _________ (add your option)

**Comment by illus0r** [comment]
if so, size is `medium`

**Comment by jonnycoull** [comment]
What is this big list?

**Comment by illus0r** [comment]
@jonnycoull that's our frontpage
@lakruzz @jonnycoull I'd also nest all academy subpages into the parent academy page. Made a rough mockup for that. It will not work if some nested academies will have other dates.
![untitled-1](https://cloud.githubusercontent.com/assets/797993/14637451/fa2a2340-0639-11e6-8346-543f51d91cd4.png)

**Comment by jonnycoull** [comment]
I think I'll have to re visit the colour coding for CODE ACADEMEY, were getting a bit rainbow esc/ complicated with all these additions. @illus0r @lakruzz

**Comment by illus0r** [comment]
@jonnycoull good! ping me when you done

**Comment by lakruzz** [comment]
I would actually like to leave this one behind as "Won't have" - and then work on - and prioritize - #100 instead.

@illus0r @jonnycoull 
Is that OK with everyone? let's not waste our time :-)
